### ISSUE TITLE
Create User Permissions Set to false

### ISSUE THREAD

**Issue by damian-pf** [AsgardCms/Platform#103]
To replicate this bug follow these steps
1. Go to Users > Users > New User
2. Fill in the Data tab fields
3. Click Roles tab and select a Role
4. Click Create (do not do anything with/on Permissions tab)

Now either log in with the new user (won't have Dashboard access) or view the database entry in the users table. The database will show you that the user has had permissions all set to **false**.

**Comment by damian-pf** [comment]
### Update
To solve this issue I have:
* removed the permissions tab from the create user view
* made Roles a required field so that a user always has permissions

If you are happy with this solution I can submit a PR?

**Comment by arturmamedov** [comment]
I think its no good to remove the permission tab, where you can place it otherwise? We need It to grant extra permission to users! But if you set the role field mandatory and after generate the permission tab merged with role permissions i think its work very well.

**Comment by kielabokkie** [comment]
@arturmamedov I think just setting the user role when creating a new user should be sufficient. How often will you need to tweak the permissions for a new user when you already have roles with pre-defined permissions?

You can always edit the user if you need to grant extra permissions to a specific user.

**Comment by arturmamedov** [comment]
@kielabokkie sorry i miss the ON CREATE, yes you right on create nobody need the extra permissions.

**Comment by kielabokkie** [comment]
@nWidart What are your thoughts on this?

**Comment by nWidart** [comment]
I'm following the thread, just busy with work lately. :smile: 

Not sure I understand why on create we won't want to add extra permissions to a user.

Say you have a new moderator that doesn't belong to any specific group, you create his account and directly give him the desired custom permissions. 

This wouldn't be possible if the permissions tab is removed from the  create view, or am I missing something?

**Comment by damian-pf** [comment]
@nWidart I think you need to replicate the issue to fully understand. Create a user with the above steps and then attempt to log in with that user.

**Comment by joshbrw** [comment]
I know this issue all too well. What happens is when you give a User a Role you'd expect them to inherit the permissions from that Role automatically (especially if you leave the checkboxes blank on the Permissions tab), but they don't inherit and they all get set to false if you don't select any. (I think that's what you mean?)

I fixed this on my project by checking if they hadn't ticked any permissions on the permissions page to take them from the role and leave the `permissions` column on the `users` table as `{}` (or `[]`).

I will try and implement a fix for this over the next few days.
