### ISSUE TITLE
Empty database after install

### ISSUE THREAD

**Issue by teodorsandu** [AsgardCms/Platform#104]
Hi,
I installed AsgardCms/Platform by git clone method, then run ```composer install```, edited env file and finally run ```php artisan asgard:install```. All seemed ok:
```
Writing lock file
Generating autoload files
> php artisan clear-compiled
> php artisan stylist:publish
AdminLTE assets published.
Flatly assets published.
Assets published.
> php artisan module:publish
Published: Core
Published: Dashboard
Published: Media
Published: Menu
Published: Page
Published: Setting
Published: User
Published: Workshop
> php artisan optimize
Generating optimized class loader

C:\wamp\www\laravel\asgard\Platform>serv
Laravel development server started on http://localhost:8000/
[Tue Sep 01 06:44:58 2015] 127.0.0.1:62649 [200]: /favicon.ico
^C
C:\wamp\www\laravel\asgard\Platform>php artisan asgard:install

  Welcome!
  Starting the installation process...

Asgard has already been installed. You can already log into your administration.
```
but I get this error:
![image](https://cloud.githubusercontent.com/assets/5700488/9596605/07cce880-5077-11e5-8f0f-bbf2ad544ab2.png)

(because) the database remains empty. Should I run some seeds?

**Comment by nWidart** [comment]
Hello,

I'm very sorry for the delay!

I see the installation process did not complete.
This is likely because you already have a `.env` file inside your project root.

You can either remove that file, or run `php artisan asgard:install --force` to overwrite it.

The installation process will migrate and seed the necessary data.

**Comment by teodorsandu** [comment]
Thank you very much, that worked! :)

waiting for more updates!

**Comment by nWidart** [comment]
Awesome :smile:
