### ISSUE TITLE
MediaModule folder_id mandatory but null

### ISSUE THREAD

**Issue by tk-s** [AsgardCms/Platform#106]
Hi, 
at least with Postgres, i cant upload a file, because folder_id is null - wich is not allowed...

if i add 'folder_id' => 0, to the Array at
https://github.com/AsgardCms/Media/blob/develop/Repositories/Eloquent/EloquentFileRepository.php#L40

it works as expected

**Comment by tk-s** [comment]
Addition: this looks like its a postgres-related bug, since postgres wont accept "" as input for an integer field.

**Comment by nWidart** [comment]
Hm interesting, I haven't tested asgard on anything but Mysql, I'll have to look into that.
Postgres wants `0` I'm guessing ?

**Comment by tk-s** [comment]
Yes, it does - i am not shure if i posted my solution (or created a PR)?
(Its working in my current installation)

Am 08.09.2015 um 10:16 schrieb Nicolas Widart <notifications@github.com<mailto:notifications@github.com>>:


Hm interesting, I haven't tested asgard on anything but Mysql, I'll have to look into that.
Postgres wants 0 I'm guessing ?

**Comment by nWidart** [comment]
Pushed the fix https://github.com/AsgardCms/Media/commit/af201b25a01863d140f8e2e1d4396dc5cd858f47 :smile:
