### ISSUE TITLE
Missing the vendor folder

### ISSUE THREAD

**Issue by rvmladenov** [AsgardCms/Platform#108]
Running step 2 in the installation guide throws exception saying: "bootstrap/../vendor/autoload.php: failed to open stream. No such file or directory"

**Comment by nWidart** [comment]
Did you install using the `create-project` command ? The create-project command does a composer install, though if you used `git clone`, you need to manually run `composer install`

**Comment by rvmladenov** [comment]
Well, I am following the installation guide which includes only these steps:
* composer create-project asgardcms/platform your-project-name
* php artisan asgard:install

**Comment by nWidart** [comment]
I know for a fact the composer create project command installs dependencies, so you probably used some other command. Composer commands are not related to AsgardCms. 

If vendor is missing, install dependencies and you'll have it like any other project with composer.

**Comment by rvmladenov** [comment]
I know what I did and the problem is not me ...
