### ISSUE TITLE
Wildcard permissions

### ISSUE THREAD

**Issue by zach2825** [AsgardCms/Platform#109]
Im working on something and the route could be something like
Randommodule/{random id}/create

I've tried in the "Randommodule/Config/permissions.php" file adding "randommodule.*.create" and a few other things without luck. Do you know of a workaround or anything to try? 

In the current permissions system i cannot figure out how to wild card add ids or the binding to allow for roles or users. instead i keep getting 
"Permission denied. (required permission: "Randommodule.1.create")"

**Comment by nWidart** [comment]
This probably wont get added, but with the permission system that might get added it will be easier to manage permissions. #145
