### ISSUE TITLE
Users Module. Pagination Does Not Work

### ISSUE THREAD

**Issue by danrichards** [AsgardCms/Platform#110]
I was seeding my users table and noticed some bugs in with the pagination in the Users module. I performed a clean install and retested (using the admin to create 10 users, 11 total) and the issue persisted.

When you first visit the users module, you get a list of all users, although the default # entries is 10. This will get bad once you have more than a few hundred users and should default to entry in the dropdown.

Additionally, the pagination links don't work. All you can browse are the first N (dropdown) results. Oddly, if you browse 100 users, then click page 2 (nothing happens), but then change to 10 users, you'll be able to see users 101~110.

There is a "Uncaught TypeError: Cannot use 'in' operator to search for 'length' in " in Chrome's console when using pagination, probably the cause.

**Comment by oimken** [comment]
Update DataTables (1.10.9)  will solve that problem .....maybe. 
give it a try.
datatable js locate in /Themes/Adminlte/assets/js/vendor/datatables/jquery.dataTables.js
