### ISSUE TITLE
Provisionning on envoyer/forge

### ISSUE THREAD

**Issue by vp-gcoutu** [AsgardCms/Platform#111]
I've been running on a problem when I try to create a dev environnement on Digital Ocean server with the Asguard platform on it.

I'm using envoyer to deploy the code over a forge provisionned box.
The box is the smallest but the script is being killed before it ends.

Do you have any clue on how to fix this issue? I'm thinking about swapping the box or upgrade it. Did you have any issues like that when you deployed your Asguard apps?

**Comment by nWidart** [comment]
Hello,

Yes, you need at least 1gb of ram on the droplet. This is because of composer dying before it can install all dependencies.
