### ISSUE TITLE
Pingpong menu getMenuWithDropDownWrapper does not have url availible

### ISSUE THREAD

**Issue by Thorazine** [AsgardCms/Platform#112]
So in the "getMenuWithDropDownWrapper" function I would like to have the url available. But when requesting it with $item->getUrl() it returns the home url ("/"), not the stored url.

**Comment by nWidart** [comment]
This looks like an issue that should be created on the [package repository](https://github.com/pingpong-labs/menus).

**Comment by Thorazine** [comment]
Are you filling $item or are they. I'm guessing you.

**Comment by mvdstam** [comment]
@Thorazine https://github.com/pingpong-labs/menus/blob/master/MenuItem.php#L266-L269

**Comment by nWidart** [comment]
Does every item returns `/` ? What url did you expect to have returned ?

**Comment by Thorazine** [comment]
In the menu builder a url has been set. In every other $item instance this results in that particular url entered in the builder. So it works everywhere, unless you want the getMenuWithDropDownWrapper to give back the set url. It always remains "/" regardless of entering a url in the menu builder.

**Comment by Thorazine** [comment]
```
<li class="dropdown'.$this->getActiveStateOnChild($item, ' active').'">
		          <a href="'.$item->getUrl().'" class="dropdown-toggle" data-toggle="dropdown">
					'.$item->getIcon().' '.$item->title.'
			      	<b class="caret"></b>
			      </a>
			      <ul class="dropdown-menu">
			      	'.$this->getChildMenuItems($item).'
			      </ul>
		      	</li>
```
$item->getUrl() should return the url entered in the menu builder like in every other function in the presenter. But this returns "/"

**Comment by nWidart** [comment]
You say it's only in the `getMenuWithDropDownWrapper` method, this leads me to believe it's something relation to the package. 

Did the link @mvdstam linked helped you to pin point the origin of the issue ?

**Comment by Thorazine** [comment]
His link points out that indeed that function is the one i'm referring to when requesting the url. It returns "/". What I cant seem to find is where the query is done for the menu builder and where $item gets it's values from. Exactly that point is the origin of what I'm looking for.

**Comment by Thorazine** [comment]
Can you confirm the missing url? If so, please open the ticket again.

**Comment by nWidart** [comment]
I'm not following. Everything you explain leads to the package.
