### ISSUE TITLE
Is there any chance to add "sub folder" feature for Media Module?

### ISSUE THREAD

**Issue by oimken** [AsgardCms/Platform#113]
All files store in media module's "files-path" now, 
It is very hard to find a image.
and when I allow upload other file type, 
they mixed with the image in the same "files-path"  folder,

Are you plan to add subfolder support for  Media Module?
Sub folder will be very helpful for classification and management.

**Comment by nWidart** [comment]
That was planned indeed, if you look at the database there's a `directory_id` on the files. Since this wasn't a priority at the time I decided to work on that later.

For now though, you can use the search field to find you files easier

**Comment by oimken** [comment]
That's great to known asgardcms' media will have sub-folders. 
Thank you for sharing such great cms!

**Comment by mikheil09** [comment]
Thanks to everyone who created this CMS. Its great!

But there is some features that needs improvements. In this case I need to organize files into folders but it is not supported yet. 
Also I need to create photo gallery but it is too complicated.

I have recommendation to integrate this CMS  with "[Responsive Filemanager](http://responsivefilemanager.com/demo.php)". I was using it in earlier projects and I can say it's great.

So, files management is problem and it can be solved using this "Responsive Filemanager"

That is just my thaghts

**Comment by nWidart** [comment]
This is *finally* coming in AsgardCMS 3.1. 🎉
