### ISSUE TITLE
How to translate Blog Module's  tag?

### ISSUE THREAD

**Issue by oimken** [AsgardCms/Platform#114]
Add tag to post  works fine.
But when I switched the language ,
Tags becomes "Not translated",
Where and how to translate the tags?

**Comment by nWidart** [comment]
Hello @oimken ,

That's still something that has to be developed.
Basically I would like to have a crud based view, just like the categories, for tags. So that after tags are created via the post view, that can be translated, or vise versa.

**Comment by oimken** [comment]
Thank you very much for your reply.   I love your asgardcms!
