### ISSUE TITLE
AdminLTE Asset Structure Issue

### ISSUE THREAD

**Issue by joshbrw** [AsgardCms/Platform#116]
When you first create an Asgard project the assets for the AdminLTE theme are in a particular structure that the `asgard.core.core` config expects, but once you re-run `gulp` from `Themes/AdminLTE` and run `php artisan stylist:publish` it throws it into a completely different structure, therefore the references are broken.

**Comment by nWidart** [comment]
Hm might be because of commit : https://github.com/AsgardCms/AdminLTE/commit/09aa8048ccc2dfd06b4b8fc8e0c3bae71f11ecd1

**Comment by joshbrw** [comment]
It's to do with the structure that the `gulpfile` in the `AdminLTE` theme generates, compared to what is in `AsgardCMS/Platform` (`asgard.core.core`) by default, in `public/themes/adminlte`

**Comment by nWidart** [comment]
It has worked before for a long time, so it's must be related to a recent
commit.

On Sunday, 27 September 2015, Josh Brown <notifications@github.com> wrote:

> It's to do with the structure that the gulpfile in the AdminLTE theme
> generates, compared to what is in AsgardCMS/Platform (asgard.core.core)
> by default, in public/themes/adminlte
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AsgardCms/Platform/issues/116#issuecomment-143563528>.
>


-- 


Nicolas Widart
www.nicolaswidart.com

**Comment by nWidart** [comment]
Fixed on latest AdminLTE version.

**Comment by joshbrw** [comment]
Woo
