### ISSUE TITLE
Failed opening required autoload.php

### ISSUE THREAD

**Issue by RadoslavAngelov** [AsgardCms/Platform#117]
Hi, I am trying to make new instalation of AsgardCMS, and I follow the steps from the documentation, but when I run "php artisan asgard:install" I get the following error:

Warning: require(C:\xampp\htdocs\amit\asgard\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\amit\asgard\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\amit\asgard\bootstrap/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\amit\asgard\bootstrap\autoload.php on line 17

I can see that the path to the file is not rendered properly but I don`t know why.

**Comment by olipiskandar** [comment]
try composer install on your project folder...
after that, try composer install
and the last, try php artisan asgard:install
CMIIW

**Comment by RadoslavAngelov** [comment]
I`ve already tried with composer install and composer update, but when I try to enter a php artisan command the same error occurs

**Comment by nWidart** [comment]
After running composer install, do you see the file it's talking about ? Ie, is there a vendor folder ?

**Comment by RadoslavAngelov** [comment]
No, I get an error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - asgardcms/media-module 1.0.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.0.1 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.0.2 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.0.3 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.0.4 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.1.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.2.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.3.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.3.1 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.4.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.5.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.6.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.7.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.8.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - asgardcms/media-module 1.9.0 requires intervention/image ~2.1 -> satisfiable by intervention/image[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.x-dev].
    - intervention/image 2.3.x-dev requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.2.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.2.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.2.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.1.4 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.1.3 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.1.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.1.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.1.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - Installation request for asgardcms/media-module ~1.0 -> satisfiable by asgardcms/media-module[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0].

**Comment by nWidart** [comment]
Ah so that's already better info to help you ...

As you can see, you don't have the required extension.

**Comment by RadoslavAngelov** [comment]
Thank you. If anyone else encounter the same problem  just has to edit the php.ini file and uncomment extension=php_fileinfo.dll (for Windows users). Thanks again.

**Comment by nWidart** [comment]
Awesome thanks for letting us know how you fixed it. :+1: Will add an entry for it on the wiki.

**Comment by quangmt** [comment]
@nWidart Please help me

After using create-project command, I don't see the vendor folder in download source.

And I meet problem when running php artisan. Where can  I get the vendor folder?

Note: I see it download AsgardCms 1.14.0

**Comment by franata** [comment]
@quangmt 
run : composer update

**Comment by madhawa-se** [comment]
hm
