### ISSUE TITLE
can't use module cache:  config('modules.cache.enabled') 

### ISSUE THREAD

**Issue by scil** [AsgardCms/Platform#119]
If i enable modules.cache, vendor/pingpong/modules/Module::__instruct say: it need four argument
```
public function __construct(Application $app, $name, $path, Json $json)
```

but vendor/pingpong/modules/Repository::formatCached is 
```
$modules[] = new Module($this->app, $name, $path);
```

I check the lasted pingpong module, Module::__construct need only 3 arguments.

Could update pingpong module ?

**Comment by nWidart** [comment]
You're free to send a PR to the [forked modules package](https://github.com/nWidart/modules). :smile:
