### ISSUE TITLE
Current setup of AdminLTE doesn't work with elixir 3

### ISSUE THREAD

**Issue by simonfunk** [AsgardCms/Platform#121]
the elixir api has changed for version 3, so gulp doesn't work.
for my new admin theme, i changed it to:

    var task = elixir.Task;

    elixir.extend("stylistPublish", function() {
        new task("stylistPublish", function() {
            return gulp.src("").pipe(shell("php ../../artisan stylist:publish "+themeInfo.name));
        }).watch("stylistPublish", "**/*.less");
    });

and as well the paths. elixir expects the js and less files under assets folder, so under resources/assets/

**Comment by nWidart** [comment]
Fixed in [1.6.0](https://github.com/AsgardCms/AdminLTE/releases/tag/1.6.0)
