### ISSUE TITLE
How to re-generate thumbs for image in Media Module？

### ISSUE THREAD

**Issue by oimken** [AsgardCms/Platform#122]
I try to re-genarate thumbs  by edit the photo (old thumbs deleted already), nothing happen, seems Media module did not detect the missing thumbs ...

**Comment by nWidart** [comment]
From the documentation: https://asgardcms.com/en/docs/media-module/refreshing-thumbnails

```
php artisan asgard:media:refresh
```

**Comment by oimken** [comment]
Sorry for Not read the docs carefully....
I just add one line in 
Modules/Media/Http/Controllers/Admin/MediaController.php
```php
    public function update(File $file, UpdateMediaRequest $request)
    {
        app('imagy')->createAll($file->path);
        $this->file->update($file, $request->all());

        flash(trans('media::messages.file updated'));
```

so when I update the media file will recreate  thumb for it.
Console command is good, but not very handy. lol.

**Comment by nWidart** [comment]
Well the console command is only for when you create new thumbnails after some were already generated.
