### ISSUE TITLE
Route Error

### ISSUE THREAD

**Issue by jramirezgranada** [AsgardCms/Platform#124]
I've installed the AsgardCMS without errors, but when i try to go to the backend URL i get an error for Route Error. See attached

 I try /auth/login and /backend
![screen shot 2015-11-11 at 12 37 56 pm](https://cloud.githubusercontent.com/assets/4364876/11098154/13efd820-8871-11e5-91c8-80d54c8989ba.png)

**Comment by nWidart** [comment]
Hello,

Did you run the installation command ? `php artisan asgard:install`

**Comment by jramirezgranada** [comment]
yes i ran and without problems, created tables in db, i didn't get an error. everything was ok, but i get this error with routes.

**Comment by nWidart** [comment]
I wasn't able to reproduce the error on a clean install. Please check you have installed everything correctly.

**Comment by joshbrw** [comment]
Can't recreate on a fresh install, either. Is this installed in a sub folder? That may cause issues.

**Comment by nWidart** [comment]
I close this due to inactivity. Feel free to re-open if you're still having issues.
