### ISSUE TITLE
Bugs in Menu Moudule

### ISSUE THREAD

**Issue by oimken** [AsgardCms/Platform#125]
on edit menu page,there is some bugs. 

##### expand/collapse buttons shows every item , even it has  no children items

fixed:
Modules/Menu/Services/MenuRenderer.php
line:83
```php
    /**
     * @param $item
     * @return bool
     */
    private function hasChildren($item)
    {
        return count($item->items);
    }
```

#####  Module's  front-end uri is fixed. could not change by menu Module.

**Comment by nWidart** [comment]
Hello sorry for the delay,

Issue 1 & 2 are fixed, but I don't understand why you mean by "Module's front-end uri is fixed. could not change by menu Module."

**Comment by nWidart** [comment]
Tagged : https://github.com/AsgardCms/Menu/releases/tag/1.12.0

**Comment by oimken** [comment]
Sorry for my english.   I mean could not change the modules frontend route in menu module.
such as  Blog moudule's url was set in  `Module/Blog/Http/frontendRoutes.php `, 
I just can not find a easy way to set Blog's link in a menu.
I saw  `menu_menuitems.module_name` field in database...
so, maybe it is not a bug, just a feature not finish yet...

**Comment by nWidart** [comment]
Alright, I'll close this issue as that last point is on #127 

Thank for reporting the other bugs :+1:
