### ISSUE TITLE
Route to custom module

### ISSUE THREAD

**Issue by prasadpyda** [AsgardCms/Platform#126]
How to setup frontend view for custom module from menu item. , There is a "frontendRoutes.php" file in pages module. Anybody please explain the process

**Comment by nWidart** [comment]
View works like any laravel application.

To setup the routing, check indeed frontendRoutes.php (can be called anything) and the RouteServiceProvider in each module.

**Comment by prasadpyda** [comment]
Thanks for the quick responce Nicolas.

**Comment by prasadpyda** [comment]
1) changed below code in RouteServiceProvider in Events module.
   protected function getFrontendRoute()
    {
        //return false
		 return __DIR__ . '/../Http/routes.php';
    }
2) added "routes.php" file in "Http" folder, and "eventsample.blade.php" in "Resources/Views" folder.

3) In routes.php file added below code
use Illuminate\Routing\Router;
Route::get('/events', function () {
    return view('evnets.eventsample');
});

But getting the error "View [evnets.eventsample] not found."

**Comment by nWidart** [comment]
So as you see the error is not a not found route, but a view.
You need to prefix the view with the module name: `YourModule::events.eventsample`

**Comment by prasadpyda** [comment]
Sorry, if i am asking manu questions?
getting Error : No hint path defined for [Events].

**Comment by nWidart** [comment]
Look at other modules, and base yourself on that. You must be defining something wrong to have these errors. Example: https://github.com/AsgardCms/Block/blob/develop/Http/Controllers/Admin/BlockController.php#L32

**Comment by prasadpyda** [comment]
Thank you Nicolas.. I got the solution. thanks for the support. :+1:

**Comment by nWidart** [comment]
Awesome :v:
