### ISSUE TITLE
Backend and Frontend Locales

### ISSUE THREAD

**Issue by joshbrw** [AsgardCms/Platform#128]
Separate backend and frontend locales.

There would have to be thought how the "Get Enabled Locales" functionality would work if this were to be implemented, as it would need to be a merge of the backend and frontend locales.

The other solution is that only locales that have been selected as "Backend Locales" can also be enabled as "Frontend Locales"..

**Comment by nikolay-stefanov** [comment]
This is nice, but this also refers to the case wouldn't be better if the front-end is completely separate app. If you split the labels, then same goes to the rest of the common files - even the models used on the front-end parts are much simpler than those used "behind the scene".

Also if something is threaded as back-end or front-end in most of the cases relates to the role of the end user using the system - for example managing of a profile affects the same entity as editing a user from the admin:)

**Comment by nWidart** [comment]
I'll close this for now. 😄
