### ISSUE TITLE
Linking a menu item to a Page doesn't work

### ISSUE THREAD

**Issue by mrdezzods** [AsgardCms/Platform#129]
In menus management, when you select a page and in non translatable fields normally you'd expect it to link to the page's slug. Apparently it doesn't work

**Comment by neposoft** [comment]
any updates on this @nWidart ?

**Comment by nWidart** [comment]
Hello,

Issue is noted, an reported by multiple people on Slack. I haven't had a chance to look into it.

Btw: It never worked the way you expect it to, so it needs to be something new for this use-case. Feel free to send a pull-request with a solution if you want. :smile:

**Comment by nWidart** [comment]
This is being worked on heavily on this PR: https://github.com/AsgardCms/Menu/pull/24

**Comment by nWidart** [comment]
This has been merged in.
