### ISSUE TITLE
Image Slider

### ISSUE THREAD

**Issue by cfreak** [AsgardCms/Platform#134]
Hello i wan't to use asgardCms to build up my new Website, but how is it possible to realize something like this page http://www.templatemonster.com/demo/51853.html.

How can i combine an Slider and different content blocks on one page?

How would be the best way to go?

**Comment by nWidart** [comment]
Hi,

First of all you need to be able to use the Laravel framework. If you have that knowledge using asgardcms to build a site with the template you link will be very easy to do.
