### ISSUE TITLE
Disable 'Register a new membership' in login page

### ISSUE THREAD

**Issue by Vilsafur** [AsgardCms/Platform#136]
Hello,

How can I disable the Registration in the login page ?

**Comment by nWidart** [comment]
Hello Vilsafur (Tu ne viens plus sur le Slack de laravel.fr ? :smile: )!

You can edit the authentication views by publishing those views. You can publish the User module views by running:

```
php artisan vendor:publish --provider="Modules\User\Providers\UserServiceProvider"
```

**Comment by Vilsafur** [comment]
Great, thanks.

(nope, je vois pas le bout sur un projet, j'essaye de me concentrer. Je reviendrais :-p)
