### ISSUE TITLE
Media - no preview image at admin's page load with include partial

### ISSUE THREAD

**Issue by Vilsafur** [AsgardCms/Platform#137]
Hello,

I've include the partial like describe [here](https://asgardcms.com/en/docs/media-module/relations).
This partial work correctly, he create the link in database but when I reload page or when I go to this edit page again, I don't see this media.
When I try to add an other media, a new link was created but I want one-to-one relation

The code of include : 
```
@include('media::admin.fields.file-link', [
                        'entityClass' => 'Modules\\\\Slider\\\\Entities\\\\Slide',
                        'entityId' => $slide->id,
                        'zone' => 'coverimage'
                    ])
```

**Comment by nWidart** [comment]
The docs explain you need to fetch the thumbnail in the controller set on the correct variable name

**Comment by Vilsafur** [comment]
Great thanks,

I thought that this include was in views only, not in admin panel.

thanks again.

**Comment by nWidart** [comment]
No problem :smile:
