### ISSUE TITLE
How can we connect with MongoDB using AsgardCms

### ISSUE THREAD

**Issue by visulvbsr** [AsgardCms/Platform#139]
As we are trying to connect with mongodb we are facing different issues can anyone please advise us the correct path to make the asgardcms up and run using mongodb

**Comment by nWidart** [comment]
Hello,

I haven't tested running the full cms on AsgardCMS. However you can use Mongo for parts of the cms, ie your modules.

**Comment by visulvbsr** [comment]
Thanks for the information mWidart .. can you please advise the steps

**Comment by nWidart** [comment]
I suggest reading the documentation http://laravel.com/docs/5.1/database and this package https://github.com/jenssegers/laravel-mongodb
