### ISSUE TITLE
Problems in backend resource such as css, js files in AsgardCMS Project on Windows

### ISSUE THREAD

**Issue by nicholasli137** [AsgardCms/Platform#140]
When I create new AsgardCMS project using composer. 
when I run php artisan serve it looks working well.
When i login to the backend, it also looks well.
But i found it some resource files are not loaded related **Modules** and **Themes**.
it says like this:
[http://localhost:8002/modules/dashboard/gridstack/gridstack.min.css/en/modules/dashboard/gridstack/gridstack.min.css](http://localhost:8002/modules/dashboard/gridstack/gridstack.min.css/en/modules/dashboard/gridstack/gridstack.min.css)
 Failed to load resource: the server responded with a status of 404 (Not Found)
Notice that **gridstack.min.css/en/modules**.
It seems like resource url is redirected.
How can I resolve this issue?
Please help me.

**Comment by nWidart** [comment]
Hello,

This has been fixed here: https://github.com/AsgardCms/Workshop/releases/tag/1.14.0
Thank you for reporting the issue.
