### ISSUE TITLE
Translation Module - No validation rules

### ISSUE THREAD

**Issue by joshbrw** [AsgardCms/Platform#141]
There is an issue with the Translation module where it seems that because the `TranslationServiceProvider` is being loaded after most of Laravel's Service Providers the custom Translator isn't being used for the Validation error messages (for example, `validation.required`).

My proposed fix to this would be:

* Update Platform, remove the Laravel `ValidationServiceProvider` and add `TranslationServiceProvider` into `config/app.php`'s `providers` section.
* Update `CoreServiceProvider`'s checks, so that it doesn't load the `TranslationServiceProvider` twice.

We need to take into account the fact that the `app.php` will need updating in `Platform`, which means that a lot of people won't get this change...

**Comment by nWidart** [comment]
I'm not able to reproduce this issue. Please double check if you aded something custom to your installation.

**Comment by Fl0ux** [comment]
I can confirm this bug. It seems to be impossible to add translations for validations rules.

I tried to add this package using composer :
https://github.com/caouecs/Laravel-lang
and also to add manually some rules in "resources/lang".

As in the example above, I get messages like "validation.required" instead of the appropriate translation.

**Comment by nWidart** [comment]
You need to set the validation key in your form request, if you're using the translatable form request.

**Comment by nWidart** [comment]
Example for the page module, which works with translatable messages:

<img width="259" alt="screen shot 2016-07-22 at 21 24 19" src="https://cloud.githubusercontent.com/assets/882397/17068717/eb9bfb74-5052-11e6-92b7-5e6708498ecb.png">

https://github.com/AsgardCms/Page/blob/master/Http/Requests/CreatePageRequest.php#L7
