### ISSUE TITLE
Create an SEO module

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#143]
This module would have the polymorphic relation of seo tags such as
- meta title
- meta description
- meta tags
- facebook title
- facebook description
- facebook type
- ...

**Comment by arcanedev-maroc** [comment]
Hi @nWidart,

Try my SEO package : https://github.com/ARCANEDEV/SEO-Helper

**Comment by amenk** [comment]
I think this is in Asgard included?

**Comment by arturmamedov** [comment]
Please someone can explain what happened here? This is a roposal or yet done in AsgardCMS?
