### ISSUE TITLE
Create a tags module

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#144]
This module would contain the polymorphic relation to handle tags.

Tags could be simple and contain:

- name
- slug

**Comment by mikemand** [comment]
So you'd pretty much want to extract out the tags stuff from the Blog module?

**Comment by nWidart** [comment]
On long term correct, though currently that would mean a breaking change.

This is mostly for new modules that need to have tags associated with them.

**Comment by mikemand** [comment]
This might be relevant. Why reinvent the wheel if one of these will work as a starting place?

https://laravel-news.com/2015/10/how-to-add-tagging-to-your-laravel-app/

**Comment by armababy** [comment]
Yeah it was my first thought once i installed blog for test run, why category and tags are not separate modules.

Also probably should do node tree for categories so you can nest them infinitely.

**Comment by armababy** [comment]
What are your take on this? Considering any of outside module or want to build from scratch?

**Comment by nWidart** [comment]
I won't be using a package most likely since there's nothing difficult about it.

**Comment by zakius** [comment]
How is this work going? I'd hopefully want to use it in (near) future and I don't know if I should just create own solution (and release it too) or you are on it and gonna release soon?

**Comment by armababy** [comment]
Was thinking of also grouping tags:
tags (id)
tag_translations (slug, name, description)
groups
group_translations (slug, name, description)
tag_groups (tag_id, group_id)
taggable (polymorphic relation)

User can load up tags for specific group, all of them or single one.
Tag can have many groups.
Tag slug and Tag name is unique also Group slug and Group name is unique.
Also make possible to tag withGroup (all tags applied in specific group or groups)

**Comment by nWidart** [comment]
I like this idea of groups! 👍

**Comment by armababy** [comment]
You mean like adding them in selectize? That would be quite tricky :D

**Comment by nWidart** [comment]
Indeed. Maybe just have a method on the TagRepository to get tags by group (or not) and send that to the view. 

Next, in the view there will be needed to include a partial, which will display the input.

And finally in the same way as the new media partials work, the tag module will listen to the created and updated events to make the links.

**Comment by nWidart** [comment]
Created: https://github.com/AsgardCms/Tag and ready to be tested.

**Comment by armababy** [comment]
Lets do this boys, test sh out of it :D
