### ISSUE TITLE
Rethink how permissions work on routes

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#145]
The current system checks the URI with the `permissions.php` config file to check if the user has access to the given page.

I thinking of going the middleware way, by added a middleware on the routes to check the permissions. This was made possible since the middleware parameters.

Example:

``` php
get('/top-secret-page', [
   'middleware'=> 'can:viewTopSecretPage',
   'uses' => 'TopSecretController@index',
]);
```

The `config/permissions.php` would thus only be used to create the permissions checkboxes in users & roles.

This would mean removing the [`PermissionMiddleware`](https://github.com/AsgardCms/Core/blob/master/Http/Middleware/PermissionMiddleware.php) to have a simpler one.

This means introducing a breaking change to all applications, meaning this would be for version 2.

*** 

Modules using new system:

- [x] Core
- [x] User
- [x] Page
- [x] Dashboard
- [x] Media
- [x] Workshop
- [x] Blog
- [x] Block
- [x] Notification
- [x] Setting
- [x] Translation
- [x] Menu

**Comment by joshbrw** [comment]
Not sure how much of a fan I am of declaring permissions in two places. I
think if we're going to go using the middleware method it should be able to
pick up all of the middleware 'permissions' on the user/role create/edit
pages. Also, how would resource controllers/routing work?

**Comment by nWidart** [comment]
It has to be in 2 places. Laravel works like that too with their "policies".

Route resource would work the same way.

**Comment by nWidart** [comment]
This is now possible with this new middleware added since commit: https://github.com/AsgardCms/Core/commit/cecd5420b31eaa2330a060f047c1972e9ce41145

Example route:

``` php
get('blocks', ['as' => 'admin.block.block.index', 'uses' => 'BlockController@index', 'middleware' => 'can:block.blocks.index']);
```

The idea would be to already convert all existing module setups with this new notation, as well as suggesting people to use this setup in the future, so the switch can be easier.

**Comment by JulienTant** [comment]
> It has to be in 2 places. Laravel works like that too with their "policies".
> Route resource would work the same way.

Well, you can build your policies from a database.
When every package registers it's "permissions" into a table like :

| id | module           | permission   |
|---|---------------------|-------------------|
| 1 | asgardcms/page | pages.index |
| 2 | asgardcms/page |pages.create |
| 3 | asgardcms/page |pages.update |

Then you have "permissions_users"

| user_id | permission_id   |
|---|---------------------|-------------------|

And "permissions_groups"

| group_id | permission_id   |
|---|---------------------|-------------------|


And in the implementation (pseudo code) :

```php
foreach(Permission::all() as $permission) {
    $gate->define($permission->module . ':' . $permission->permission, function ($user, $post) use ($permission) {
       return $permission->users()->where('id', $user->id)->exists() || $permission->groups()->whereIn('id', $user->groups->pluck('id))->exists()
    });
}
```

This is just an idea...
