### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by gabyrusu** [AsgardCms/Platform#147]
Hey guys. I have a problem after "php artisan asgard:install". I keep getting this error: "Please ensure your database credentials are valid." no metter what the credentials are. I tried with the correct ones and the default ones... is the same story. Any ideas?

**Comment by nWidart** [comment]
Something must be wrong with your database credentials.

What development environment are you on ?

**Comment by gabyrusu** [comment]
thansk for your quick response, Nicolas. i'm on local development environment . and the database credentials are ok

**Comment by gabyrusu** [comment]
Nicolas, don't bother no more... I'm stupid :) I forgot to enter <none> for the password

**Comment by nWidart** [comment]
Hehe, no worries. :smile: 

Enjoy the cms. :)

**Comment by jonathanpalma25** [comment]
I have a problem with install, please help me

![problem](https://cloud.githubusercontent.com/assets/16760950/13439148/40d2dcf2-dfba-11e5-90b5-7eecfce4f82d.png)

**Comment by nWidart** [comment]
Same as before, you entered wrong credentials.

**Comment by jonathanpalma25** [comment]
I am using Xampp , and that the correct credentials son ! .

I have seen that at the end of each line , except for the first line I get **homestad** . That could cause this inconvenience

**Comment by nWidart** [comment]
If it's the correct credentials you wouldn't get this error :smile: 
This means laravel can't connect to your database.

**Comment by brandenwagner** [comment]
You are leaving a password of  '' (blank). you have to actually type '<none>'

**Comment by JanMesaric** [comment]
So, I found a solution to problem, I was using homestead and it uses port 33060. So when creating the app via terminal use localhost:33060 and it will go through. And now you have DB_HOST=localhost:33060 in your .env file, but guess what, it does not work. Change that to DB_HOST=localhost and you're good.

**Comment by Mtechnik** [comment]
This is what exactly it should look like, should you have any problems:
```
APP_ENV=local
APP_DEBUG=true
APP_CACHE=false
APP_KEY=DVbMogaTXLQhbT1lINBzgQeAIew1kXdF

DB_HOST=localhost
DB_DATABASE=website
DB_USERNAME=root
DB_PASSWORD=

CACHE_DRIVER=array
SESSION_DRIVER=file
```
So when it asks you for the password, if your using the root as user, then the password you need to be sure to actually type out is exactly just like this: <none>, with the < and >. This took me a 1 ful day to realize. However, this should not be.

**Comment by mentordeveloper** [comment]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'roles_slug_unique' (SQL: insert into `roles` (`name`, `slug`, `updated_at`, `created_at`) values (Admin, admin, 2017-03-21 14:24:22, 2017-03-21 14:24:22))

**Comment by mayz77** [comment]
I got the same problem installing on localhost with XAMPP for mac. Since the php on macOS is the difference one from XAMPP. I do type "/Applications/XAMPP/bin/php artisan asgard:install" and that solves the problem. Not sure if this can help.

**Comment by JitendraPrajapati67** [comment]
I also got the same issue. each and every time same information repeat.

**Comment by nWidart** [comment]
That just means laravel can't connect to your database.

**Comment by vhgcuong** [comment]
Hi there!!!. I have issue when using docker in cms:
``` ./dcp a asgard:install -f```
![Screenshot 2019-05-23 16:23:48](https://user-images.githubusercontent.com/44945530/58241489-498bf500-7d77-11e9-97ee-55cd9a868011.png)

**Comment by Sofs-Ronys** [comment]
I have a problem with installing lavaline, please help me.

![image](https://user-images.githubusercontent.com/64073993/123467206-612dab80-d5d7-11eb-98ef-d35c18a0fe4b.png)
