### ISSUE TITLE
xdebug.nesting_level

### ISSUE THREAD

**Issue by Annie-Mi** [AsgardCms/Platform#148]
Hello,

I get only a white screen, I can't see the login, but the route is correct. If I type "/backend" I'll forwarded to /auth/login. The main Site (/public) is empty as well. If I go to the main site I'll forwarded to public/en, also the routing is correct. Only I can't see any content. Did get somebody this error before?

Thanks!

**Comment by nWidart** [comment]
Hi,

White screens usually means an error with the server configuration / 500 error. Please check your logs to understand what's crashing.

**Comment by Annie-Mi** [comment]
Hi,

thanks for the quick answer.
I getting this error: "Maximum function nesting level of '100' reached, aborting!"
I know, that I should change the xdebug.nesting_level to a higher level, but I can't find where. I using a mac and I can't find any xdebug.ini or same. I changed it in my php.ini (restart apache etc) file, but I still getting the same error.
Where should I make the changes?

Thank you

**Comment by nWidart** [comment]
You can see that on the wiki: https://github.com/AsgardCms/Platform/wiki/Maximum-function-nesting-level-of-'100'-reached,-aborting!

Depending on your setup, mamp / homestead /vagrant etc, that will be located at different places.
