### ISSUE TITLE
Scaffolding the CRUD templates based on the DB structure (schema to scaffold)

### ISSUE THREAD

**Issue by nikolay-stefanov** [AsgardCms/Platform#149]
It'll be nice if new Scaffolding command is made - it could cover “reverse engineering” the DB structure defined, afterward it’ll be used to create automatically base forms for the entity data management.

Such "generators" are present in rails for example:
https://github.com/sferik/rails_admin/wiki
http://www.slideshare.net/benoitbenezech/rails-admin-overbest-practices 

All could be based on a convention, not configuration. For example an **enum** field type is for when you need to display a list of potential values. It will be rendered with a select box in forms. A **boolean** will be rendered as a checkbox etc.

Also in this way all the UI could be build using the Form macros, so there will be a good separation of the "surrounding" theme UI from the logic.

**Comment by nWidart** [comment]
I don't see a big usefulness in this personally, since to do that you would have to make the migration etc. anyway.

This can be a separate module that does this though.

**Comment by nikolay-stefanov** [comment]
Yes, being a module instead of a command is a good idea - so the configuration of the DB field to UI rendered could be changed.

The advantage of this could be much faster creation of the basic CRUD operations for an entity inside a module. If a project has several simple entities that has to be managed, this will shorten the development time, keeping the code writing in only few lines :)

**Comment by nWidart** [comment]
After having thought about this a little more, I do agree with your point of view.

It might actually be added in the Workshop module, along side the current module scaffold and theme scaffold commands. It depends on the scope of the feature basically.

**Comment by Houbsi** [comment]
I would say this could be a package on it's own. I was one time working on something like this. And any php application could benefit from this kind of feature.

**Comment by nikolay-stefanov** [comment]
Thanks Houbsi, I think that it's better to be part of the Workshop and respectively from the Asgard core, since it involves thinks like the Form::macro, where all UI fields rendered could be proxy-ed giving us independence if someday a one decides to change the skin for example

**Comment by Houbsi** [comment]
the core could be a php-neutral package, and you import it afterwords with asgard specific stuff.

thtat would be my way of modular thinking.

**Comment by nWidart** [comment]
Extracting to a package sounds good, but I think it's more a time investment issue. Extracting to a package by making it configurable enough would take much more time than having it in AsgardCms, tailored specifically for AsgardCms.

I think we can start by adding it in AsgardCms, and when time allows it, we can extract further to a package. This way, at least we have a first view of a working system, and we'll probably have new and better ideas on how to improve the setup.

**Comment by Houbsi** [comment]
+1 @nWidart good thinking!

**Comment by SimoTod** [comment]
Could this issue be solved contextually to #155? 
If Asgard asks for fields during the scaffolding, it could generate form as well as migration. 
@nWidart If that sounds good to you, I'd like to work on this functionality.

**Comment by nikolay-stefanov** [comment]
Hi SimoTod:)
No, it's better to not assign this to #155 , since this one is going to be much more complex than just creating simple forms (meantime it's going to be ready for publishing very soon ;-)). Inside it will be covered also forms that builds:
- recognizing the translation table (if such) for an entity and building fields inside the translation tabs
- recognizing the attributes assigned with a hasOne relation (that logically is the same object, but hold rarely used data)
- auto recognizing and building as UI components controls that serves the belongsTo and belongsToMany (a pivot table)
- ...and few other nice features:)

**Comment by SimoTod** [comment]
Some of them are not too complicate.
- Cycle asking not translable field until null.
- Cycle asking translable field until null. (this 2 covers point 1)

**Comment by nWidart** [comment]
No more updates, so im assuming this wasn't pursued.
