### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by ahkmunna** [AsgardCms/Platform#150]
I ran this command "composer create-project asgardcms/platform newProject" and getting this error with lots of broken files.
PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' in /Users/****/config/app.php on line 101

**Comment by nWidart** [comment]
That's a notice so shouldn't stop the script execution.
Also that's something to do with your development setup. Check your setup with laravel.

**Comment by ahkmunna** [comment]
I just noticed the the route file in the repository is also empty. I thought its only happen on my machine.

**Comment by arcanedev-maroc** [comment]
The mcrypt extension is missing in your PHP configuration.
