### ISSUE TITLE
Custom error routes

### ISSUE THREAD

**Issue by loganbest** [AsgardCms/Platform#153]
Is there a way to set custom routes to my theme pages for something like 404 or 500 HTTP status codes? I'd like to utilize good looking pages instead of the revealing default laravel exception pages.

**Comment by nWidart** [comment]
Hello,

You can use those as in any laravel app.
Either you add your custom views in `resources/views/errors/`, or you listen for the Exceptions in the `App\Exceptions\Handler` and do something custom with them.
