### ISSUE TITLE
Remove composer.lock from gitignore in install command

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#154]
Currently platform has the `composer.lock` file in the gitignore file. This is because I actually use this repo locally to test every module together. I could probably use a second application for this.

So either I use a second app for the global module testing, or I add a step in the install command to remove that line from the gitignore file. First latter being more work required.

**Comment by Houbsi** [comment]
I wouldn't add a step in the install command.

Isn't this composer.lock file only in your personal case?
