### ISSUE TITLE
Module Scaffold: ask & generate the entity fields in migration

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#155]
It would be a nice additional to have the module scaffold also ask the which fields should be added to the entity plus its type.

This could then populate the migration files accordingly.

Example:
```
Enter which entities you want, leave blank to continue to next step...
-> Category(name:varchar,slug:varchar)
```

It does become more complicated if a property should be added on the translation table or the base table.

```
Enter which entities you want, leave blank to continue to next step...
-> Recipe(preparation_time:int|normal,title:varchar|i18n)
```

What this wont do however, is prepare the views with those fields. Reason being this can become pretty custom based on the need. A simple input field is ok, but added dropdowns/autocomplete/multiselect(or not) etc is all depending on the project and need of the client.

***
*Please note the actual syntax is just a brainstorm and not set in stone.*

**Comment by JulienTant** [comment]
Hi Nicolas,

Most of the folks are used to the [Laracasts Generator](https://github.com/laracasts/Laravel-5-Generators-Extended) syntax, maybe you can borrow some source code, or use this package to generate the migrations ?

**Comment by nWidart** [comment]
Good idea.

I was also thinking a while back of being able to generate a module from a configuration file (probably yaml).
