### ISSUE TITLE
[Suggestion] Organizing the asgard config files

### ISSUE THREAD

**Issue by arcanedev-maroc** [AsgardCms/Platform#156]
I think the config files should be organized and kept simple for search/edit and other stuf.

Why not something like this:

```
config
  |-- asgard
  |     |-- core
  |     |     |-> available-locales.php
  |     |     |-> config.php
  |     |     |-> core.php
  |     |     |-> settings.php
  |     |-- dashboard
  |     |     |-> dashboard.php
  |     |-- ...
  |-> app.php
  |-> auth.php
  |-> ...
```

**Comment by nWidart** [comment]
I agree. Sadly since laravel 5, all configuration files are in on folder only.

Back in laravel 4, packages had their own subfolder in the config folder. 

`config/packages/vendor/name/configfile.php`

**Comment by arcanedev-maroc** [comment]
Test it and see it by yourself.

**Comment by nWidart** [comment]
I did, a very long time ago.

**Comment by arcanedev-maroc** [comment]
It works for me.

**Comment by arcanedev-maroc** [comment]
Try to create a dummy config like this `config/asgard/test.php`:

```php
// config/asgard/test.php

return [
    'hello' => 'world',
];
```

And do a dump and die in a test route or something :

```php
dd(config('asgard.test.hello'))
```

**Comment by nWidart** [comment]
I did see you comment, but I haven't had the chance to test it yet.

**Comment by arcanedev-maroc** [comment]
OK, you can reopened if you want.

And i don't know if you are interested by this suggestion or not ? 

Because it may break you current version or something.
