### ISSUE TITLE
can't see website pages locally

### ISSUE THREAD

**Issue by gpsmadness** [AsgardCms/Platform#157]
After I installed asgard in the www folder of Wamp I was unable to view pages in the public folder.
for example when I go to asgard/public I get this error:
"The requested URL /asgard/public/en was not found on this server".

But when i go to "localhost/asgard/public/index.php" it works(but this only works for this page not the backend).

This problem is not just restricted to the home page but also the backend.

Wamp version: 2.5
Apache version: 2.4.9
PHP version: 5.5.12
MySQL version: 5.6.17

**Comment by nWidart** [comment]
It looks like you vhost is not setup correctly. 
However I can't help you with setting that up on windows. Maybe look it up on stackoverflow/google.

**Comment by gpsmadness** [comment]
Found the solution.
1 of the Apache modules that where needed by asgard was turned of in Wamp. Turned it on and problem was solved.

thanks for pointing me in the right direction!

**Comment by nWidart** [comment]
Awesome, thanks for letting us know, this might help someone else in the future.

Would you mind saying which module it was, so that a future person can fix it faster ?

Thank you!

**Comment by gpsmadness** [comment]
It was the "rewrite_module" module from apache
You can activate it in wamp by clicking the wampserver icon in your system tray and navigating to apache/apache modules.
