### ISSUE TITLE
Application Key not correctly set

### ISSUE THREAD

**Issue by Houbsi** [AsgardCms/Platform#158]
Hi,

i just used: 

``composer create-project asgardcms/platform``

and the terminal said:

``> php artisan key:generate
Application key [iI2LkRfAvtDChwA6cMpKzIHkvzAPr8wS] set successfully.``

But the .env was not created and the key was not set...

**Comment by Houbsi** [comment]
I have to do:

''php artisan asgard:install''

Afterwords... so there is somehting wrong with the composer create script

**Comment by nWidart** [comment]
That's normal though, the key is set on `asgard:install`

**Comment by Houbsi** [comment]
it's confusing... ;)

**Comment by joshbrw** [comment]
This is a non-issue really as you have to run the Asgard installer to get
up and running.

Might be worth removing this from the composer.json's
`post-create-project-cms` to avoid confusion?

**Comment by nWidart** [comment]
Guess I could remove it here: https://github.com/AsgardCms/Platform/blob/develop/composer.json#L70

**Comment by joshbrw** [comment]
Any chance you could PR that change @Houbsi? :smile:

**Comment by Houbsi** [comment]
i'll do it

**Comment by Houbsi** [comment]
https://github.com/AsgardCms/Platform/pull/159
