### ISSUE TITLE
Settings are fixed as "Google Analytics Code"

### ISSUE THREAD

**Issue by Houbsi** [AsgardCms/Platform#160]
Not everyone uses Google Analytics.

So we should rename it and also make the table field "Provider Agnostic".

Regarding the table field name changes... it's a breaking changes and should be done only on the 2.X Release

**Comment by nWidart** [comment]
The `2.0` branch has been created, you can send a PR to this branch if you want. https://github.com/AsgardCms/Setting/tree/2.0

**Comment by Houbsi** [comment]
I'm tackling it atm

**Comment by nWidart** [comment]
:+1: I've been swarmed with work lately, haven't had a lot of time on issues/prs.

**Comment by Houbsi** [comment]
No worries, are working on some projects myself.. but want to get 2.0 moved forward, so i'll help already with the small fries :)

**Comment by Houbsi** [comment]
core::google-analytics i don't find the seeder in the Setting-Module and not in the core module... xD where  is it hidden?

**Comment by nWidart** [comment]
@Houbsi it's here https://github.com/AsgardCms/Core/blob/master/Config/settings.php#L19

I'm in the process of doing this now. How would you call this provider agnostic field ?

**Comment by mikemand** [comment]
Maybe just `analytics`?

**Comment by nWidart** [comment]
I guess that makes sense indeed. Maybe `analytics-code`/`analytics-script` in order to understand we're talking about the code/script to add.

**Comment by mikemand** [comment]
In that case, I would do `analytics-script` because most analytics providers give you some kind of JavaScript to put on your site.

**Comment by nWidart** [comment]
This is done on the 2.0 branches.
