### ISSUE TITLE
Laravel 5.2 compatibility

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#161]
Still not 100% sure I want this, but if it does happen, it will on version `2.0`.

**Comment by nWidart** [comment]
Decided Asgard will not run with laravel 5.2.

**Comment by vicrau** [comment]
why not?

**Comment by nWidart** [comment]
This could still change, but this was the reasoning:

I compared it to server (ubuntu) releases. You never go with a distribution that's not LTS, you upgrade from lts to another lts. This is because you know the lts will be good and stay supported for a long period of time.

**Comment by armababy** [comment]
In ideal world we could have 1 LTS and one non-LTS, but currently there's only one nWidart :)

**Comment by spartangian** [comment]
Im with you mr. nwidart.. i think it is better to wait for another LTS release of laravel. Especially that php7 already released as stable, i am thinking that there's more to add on upcoming laravel version.
