### ISSUE TITLE
Read exception errors views in active theme

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#162]
Currently the `404`, `500`, `503` error views are read from the default location, `resources/views/errors`. 

It would be nice to set that to the `Themes/activetheme/views/errors`.
This can be done by overwriting the `renderHttpException` method in `App\Exceptions\Handler`

Of course this can already be done manually, but having it by default might be a good idea.

**Comment by mikemand** [comment]
>Currently the `404`, `500`, `503` error views are read from the default location, `resources/views/errors`.

This is not correct for 404 errors, in my experience. I have a view at `Themes/Mytheme/views/errors/404.blade.php` and it works just fine.

I do not know, however, if it is a requirement to force an abort with a 404 code by catching the `Illuminate\Database\Eloquent\ModelNotFoundException` exception in `App\Exceptions\Handler`'s `render` method. I have just always done so.

```php
if ($e instanceof ModelNotFoundException)
{
    abort(404, trans('module::module.messages.not found'));
}
```

**Comment by nWidart** [comment]
Interesting for the 404.
I know @joshbrw has also overwritten the  `renderHttpException method to point to the theme.

**Comment by joshbrw** [comment]
Turns out I didn't. This might be caused by stylist's incorrect theme order
loading. That package is just bad :-(

**Comment by nWidart** [comment]
It's not bad, common! :P

It might indeed be because laravel first checks in the theme folder, followed by checks the resources/views folder if not found.
If that's the case, we don't need to do anything. :smile:

**Comment by joshbrw** [comment]
Yeah it's probably that, although last time I checked in sure it was
loading stuff the wrong way round, especially for theme inheritance

**Comment by nWidart** [comment]
Tested an it indeed works.
