### ISSUE TITLE
About  stylist:publish  not compile .less files

### ISSUE THREAD

**Issue by oimken** [AsgardCms/Platform#163]
I am trying to make my own theme for asgardcms lately,
there is a problem when I try to compile my .less file by elixir, here is the steps:

* New theme was copy from Themes/Flatly and change every name string in `theme.json`,`composer.json`,`elixir.json`,`bower.json` from "Flatly" to "Newtheme"
* Run `bower install` and `php artisan stylist:publish Newtheme`, and set the front-end theme to "Newtheme" in `http://asgardlocalsite/en/backend/workshop/themes`, everything works.
* I add one line `"custom"` in `resources/less\main.less` , of cause it is my own less file and I already put it in `Themes/Newtheme/resources/less/custom.less`, same folder with `main.less` and it is quiet simple content and I am sure there is nothing wrong in it .
* Run `php artisan stylist:publish Newtheme` again to compile new .less file, but nothing happen.
* Delete `Themes/Newtheme/assets/css/main.css`, Run `php artisan stylist:publish Newtheme` ，there is no `main.css` created. revert `Themes/Newtheme/resources/less/main.less` to original one, and `stylist:publish` again. nothing create in `Themes/Newtheme/assets/css`...
* Delete `public/themes/newtheme/css/main.css` and `stylist:publish` agian... there is no more `main.css`

##### It seems that  `php artisan stylist:publish` only do the copy job.  
Is it a bug?
looking forward for some helping..

thanks  very much.

**Comment by nWidart** [comment]
yes, the stylist:publish only copies files from your theme assets directory to the public folder.

**Comment by oimken** [comment]
The theme's gulpfile.js is not ready for use, It need some modifications:

```
/asgardcms/Themes/Flatly/gulpfile.js:11
    this.registerWatcher("stylistPublish", "**/*.less");
         ^

TypeError: this.registerWatcher is not a function
```

#####  Replace 
```php
elixir.extend("stylistPublish", function() {
    gulp.task("stylistPublish", function() {
        gulp.src("").pipe(shell("php ../../artisan stylist:publish "+themeInfo.name));
    });
    this.registerWatcher("stylistPublish", "**/*.less");
    return this.queueTask("stylistPublish");
});
```
##### To：
```php
elixir.extend("stylistPublish", function() {
    gulp.task("stylistPublish", function() {
        return gulp.src("").pipe(shell("php ../../artisan stylist:publish "+themeInfo.name));
    }).watch("**/*.less");
});
```
##### After that,  gulp works fine.

Btw:
`artisan stylist:publish` is a little annoy in dev.
just add a copy task in gulpfile.js to watch. I save sometime.
```php
    /**
     * Copy assets to public
     */
    mix.copy(
        'assets',
        '../../public/themes/winse'
    )
```
