### ISSUE TITLE
Remove the "magical" config registering for every module

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#165]
In `2.0` I'm thinking to remove the automatic configuration registering for every module.

Currently: every module config is registered automatically.
In 2.0: Every module will need to register its config on its own. Example:

``` php
$this->mergeConfigFrom(__DIR__ . '/../Config/config.php', 'asgard.page.config');
$this->publishes([__DIR__ . '/../Config/config.php' => config_path('asgard.page.config' . '.php'), ], 'config');
```

Positive:

- This is already the case with publishing of views.
- Allows for publishing *individual* module configuration files.
Example:

```
php artisan vendor:publish --provider="Modules\Page\Providers\PageServiceProvider" --force --tag="config"
```

Negative:

- Requires *a bit* more configuration on the users end.

*** 

Modules already on the new system:

- [x] Core
- [x] User
- [x] Page
- [x] Dashboard
- [x] Media
- [x] Workshop
- [x] Blog
- [x] Block
- [x] Notification
- [x] Setting
- [x] Translation
- [x] Menu

**Comment by lead-worker** [comment]
It is good idea. 
And as addition, I think it will be a good practice use different folders for configs of different modules. And, maybe, all them will need place in specific folder for all asgard config. So, in the end we will have structure like this:

- asgard/
	- core/
		- available-locales.php
		- config.php
		- core.php
		- ...
	- dashboard/
		- dashboard.php
		- ...
	- ...
- app.php

**Comment by nWidart** [comment]
Thank you @lead-worker . This is indeed on the way for version 2.0.

I've created a [helper trait](https://github.com/AsgardCms/Core/blob/2.0/Traits/CanPublishConfiguration.php) to more easily publish the configuration files.

Now with the following API:

``` php
$this->publishConfig('dashboard', 'permissions');
```

Which will publish the `permissions.php` file in the `Dashboard` module to `config/asgardcms/permissions.php`

**Comment by nWidart** [comment]
All 2.0 branches of modules have this setup.

<img width="293" alt="screen shot 2016-06-16 at 21 36 59" src="https://cloud.githubusercontent.com/assets/882397/16130641/83fcaaa4-340a-11e6-9849-72af90278306.png">

**Comment by nWidart** [comment]
The subfolder doesn't work natively after all. Laravel publishes it, but it can't read from it.

**Comment by armababy** [comment]
Hmm, is the implementation not picking up configs subfoldered or anything else?
For me on current 5.1 asgard installation i can reach any folder.

![71ca6ad1601460a4b7b35f71e7cf043b](https://cloud.githubusercontent.com/assets/219556/16162087/d0d249c2-34d9-11e6-90ce-1930f260bb03.png)

**Comment by nWidart** [comment]
Yea my bad, the 2 keys needed to match https://github.com/AsgardCms/Core/commit/b6e6fbc4e6bdd20fdcaf737d5b4ea823c69e15ec

**Comment by armababy** [comment]
Ah cool :)
