### ISSUE TITLE
Can not run php artisan command

### ISSUE THREAD

**Issue by quangmt** [AsgardCms/Platform#166]
Please help me

After using create-project command, I don't see the vendor folder in download source.

And I meet problem when running php artisan. Where can I get the vendor folder?

Note: I see it download AsgardCms 1.14.0

**Comment by SimoTod** [comment]
@quangmt: Did you run *php artisan asgard:install*?
Note, you have to move inside the project folder before calling the command.
The vendor folder will be created after you run the command.
