### ISSUE TITLE
Entity name problems

### ISSUE THREAD

**Issue by tanmuhittin** [AsgardCms/Platform#167]
When you create 2 entites with the same name in different modules, one of the model doesnt work for edit page.
For example I have categories entity for 2 different modules in their edit page both of them points to the same model

**Comment by nWidart** [comment]
That should not happen. Please double check your namespace. The namespace is what makes those 2 models unique.

**Comment by tanmuhittin** [comment]
I am pretty sure that they are different. I am sending the relevant modules
[Formlar.zip](https://github.com/AsgardCms/Platform/files/113590/Formlar.zip)
[News.zip](https://github.com/AsgardCms/Platform/files/113591/News.zip)
. In my News module edit route looks for Forum module’s model. Forum model was created afterwards and I had a similar issue before and I changed the name of the entity and I was ok. But the same thing happened again.

**Comment by nWidart** [comment]
The namespace must be wrong, that's the only way you can have a wrong class. I have a project with 2 "Category" models, and thanks to php namespaces it works fine.

**Comment by tanmuhittin** [comment]
I found the problem. In the backendRoutes.php file there are bindings to enetity names. when I set up a new module which has the same entity name, the new modules binding for ,lets say categories, works and the results for the new entity is fetched.
maybe one can find a better solution but for now I changed the binding in my newer module's backendRoutes.php file as
`
$router->bind('categories', function ($id) use ($router) {
        if(strpos($router->current()->uri(),'news')!==false){
            return app('Modules\News\Entities\Categories')->find($id);
        }
        return app('Modules\Forum\Repositories\CategoryRepository')->find($id);
    });
`

**Comment by nWidart** [comment]
Ah yes indeed. The bind parameter name needs to be different. You can prefix with module name for example.

**Comment by tanmuhittin** [comment]
if we make those bindings above route group then the bindings are created with the group name so they will be specific to the module and entity itself.
I think The current situation is not proper.
A solution must be found

**Comment by nWidart** [comment]
In group or outside the group won't change anything.

Like I said, use a namespaced parameter name and your issue will be fixed.

**Comment by mikemand** [comment]
Just to add on to what Nick said: Laravel doesn't put the route-model bindings into groups like you can with your routes themselves. Bindings are in the global "namespace" for routes, so any route can access one, regardless of its groupings.

Whether this is a flaw or bug is up for debate. I personally believe that if you define a binding within a route group, it should only be accessible to routes within that group (and any subgroups). Likewise, any binding that is defined outside of a group is available to all routes. This was [suggested two years ago](https://github.com/laravel/framework/issues/4840), but rejected pretty quickly.
