### ISSUE TITLE
media-grid index action without thumb choice (dropdown-menu)

### ISSUE THREAD

**Issue by ruscon** [AsgardCms/Platform#168]
Can we do it optional?

**Comment by oimken** [comment]
yes. that's kind of annoying to click the drawdown a click agin for every image. just add a button for original size.
https://github.com/oimken/Media/commit/c44b457f80caf376a5c44c1c47c0032c98acc08c

**Comment by mikemand** [comment]
@nWidart: I think what needs to happen is separate out the CKEditor media grid from the other media grid (or, add some way to check which of the media grids are in use so you can either show all the thumbnail sizes - for WYSIWYG integration - or just a single "Select" button - for attaching a media item to an object).

**Comment by ruscon** [comment]
@nWidart some comments for this ?

**Comment by nWidart** [comment]
Hello,

Sorry for the delay. 

@mikemand That's already the case.

Pull requests welcome to remove the dropdown.

**Comment by ruscon** [comment]
@mikemand can you ?

**Comment by ruscon** [comment]
@nWidart, @oimken implementation ok for you ?

**Comment by nWidart** [comment]
For the wysiwyg it makes sense to not show the dropdown. However for the object relations, there it is used.

**Comment by nWidart** [comment]
This was tagged a while ago. The partials via non-wysiwyg don't have the dropdown, and the popup via the wysiwyg has the dropdown.
