### ISSUE TITLE
Setup with laravel homestead

### ISSUE THREAD

**Issue by matchboxhero** [AsgardCms/Platform#171]
Hi,

I've been trying to get this setup with laravel homestead; I've got all the files pulled down, when I try to run; `php artisan asgard:install` it won't accept the database details and always returns the error `Please ensure your database credentials are valid.`. I'm using the same details I would use to setup a wordpress or custom laravel site but it will not accept them.

Has anyone managed to get this up and running on laravel homestead?

Cheers,
Ste.

**Comment by nWidart** [comment]
Hi,

I only use homestead, and it works. Please double check the credentials.

**Comment by matchboxhero** [comment]
I'm using the same as I always do, it works fine for other systems, I've tried a number of variations with no luck;

![screen shot 2016-02-10 at 16 01 26](https://cloud.githubusercontent.com/assets/5112099/12952771/98707588-d00f-11e5-869f-7ec54ad323fb.png)

**Comment by nWidart** [comment]
That means laravel can't connect to the database.

Are you ssh'ed in the vagrant box ?

**Comment by matchboxhero** [comment]
Thanks for the reply, I was not and that was the problem. 

Thanks @nWidart :+1:

**Comment by nWidart** [comment]
Cool :)

**Comment by ClausMunch** [comment]
This is also an issue if you run it in Laragon..
