### ISSUE TITLE
route group not working

### ISSUE THREAD

**Issue by konstantinkonstantinovbgo** [AsgardCms/Platform#172]
Hi,

I made a module name: 'jobpositions'
Here we go my routes:
/*
backendRoutes.php
*/
$router->group(['prefix' => '/jobpositions'], function (Router $router) {

    $router->bind('jobpositions', function ($id) {
        return app('Modules\JobPositions\Repositories\JobPositionsRepository')->find($id);
    });

    get('/', ['as' => 'admin.jobpositions.jobpositions.index', 'uses' => 'JobPositionsController@index']);
    get('/create', ['as' => 'admin.jobpositions.jobpositions.create', 'uses' => 'JobPositionsController@create']);
    get('/{jobpositions}', ['as' => 'admin.jobpositions.jobpositions.edit', 'uses' => 'JobPositionsController@edit']);
});

After then I visit http://localhost/en/backend/jobpositions

**ERROR:**
_**Permission denied. (required permission: "jobpositions.dashboard.index") **_

What's happend !!!

**Comment by armababy** [comment]
You need to add permissions after your create module.
In backend Users > Roles
