### ISSUE TITLE
[AdminLTE 1.15.1] Widgets

### ISSUE THREAD

**Issue by armababy** [AsgardCms/Platform#173]
Hey,

I started to make bunch of widgets for modules.
There are some concerns with this.
- **Allow user to permanently or temporally remove widget** (some users might not want see widget that does not relate to them, currently you can only re-arrange them) 

Maybe some kind of visibility switch so they can re-enable them without fully resetting whole grid?

Also on a off-topic to this specifically:
Probably all modules that supply widget (for example Blog module) should implement `hasAccess` check in Widget class, so we can control permissions.

**Comment by nWidart** [comment]
Hello,

These are good idea, I'll keep them in mind. :smile:

**Comment by mikemand** [comment]
Also need to look into how they are placed in the grid...If you have two modules that supply the same X and Y coordinates for a widget, they overlap and are sometimes not able to be moved. I _thought_ AdminLTE handled this automatically (there was some Javscript to handle the order of the widgets, but I cannot recall where I saw it).
