### ISSUE TITLE
Bug in Page Module's is_home

### ISSUE THREAD

**Issue by oimken** [AsgardCms/Platform#174]
There is no way to uncheck default home page's  `is_home` checkbox and update,
so, can not set another page to home page.

I think when user checked the `is_home` checkbox and save changes,  just update any other page which has `is_home = 1`  to `0` before update database .  no rule needed.

**Comment by nWidart** [comment]
Hello,

Sorry for the very late reply.
This has now been fixed on [1.14.0](https://github.com/AsgardCms/Page/releases/tag/1.14.0)

As you suggested the validation rule was removed, and instead the other homepage will be set to 0.
