### ISSUE TITLE
[Media 1.20.1] Anything other than image extension returns empty path

### ISSUE THREAD

**Issue by armababy** [AsgardCms/Platform#175]
Hey,

Based on this http://forum.asgardcms.com/topic/21/media-module-allowed-types-inserting-new-types i wanted to see wheres problem with any other type other than declared in File entity.

I have came to conclusion that if you supply anything other than [$imageExtensions](https://github.com/AsgardCms/Media/blob/master/Entities/File.php#L19)
This [MediaController.php](https://github.com/AsgardCms/Media/blob/master/Http/Controllers/Api/MediaController.php#L82) will set ``$thumbnailPath`` to ``null`` because path property of ``Modules\Media\ValueObjects\MediaPath`` is private.

In the File entity ``getPathAttribute`` accessor declares path as MediaPath valueobject.

This specific [getThumbnail](https://github.com/AsgardCms/Media/blob/master/Image/Imagy.php#L83-L85) part tries to return that protected property

Could anyone confirm that null is returned for any media that is not decaled in $imageExtensions (linked above).

Probably could fix this with ``return $originalImage->getUrl();``
Also view part should be tweaked to display fa-file icon without image instead of image.

**Comment by nWidart** [comment]
Did you try master branch ?

**Comment by armababy** [comment]
Yes indeed just tested still happens in dev-master.

How to test:

install asgard,
install blog module,
add something like .pdf in allowed-types,
add new blog post,
try to upload and link any pdf.

Link is okay but it returns ``{"error":false,"message":"The link has been added.","result":{"path":{},"imageableId":"1"}}`` and it lead to NotFoundHttpException for that path obviously.

``return $originalImage->getUrl();`` fixes part where path is returned correctly, but i'm not sure about it as i didn't study to much all of Media module and intent of everything.

**Comment by nWidart** [comment]
I'm not sure I'm following. I haven't had any issues with other file types than images.

It's normal that you can a broken thumbnail, you can refresh the page to get another thumbnail.

**Comment by armababy** [comment]
Yes media file is correctly linked and after refresh you will get file icon. It was just asked on forum why my media is broken (since without refresh people would think it does not work).

**Comment by nWidart** [comment]
Because the current expect to fill an `img` html attribute. 

I think it's normal that people think it doesn't work since their file isn't an image, thus it makes sense no image gets displayed.

**Comment by armababy** [comment]
Sure i think so too, but it would be nice if it would display something other than broken image for new user sake.

And also if you want to do more work with linked media currently you can't because there are no path, you would need to refresh page or query path using imageableId.

I do not consider this a big issue just a small user experience improvement.

**Comment by armababy** [comment]
So with 2.0 media updates this would require two different approaches:

* For old ones we just need to change [this](https://github.com/AsgardCms/Media/blob/2.0/Image/Imagy.php#L86) into ``return $originalImage;->getUrl();``
* For new ones there's no more ajax call to link media and no data returned, so if we want distinguish between __image__, __video__, __audio__, __file__ we need to supply that information to [here](https://github.com/AsgardCms/Media/blob/2.0/Resources/views/admin/grid/partials/content.blade.php#L88) with something like ``data-media-type``.

Not sure where to determine media type in ``FileRepository`` or just as Media module [helper ](https://github.com/AsgardCms/Media/blob/2.0/Helpers/FileHelper.php)

**Comment by nWidart** [comment]
**For the old ones:**

is returning the url enough ? How does the partial then knows to display an `img` attribute or not ?

**For the new ones:**

I think adding it to the data attribute sounds like a good solution. That's something that could go on the helper class indeed.

**Comment by armababy** [comment]
Yeah in both cases theres view part also, was only hitting php changes.
Anyways i came up with solutions, i'll push soon new feature branch for 2.0.
As i understand 1.x is frozen? Will not push this particular change there?
