### ISSUE TITLE
[Media] If zone is named 'thumbnail', then the preview image is broken

### ISSUE THREAD

**Issue by mikemand** [AsgardCms/Platform#176]
Cause: https://github.com/AsgardCms/Media/commit/e699e68ebe2808b0cd4baa06a55cb1b85fe99762

Consider changing the variable name to something like `thumbSize` or `previewSize`. Something that would be very unlikely for a dev to use as their zone name.

**Comment by zedee** [comment]
Is there any workaround to this bug at this moment?

**Comment by nWidart** [comment]
Sending a pull request with a rename on that variable 😄

**Comment by zedee** [comment]
I think I'm not confident nor experienced enough with GitHub to do so... Time to take a look to the documentation! :)

**Comment by armababy** [comment]
@zedee Yes if you only need to edit 1 file without creating branches and so on you can do it here in github via webui.

**Comment by mikemand** [comment]
Fixed in https://github.com/AsgardCms/Media/issues/35.
