### ISSUE TITLE
Enhancement: Dynamic Widgets

### ISSUE THREAD

**Issue by nbdamian** [AsgardCms/Platform#179]
I was doing some research into how to do Dynamic Widgets with AsgardCMS, although never came across a solution. What I want is that for each user it generates a widget on the dashboard, with each widget containing some statistics, without having to manually create each one and then updating them each when a change is made.

**Comment by nWidart** [comment]
I would suggest customising the Dashboard module to achieve the wanted behaviour. Remove it from composer and commit the module into your project.
