### ISSUE TITLE
Notifications System

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#18]
Still looking for the best solution

- Ajax call every x seconds to get the notifications,
- Use sockets for real time notifications ( http://socketo.me/ )

An additional email notification could be sent if the user is offline. This would require an user account setting to disable email notifications.

Also use http://lab.ejci.net/favico.js/ to add notification count in favicon.

**Comment by tk-s** [comment]
Any news on this part?

**Comment by nWidart** [comment]
This is still planned. When I have time, I'll work on it. :smile:

**Comment by nWidart** [comment]
Progress: http://quick.as/7rasgvgv :smile:

**Comment by nWidart** [comment]
Done here: https://github.com/AsgardCms/Notification
