### ISSUE TITLE
Translations GUI still linked when config set to false.

### ISSUE THREAD

**Issue by theTrip73** [AsgardCms/Platform#180]
I'm not sure what the intent is, but when I turn off the translations GUI through the config/app.php setting, the admin link for Translations remains in the left sidebar. Clicking it results in the following error: "Call to undefined method Illuminate\Translation\FileLoader::paths()".

Two suggestions for fixing this come to mind:

(1) Hide the link.
(2) Instead of loading the normal index page for Translations, show a new view with instructions on how to turn on the Translations GUI.

**Comment by nWidart** [comment]
Hello,

Thanks for reporting this. I'm very busy currently, will look at it when possible.

Pull requests always welcome.

**Comment by nWidart** [comment]
Hello this has been fixed on `1.11.1` release of the Translation module.

**Comment by marfrelen** [comment]
Sorry for reopen this ticket,

but the Error appears again.
