### ISSUE TITLE
[Core] Guzzle requirement

### ISSUE THREAD

**Issue by armababy** [AsgardCms/Platform#181]
Hey,

I'm starting to make SocialAuth and it requires guzzle v6+.

So i looked up what goes where and Core module requires v5 of Guzzle.
And currently all requirements are met for v6.
Laravel 5.1 can use version 6 for mailer API's.

We can see that in all Asgard [Imagy](https://github.com/AsgardCms/Media/blob/master/Image/Imagy.php) is using it once.

Something like:
Replace guzzlehttp/guzzle v5 with v6 requirement from Core module.
Renew code ``Mimetypes::getInstance()->fromFilename($filename)`` to ``GuzzleHttp\Psr7\mimetype_from_filename($filename)`` in [Imagy#148](https://github.com/AsgardCms/Media/blob/master/Image/Imagy.php#L148)

Any thoughts? I see there's pull request, it would require another pull request to take care of mime thing.

**Comment by nWidart** [comment]
Hello,

Guzzle causing issues again. I'm not sure we can require guzzle 6 without breaking other things, or more likely other projects that depend on guzzle 5.

**Comment by armababy** [comment]
You are right main concern would be BC for users that use actual guzzle 5 in their projects.
As far as any internal problems i just found one that i pointed out before in Imagy file.

```
composer depends guzzlehttp/guzzle
asgardcms/core-module  1.23.1  requires  guzzlehttp/guzzle (~5.0) 
```
No other part of original installation does not depend on it.
intervention/image has it own dependency on guzzlepsr7, thats fine it uses newest.

But ultimately i get it upping to v6 would require major release as it will bc for some projects.

I'll then have to manually do it for now by using v6 on my own untill time comes :)

**Comment by nWidart** [comment]
Might be something worth doing in 2.0 though. It also depends if laravel requires guzzle, but I doubt it does.

**Comment by armababy** [comment]
Nah laravel has only optional requirement for guzzle ("guzzlehttp/guzzle": "~5.3|~6.0") in case you want mailgun, mandrill trough api.

**Comment by nWidart** [comment]
I see so that's good, so on 2.0 we can require version 6.

**Comment by armababy** [comment]
#232

**Comment by nWidart** [comment]
No need to have 2 same issues open. Linking them is enough.
