### ISSUE TITLE
[Composer installer] Asgard one

### ISSUE THREAD

**Issue by armababy** [AsgardCms/Platform#183]
Not sure if i should post here or to composer installers github.
I'm assuming you are in charge so i should discuss here i guess.

It's still same problem for trying to make modules and all that jazz.

Installer profile for Asgard does not allow me to use hypens in composer package name, for example lets see ``vendor/amazing-package``.

What's currently happening it installs my package as ``Modules/Amazing-package``, which breaks all code highlighting and namespaces and so on. And probably breaks ping-pong modules.

To fix this we should mimic studly_case functionality.

This [AsgardInstaller#L32-L37](https://github.com/composer/installers/blob/master/src/Composer/Installers/AsgardInstaller.php#L32-L37)

To something like:
```php
    protected function inflectPluginVars($vars)
    {
        if(strpos($vars['name'], '-module') !== false)
            $vars['name'] = preg_replace('/-module/', '', $vars['name']);

        $vars['name'] = str_replace(['-', '_'], ' ', $vars['name']);
        $vars['name'] = str_replace(' ', '', ucwords($vars['name']));

        return $vars;
    }
```
or even simpler (since preg_replace pattern does not require any specific place for '-module')
```php
    protected function inflectPluginVars($vars)
    {
        $vars['name'] = str_replace(['-module', '-', '_' ], ' ', $vars['name']);
        $vars['name'] = str_replace(' ', '', ucwords($vars['name']));

        return $vars;
    }
```

Which would allow to have package names like ``dashboard-module``, ``amazing-package``, ``and_another-one`` and so on.

Any toughs on this? After this change we would wait for pingpong to fix their game for a full cycle, but for now it helps a lot to use custom modules with several words in package name using conventional naming pattern vendor-name/word-word-word.

**Comment by nWidart** [comment]
Sorry for late reply. This looks interesting. Would this work with without modifying pingpong/modules ?

**Comment by armababy** [comment]
Yeah it works with current Asgard modules and is not BC:
``dahsboard-module`` folder becomes ``Dashboard`` (as before)
``dashboard-module-extension`` folder becomes ``DashboardExtension`` (allow this now)
``fancy_new-dashboard-module`` installs in ``FancyNewDashboard`` (and this)

As far as i have tested pingpong has no problems with camel cased folder names.

This would just help installing custom modules without need to manually rename folder after using installer.

**Comment by armababy** [comment]
Reference: composer/installers#317
