### ISSUE TITLE
Check MySQL user privileges before proceeding with the installation

### ISSUE THREAD

**Issue by kehugter** [AsgardCms/Platform#184]
I created the Asgard MySQL user with the SELECT,INSERT,UPDATE,DELETE,CREATE,DROP privileges, which resulted in the following error when running `php artisan asgard:install`

```
Database successfully configured
                                     
  User Module                        
  Starting the User Module setup...  
                                     
SQLSTATE[42000]: Syntax error or access violation: 1142 ALTER command denied to user 'asgard'@'localhost' for table 'persistences' (SQL: alter table `persistences` add unique `persistences_code_unique`(`code`))
```

I granted all privileges and ran `php artisan asgard:install` again, but the setup wouldn't resume/restart:

    Asgard has already been installed. You can already log into your administration.

The privileges, if possible, should be checked before continuing. Adding the minimum required privileges for installing (and running, if different) Asgard in the documentation would be helpful, too.

**Comment by joshbrw** [comment]
I'm not a fan of this idea. Asgard is a platform for developers, and they
should understand that all MySQL privileges should be granted.

**Comment by nWidart** [comment]
You can re-run the installation with the `--force` flag on the install command.

**Comment by kehugter** [comment]
> all MySQL privileges should be granted

In most cases, all privileges are not necessary. I don't consider it a "is for developers" issue - for instance, valid DB credentials are a condition to resume the installation. It doesn't just throw an error, break the installation attempt and require a `--force`.

> re-run the installation

Yes, thanks, I did. I wanted to highlight the fact that it assumed that the installation was successful.

**Comment by nWidart** [comment]
I think that if you want to setup custom privileges you are free to do so, as long as laravel has what it needs to access and write data.
