### ISSUE TITLE
Add mcrypt to the list of minimum requirements

### ISSUE THREAD

**Issue by kehugter** [AsgardCms/Platform#185]
I was getting the following message

    PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' in /var/www/asgard/config/app.php on line 101

several times during the installation, and the default home page displayed a couple of error messages about

    No supported encrypter found. The cipher and / or key length are invalid.

Installing and enabling the mcrypt mod solved the issue.

**Comment by nWidart** [comment]
We could do that yes, I didn't add it since it's a laravel requirement.

The documentation can be found here if you want to PR the change: https://github.com/AsgardCms/Documentation :+1:

**Comment by kehugter** [comment]
> laravel requirement

I didn't see it in the docs
https://laravel.com/docs/5.2#installation

Will PR in a second.
