### ISSUE TITLE
Non-breaking way of setting blog as home page

### ISSUE THREAD

**Issue by zakius** [AsgardCms/Platform#187]
It would be nice to have ability to set blog index as homepage without editing module files

**Comment by armababy** [comment]
@nWidart what if we move homepage setting into settings tab instead and add dynamic dropdown to set page or blog category/post as homepage?
That would also get rid of #174 

Something like wordpress type of dropdown.

**Comment by nWidart** [comment]
hm interesting suggestion. I'm unfamiliar how wordpress does it, it has been too long. 

Moving that setting on the settings view would be a little bit counter intuitive in my opinion, as when you save a page, and want it to be the homepage, you'd need to go to another view select it + save.
Instead of just on save view as 'create page', checking 'homepage'.

**Comment by joshbrw** [comment]
Only issue with having the `Homepage` checkbox on the Page Create/Edit page is that someone could select multiple pages as the homepage. The two solutions to this are:

* Move it to Settings, a single dropdown.
* Upon saving the Page as a Homepage, unmark every other Page as Homepage.

**Comment by armababy** [comment]
It's very nice and convenient for page-only as homepage solution.

What i'm thinking of is place where you could set any of visible pages, blog categories or any other view as homepage.
And possibly also for custom modules to create their own homepages, without page and templates.

**Comment by nWidart** [comment]
As the recent release of page module, if one page is already set to homepage, and we set another page to homepage, it will de-active the old homepage.

**Comment by nWidart** [comment]
I like the idea however of being able to set a homepage from whatever module, from a centralised location.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
