### ISSUE TITLE
Invalid version string "4.x.x"

### ISSUE THREAD

**Issue by nikunjkansara** [AsgardCms/Platform#191]
### Summary of issue
When I start to install the AsgardCms platform with Laravel 5.2, I found error lik 

### Steps to reproduce
[RuntimeException]                                                           
  Could not load package intervention/image in http://packagist.org: [Unexpec  
  tedValueException] Could not parse version constraint 4.x.x: Invalid versio  
  n string "4.x.x"  

---------------------------------
[UnexpectedValueException]                                                
  Could not parse version constraint 4.x.x: Invalid version string "4.x.x"

### System Details

- Operating System
- PHP Version 5.6
- Laravel Version 5.2
- `Asgardcms/Platform` version latest

**Comment by nWidart** [comment]
One google search further: https://github.com/Intervention/image/issues/464
