### ISSUE TITLE
Settings view variables

### ISSUE THREAD

**Issue by nbdamian** [AsgardCms/Platform#192]
I have 
````
return [
	'signature_template' => [
        'description' => trans('signature::signatures.settings.signature_template'),
        'translatable' => false,
        'view' => 'signature::settings.select-template',
    ]
];
````

In my module's settings.php.
Is it possible to run a request of `$this->template->all()` and pass the result to the view to display in a select in the settings module.

If so, how would I go about this?

**Comment by joshbrw** [comment]
If you're wanting to interact with view files outside of the view rendering logic, I'd recommend you use a View Composer and attach it to the view. Note that View Composers also have access to the View object itself, so it's possible to take data from the view, and also to set it onto the view for rendering.

https://laravel.com/docs/5.1/views#view-composers

**Comment by nbdamian** [comment]
@joshbrw Awesome thanks.
Although it should be noted that the providers are saved in module.json.
The namespace for the ServiceProvider has to be `Modules\Signature\Providers`.
The namespace for the Composer has to be `Modules\Signature\ViewComposers`.
