### ISSUE TITLE
loop entry when run php artisan asgard:install on cmd

### ISSUE THREAD

**Issue by yudirahmanjr** [AsgardCms/Platform#194]
Always loop entry when i run php artisan asgard:install on cmd win 7
enter database host ->
localhost
enter  database name ->
asgard
enter username ->
root
enter password ->

after all above, its loop again
enter database name-> 
................ same as above

how to solve it ?

**Comment by nWidart** [comment]
Hello, you can solve it by entering correct data.
This happens wgen laravel can't connect to mysql.

On Wednesday, 11 May 2016, yudirahmanjr <notifications@github.com> wrote:

> Always loop entry when i run php artisan asgard:install on cmd win 7
> enter database host ->
> localhost
> enter database name ->
> asgard
> enter username ->
> root
> enter password ->
>
> after all above, its loop again
> enter database name->
> ................ same as above
>
> how to solve it ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AsgardCms/Platform/issues/194>
>


-- 
--
Nicolas Widart

Sent from my iPhone

**Comment by yudirahmanjr** [comment]
thanks @nWidart , the problems is my database password is incorrect. 
My first asgard web is run ! 

thanks

**Comment by yudirahmanjr** [comment]
hello @nWidart i try to install notification_modul and i got an error like this 
ErrorException in Connection.php line 655:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'asgard.notification__notifications' doesn't exist (SQL: select * from `notification__notifications` where `user_id` = 1 and `is_read` = 0 order by `created_at` desc limit 10) (View: D:\wamp64\www\asgard\Themes\Adminlte\views\layouts\master.blade.php) (View: D:\wamp64\www\asgard\Themes\Adminlte\views\layouts\master.blade.php)

should i create notification table on my database first ? 
how to solve it
thanks ..

**Comment by yudirahmanjr** [comment]
solved :)

**Comment by nWidart** [comment]
Awesome 👍
