### ISSUE TITLE
Overhaul the media module relations to work on create and edit

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#195]
Currently the issue is the partial for adding media on an Entity, can only be used on update views.

Below are notes in order to make the media module work for both create and edit views.

![](https://cldup.com/jwY8snE658.png)

**Comment by nWidart** [comment]
The create view can now have media. The current workflow to achieve this:

- Insert the `media::admin.fields.new-file-link-multiple` partial like so:

``` php
@include('media::admin.fields.new-file-link-multiple', [
    'entityClass' => 'Modules\\\\Product\\\\Entities\\\\Product',
    'zone' => 'gallery'
])
```

- Trigger an event when you model was created
    - Your event needs to implement `Modules\Media\Contracts\StoringMedia`
    - Your event needs to have 1) the Entity and 2) the data from the form
    - The interface requires 2 methods, to return each of those properties
- In `asgard.media.events.php` (re-publish media module to have it, or create it manually) add your event in the array.

That's it.

**Comment by nWidart** [comment]
This now also works for the single image on create view:

```
@include('media::admin.fields.new-file-link-single', [
    'zone' => 'coverimage'
])
```
In the same way, we now also need to trigger an event on the create method, that implements the `StoringMedia` interface.

**Comment by nWidart** [comment]
Issues encountered:

- No current way of having 2 single media partials on create views.
    Issue is with the `zone` name. If 2 single media partials have been included, one for `zone1`, and one for `zone2`, they will all have `zone2`, which is loaded last and overwrites the first.

    I don't know how this could be fixed. 
    
    I wanted to have a form structure of `medias_single[zone_name]` which will contain the `file_id`, however since those functions overwrite each other, I wasn't able to make this work.



-

**Comment by nWidart** [comment]
1. I was able to make it work in the following way: https://github.com/AsgardCms/Media/commit/09b8329513bb3a4329088b7bbe5aab9e39af4586

**Comment by nWidart** [comment]
There is now also a new feature that allows the polymorphic link to be removed upon deleting of a model.

It also requires the creation of an event. Something like `ProductWasDeleted` event, that implements the `Modules\Media\Contracts\DeletingMedia` interface.
That event needs to have the id of the entity and its class name.

Finally add this event to the `asgard.media.events.deleting` config key.

**Comment by nWidart** [comment]
This has been tagged on [1.22.0](https://github.com/AsgardCms/Media/releases/tag/1.22.0) of the media module.

- [Check the upgrade guide for the media module](https://asgardcms.com/docs/upgrade-guides/media#upgrade-1.22.0)
- [New documentation](https://asgardcms.com/docs/media-module/relations)

**Comment by armababy** [comment]
Nice, thanks :)

**Comment by divyasreem** [comment]
I am usingthis in create view in a different module able to get the browse button in create view but how to get and store the value in db unable to understand



create view file : 

<div class='form-group{{ $errors->has('name') ? ' has-error' : '' }}'>
    {!! Form::label('name', trans('paymentmethod::paymentmethods.form.name')) !!}
    {!! Form::text('name', Input::old('name'), ['class' => 'form-control', 'placeholder' => trans('paymentmethod::paymentmethods.form.name')]) !!}
    {!! $errors->first('Name', '<span class="help-block">:message</span>') !!}
</div>
@include('media::admin.fields.new-file-link-single', [
    'zone' => 'logo'
])


controller create file : 

public function create()
    {
        return view('paymentmethod::admin.paymentmethods.create');
    }

store file: 
public function store(Request $request, FileRepository $fileRepository)
    {
        $this->paymentmethod->create($request->all());

        flash()->success(trans('core::core.messages.resource created', ['name' => trans('paymentmethod::paymentmethods.title.paymentmethods')]));

        return redirect()->route('admin.paymentmethod.paymentmethod.index');
    }

please help me how to proceed further

**Comment by nWidart** [comment]
You should read the documentation. It is explained step by step. https://asgardcms.com/docs/v1/media-module/relations#one-to-one-relation

**Comment by divyasreem** [comment]
Unable to understand that document , can you please explain  more details

**Comment by nWidart** [comment]
Read this issue then. Again explained step by step.
