### ISSUE TITLE
How to install asgard cms in bitbucket repository

### ISSUE THREAD

**Issue by aqilkam** [AsgardCms/Platform#196]
### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by armababy** [comment]
What do you mean by installing in bitbucket repository?

**Comment by aqilkam** [comment]
i am unable find steps to install asgard cms in bitbucket respository or in any hosting server. i am new to laravel so if there are any steps to install the cms. will be helpful.

**Comment by armababy** [comment]
You need command line access to install, as long as you have that and you meet all Laravel requirements you can install it anywhere you like.

If you have no SSH access, but only FTP you could try to install it trought Codeanywhere container then transfer files to your server.

Asgard have no flat zip file that you could use to install, so this not exactly an issue should be a question @ http://forum.asgardcms.com or a feature request.

**Comment by aqilkam** [comment]
thanks for your reply.

i have command line can you guide me to install on server what should i write in command line.

for local machine it's working fine when i am typing "composer create-project asgardcms/platform asg" 

for installing in server what changes i should do in the command line.

**Comment by armababy** [comment]
It's same for local or remote server, nothing changes.
You need composer, database, comply with Laravel requirements and thats it.
I see no issue here.

**Comment by nWidart** [comment]
Hello,

This "issue" has nothing to do with asgardcms or even laravel for that matter.
Please refer to your source control documentation (git,...)
