### ISSUE TITLE
FatalThrowableError in TemplateViewComposer.php line 62

### ISSUE THREAD

**Issue by rockymontana** [AsgardCms/Platform#197]
### Summary of issue
![image](https://cloud.githubusercontent.com/assets/330839/15350931/aff86066-1cdc-11e6-83cd-f3a7308d0506.png)

### Steps to reproduce
go to domain.tld/lang/backend/page/pages/create
I went via the menus which then are `Main Menu -> Pages -> Create a Page` to get that.
### System Details

OS X - El Capitan
7.0.6
Laravel Framework version 5.1.35 (LTS)
```
  "require": {
    "laravel/framework": "~5.1",
    "pingpong/modules": "dev-feature/5.1",
    "cartalyst/sentinel": "~2.0",
    "asgardcms/core-module": "~1.0",
    "asgardcms/dashboard-module": "~1.0",
    "asgardcms/user-module": "~1.0",
    "asgardcms/setting-module": "~1.0",
    "asgardcms/media-module": "~1.0",
    "asgardcms/page-module": "~1.0",
    "asgardcms/menu-module": "~1.0",
    "asgardcms/workshop-module": "~1.0",
    "asgardcms/translation-module": "~1.0",
    "asgardcms/flatly-theme": "~1.0",
    "asgardcms/adminlte-theme": "~1.0",
    "asgardcms/notification-module": "^1.3"
  },```

**Comment by nWidart** [comment]
If you went to that class, you see that it didn't find your template.

ie: ` return $this->themeManager->find(setting('core::template'))->getPath();`.

You need to use a template that exists.

**Comment by rockymontana** [comment]
It was set when I looked in the settings menu, but since it was the only option it was the only possible value for the HTML to chose from. When I re-saved the setting it worked!
