### ISSUE TITLE
Application Error when trying to integrate the theme.

### ISSUE THREAD

**Issue by aqilkam** [AsgardCms/Platform#199]
I'm using AsgardCMS for first time. While accessing the site in my local server, I got the error message "NotFoundHttpException in Application.php line 879:". when i was integrating the theme. i have removed all the changes but still the errors comes Help me to resolve this problem?

Thanks in advance.

**Comment by nWidart** [comment]
Try with a clean install 😄

**Comment by aqilkam** [comment]
it installed clean.
the admin is getting logged in only frontend is giving this error can u guide me on this please.

Thanks

**Comment by nWidart** [comment]
You said you had to revert back some changes, so possibly you forgot something somewhere.
As this error cannot be reproduced on a clean install.

404, would also trigger if you didn't run the install command.

**Comment by aqilkam** [comment]
404 might be the cause.
if 404 triggers it then how to solve it.

**Comment by nWidart** [comment]
As I just said, follow the install instructions.

Let's continue the conversation on [slack](http://slack.asgardcms.com/) as this isn't a bug on the cms.
