### ISSUE TITLE
After composer create-project, the asgard:install tell me - yet installed

### ISSUE THREAD

**Issue by arturmamedov** [AsgardCms/Platform#204]
### Summary of issue
Run `php artisan asgard:install` get me `Asgard has already been installed. You can already log into your administration.`

### Steps to reproduce
```
$> composer create-project asgardcms/platform your-project-name
$> php artisan asgard:install
```
### System Details
Windows 10
PHP 5.6.14
comoser 1.0-dev (44bc8e019f8b4ac711b647b0693f84061ac7bb38) 2015-12-07 16:56:35
(that in Asgard Platform v5.1.40)
(last v1.14.1)

**Comment by arturmamedov** [comment]
Ok its because i create the .env file before run it ... i always set up my db connection trough it!

**Comment by arturmamedov** [comment]
@nWidart and what we need to do on servers where we don't wont to use the `.env`?
```php
$this->app->singleton('asgard.isInstalled', function ($app) {
	$envFileLocation = "{$app->environmentPath()}/{$app->environmentFile()}";

	try {
		$hasTable = Schema::hasTable('setting__settings');
	} catch (\Exception $e) {
		$hasTable = false;
	}

	return $app['files']->isFile($envFileLocation) && $hasTable;
});
```

**Comment by nWidart** [comment]
Every server needs a .env file. Laravel can't work without it.

**Comment by arturmamedov** [comment]
I not agree with this, i have many laravel installation that work without it. And i ever think that it for semplify work in local and testing enviorements.

Example:
- in local machine i have .env with db conf of local things and debug setted to true ...
- in remote i not load .env and laravel automatically use the /config/(.*).php files configuration that are configured for production

i think not only i'm use this scenario

**Comment by mikemand** [comment]
The only thing that Asgard checks is if the file exists (not the contents). You could create an empty `.env` file and it will then rely on there being a `setting__settings` table in the database.

**Comment by nWidart** [comment]
I don't see why you wouldn't use a .env file. That means you commit your database / services credentials, which isn't a good idea anyway.

**Comment by arturmamedov** [comment]
Yes you right, maybe i need to re-look and re-factor my method of configuring production server. No commit the config and use only the .env, its go be more clean and secure afterwards.
Thanks for the answers and suggestions, happy coding!

**Comment by nWidart** [comment]
I see, thanks for the explanation, helps to get an idea of the use case. 

However AsgardCMS doesn't support not using the `.env` file. 

I never use and ftp also, and I also deploy using git, yet I have a .env file on my servers. You can do this by creating that .env file _once_ and forget about it later. It can be created using vim/nano for instance.
