### ISSUE TITLE
Problem with asgardcms in MediaRelation

### ISSUE THREAD

**Issue by wassimhattab** [AsgardCms/Platform#205]
### Summary of issue
Hello I'm facing a problem with asgardcms in MediaRelation when adding 'use MediaRelation'
Error saying Trait 'Modules\Recipes\Entities\MediaRelation' not found

![1](https://cloud.githubusercontent.com/assets/20112008/16307721/0140cf3a-396b-11e6-8d2d-743e8d3f315f.png)

![2](https://cloud.githubusercontent.com/assets/20112008/16307729/083cc050-396b-11e6-856f-f4b77e496de7.png)

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by zeraist** [comment]
You need to add 

use Modules\Media\Support\Traits\MediaRelation;

**Comment by wassimhattab** [comment]
When i add use Modules\Media\Support\Traits\MediaRelation;
it give me the following error
Trait 'Modules\Recipes\Entities\Modules\Media\Support\Traits\MediaRelation' not found;

**Comment by zeraist** [comment]
Try putting a slash before

use \Modules\Media\Support\Traits\MediaRelation;

**Comment by nWidart** [comment]
Did you also place that after the `namespace` declaration ?

**Comment by wassimhattab** [comment]
It works when adding a slash before thank you @zeraist 
and yes @nWidart after the name space
