### ISSUE TITLE
Add method to add an internal-api routes file

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#206]
Adding method on the Core `RoutingServiceProvider` to have an internal api routes file.

This will allow separation of public and private apis.

**Comment by nWidart** [comment]
I'm not convinced anymore this needs to be done, as it would only require to have 2 different route groups in the `apiRoutes` file.

**Comment by armababy** [comment]
Hmm, 2 files vs 2 groups.
For general purposes i guess 1 file would be nice.
On the other hand what if you have massive API's that one file would be large, but again no much of a problem if you use folding in IDE.

What are drawbacks of having 2 files? Extra serviceprovider, changes in Core, more documentation i guess.

**Comment by joshbrw** [comment]
My issue with having two files is that not everyone is going to need that second file, whereas most people use frontend/backend/api routes. "Technically" speaking, they're still API Routes so make more sense to exist in the API routes file.

**Comment by nWidart** [comment]
The negative point of the 2 files is that it's one more breaking change, which isn't that bad. 
It would also require editing all existing modules to add that additional method.
And also move all current api routes to the new internalApi file, since all current api endpoints are for the backend itself.

All this work, to basically have a little better organisation, organisation that would already be possible if one would require the 2 files manually in the `apiRoutes` file.

``` php
// in apiRoutes.php
require __DIR__ . 'internalApi.php`
require __DIR__ . 'publicApi.php`
```

Which isn't as nice, but would still be functional for the few that have too many routes.


@joshbrw just like the current route files, they are optional. Meaning if you only need a private api, you only require that file, and set the other method to false. This is already the default behaviour for frontend and api routes when scaffolding a module.
