### ISSUE TITLE
ckeditor image not selecting

### ISSUE THREAD

**Issue by deepakSP** [AsgardCms/Platform#211]
### Summary of issue

when inserting image through ckeditor nothing get selected url box is also empty thr is no error in console box

### Steps to reproduce
it was a fresh install so don't know how to reproduce .. screenshots

<img src='https://s32.postimg.org/iqmdc4cad/one.png'/>

but image never get inserted its always blank
<img src='https://s32.postimg.org/9wvgv0pbp/two.png'/>

### System Details

- w10
- PHP Version - 7
- `Asgardcms/Platform 1.14.1

**Comment by nWidart** [comment]
You ignored the issue template, closing.

**Comment by deepakSP** [comment]
Template issue ??

**Comment by nWidart** [comment]
What you see when you create a new issue.

**Comment by deepakSP** [comment]
updated

**Comment by nWidart** [comment]
I wasn't able to reproduce this. Maybe check you're on the latest version, permissions set correctly etc.

**Comment by nWidart** [comment]
Found the issue, it was fixed in pr41, but I forgot to tag that.

This was now tagged. https://github.com/AsgardCms/Media/releases/tag/1.25.2
