### ISSUE TITLE
[Media 1.25.1] JS problems when using multiple and single in same form.

### ISSUE THREAD

**Issue by armababy** [AsgardCms/Platform#213]
### Summary of issue

When including both single and multiple media in same view, clicking on ``jsRemoveLink`` in multiple form removes all media files and hidden order input field.

### Steps to reproduce

1) include both media views:
```
@include('media::admin.fields.new-file-link-single', ['zone' => 'site_image'])
@include('media::admin.fields.new-file-link-multiple', ['zone' => 'site_gallery'])
```
2) add two or more media files on multiple uploader
3) click X(remove) on any of multiple media

### Expected result

Only one media file being removed and hidden order input field remains.

### System Details

- Operating System: Ubuntu 14.04.04
- PHP Version: 5.6.23
- Laravel Version: 5.1.40
- `Asgardcms/Platform` version: 1.14.1

**Comment by motchju** [comment]
Hello,

Please check this new version https://github.com/motchju/Media

Only 3 files has been updated

https://github.com/AsgardCms/Media/compare/master...motchju:master

Let me know the result, if it's ok, I will propose a PR

**Comment by mikemand** [comment]
A few comments inline @motchju. Other than that, it looks good. Are the other file links affected too, or just the new file links?

**Comment by armababy** [comment]
@mikemand I only tested this on new file links.

**Comment by nWidart** [comment]
I think this is only on the new partials. As @motchju already fixed the same issue on the ones for edit views.

**Comment by armababy** [comment]
@motchju your commits are working as expected thanks.

**Comment by nWidart** [comment]
Awesome, hopefully @motchju can PR tomorrow :)

**Comment by motchju** [comment]
Hi,

PR done, thank @mikemand for the comments.

**Comment by nWidart** [comment]
Tagged on version [1.25.3](https://github.com/AsgardCms/Media/releases/tag/1.25.3).

Thanks @motchju !
