### ISSUE TITLE
Creating a module without a sub menu in backend

### ISSUE THREAD

**Issue by wassimhattab** [AsgardCms/Platform#216]
### Summary of issue
Can i create a module ( menu in backend ) without a entity ( submenu in backend )

![asgard](https://cloud.githubusercontent.com/assets/20112008/16729878/ff548bf6-4777-11e6-9f32-7534e1da0926.png)

In my case if i want the link on the Module name 'Pricing' without having a entity 'Pricing'

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Hello,

In the future, please post these type of question on the [forum](http://forum.asgardcms.com/).

Open your sidebar class and move your item up. The documentation of [laravel-sidebar](https://github.com/maatwebsite/laravel-sidebar) can help you.
