### ISSUE TITLE
[User 2.0 - bab080c] Missing foreach key value

### ISSUE THREAD

**Issue by armababy** [AsgardCms/Platform#217]
### Summary of issue
View https://github.com/AsgardCms/User/blob/2.0/Resources/views/admin/partials/permissions-create.blade.php#L31 missing ``$permissionAction => $permissionLabel`` pair resulting in ``Undefined variable: permissionLabel`` in 3 subviews.

### Steps to reproduce
Go to ``backend/user/roles/create``

### System Details
- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version: 2.0.x-dev

----------------------
I would PR it but it seems fork of 2.0 User module is disabled :(

**Comment by nWidart** [comment]
Thanks! fixed on https://github.com/AsgardCms/User/commit/4e4aff0c14b857b6fdc7e778469f48a3d95342eb

**Comment by nWidart** [comment]
I'm not sure however why you can't fork the user module. Isn't the fork button active ?

**Comment by armababy** [comment]
Oh my bad, i had some funky old Asgard/User already forked.
Deleted that and can see 2.0.

**Comment by nWidart** [comment]
Ah ok 😄  You can also run `git fetch upstream` (if you named the remote as upstream) to get new repo info like branches.
