### ISSUE TITLE
[Platform 2.0] Folder does not exist

### ISSUE THREAD

**Issue by armababy** [AsgardCms/Platform#218]
### Summary of issue
https://github.com/AsgardCms/Media/blob/2.0/Validators/MaxFolderSizeValidator.php#L29 expects valid folder, but it does not exist ``/public/assets/media``.

### Steps to reproduce
Upload file in ``backend/media/media``

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version: 2.0.x-dev

--------------------------
Seems that this have been lost somewhere from Asgard 1.

**Comment by nWidart** [comment]
Thanks again! Fixed as well on latest platform. https://github.com/AsgardCms/Platform/commit/6a8e398cedd3e181e53ecd0d39a730730065fa64
