### ISSUE TITLE
New way of registering thumbnails for Media

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#220]
With the tag module coming along, I'm thinking to use the same technique to register thumbnails. https://github.com/AsgardCms/Tag#2-defining-a-new-namespace-to-use-for-tags

This would remove a thumbnails.php config file. In turn this also means there won't be any closures in config files anymore, which makes them cachable.

**Comment by armababy** [comment]
I'm all for config cache, was annoying for not to able to do it because of 2 closures :+1:

**Comment by nWidart** [comment]
One "issue", if that, is that users won't easily be able to overwrite the 2 default thumbnails that come with asgard. 

I personally don't think that's that important, since I usually don't even use those 2 thumbnails in projects.

Maybe asgard shouldn't even ship with default thumbnails.

**Comment by armababy** [comment]
Isn't grid and media fields using two default thumbnail sizes?
If they got removed you'd have to put some size constraints on <img> tags, so the user don't upload 1000x1000 and look at that :D

**Comment by nWidart** [comment]
ah yea you're correct. Those thumbnails are used in the media partials.

**Comment by mikemand** [comment]
Maybe change the name of the ones that are shipped with Asgard to something less likely to need overwriting? I usually always end up changing the size of mediumThumb, depending on the requirements for the project. I don't typically make my own sizes unless I need an additional size for something special.

**Comment by nWidart** [comment]
That's a good idea. Now I'm going to spend hours on trying to find a good name. :D

So you never crop/resize your images and let css resize a 3000x3000px image ?

**Comment by mikemand** [comment]
I hardly ever allow images bigger than 500x500px. :P The only special cases are typically the top banner(s), which I put in the Theme's images and just replace if/when they get a new header.

**Comment by armababy** [comment]
I was always thinking why not name them for what they are used for something like: <module>,<function>, <size>. AsgardMediaGridThumbnail, AsgardMediaFieldThumbnail or something like that.

**Comment by nWidart** [comment]
@mikemand I see. To each their own I guess. 😄 I personally create as few thumbnails as possible, but I still create them so that one thumbnail can be used at multiple places. I mind less that css is resizing a 200x200px image to 100x100 for instance.

@armababy For this reason, I'm not sure if naming them based on their usage would be appropriate. However, that is for the custom thumbnails I configure per project & client. 

But maybe that can be an exceptions for the 2 thumbnails asgard ships with.

- smallThumb : used in the index view of images 
- mediumThumb : used in the media partials.

**Comment by armababy** [comment]
Well i personally just do my images for the  entity_purpose_size: site_logo_small etc. So it has never bothered me how are default ones called, but yeah i can see why people had conflicts :)

**Comment by mikemand** [comment]
@nWidart Don't get me wrong, I do use the `mediumThumb` (usually changed to 200px wide instead of the odd 180px) and sometimes `smallThumb` - but not as often - and I create a `largeThumb` (typically 300px wide) on a case-by-case basis. But I still don't let the client upload anything bigger than 1 MB or (more typically) 500x500px. For the web, there is no reason to have huge images, in my opinion.

**Comment by nWidart** [comment]
Currently registering the thumbnails like so:

``` php
$this->app[ThumbnailManager::class]->registerThumbnail('smallThumb', [
    'resize' => [
        'width' => 50,
        'height' => null,
        'callback' => function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        },
    ],
]);
$this->app[ThumbnailManager::class]->registerThumbnail('mediumThumb', [
    'resize' => [
        'width' => 180,
        'height' => null,
        'callback' => function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        },
    ],
]);
```

**Comment by nWidart** [comment]
This can currently be tested on latest Media module.
