### ISSUE TITLE
2.0 On install: User Module - could not find driver

### ISSUE THREAD

**Issue by bishopm** [AsgardCms/Platform#221]
### Summary of issue
Thank you for a great Laravel CMS - I'm loving AsgardCMS!

I saw a thread that said that 2.0 will be out fairly soon and so I tried to install it this morning. On running php artisan asgard:install, I can enter the db details, but then the install fails with 

"Starting the User Module setup ... 

could not find driver"

I know this is a development version, but would love to try it out - any thoughts on what the problem may be?

Thanks

Michael

### System Details

- Operating System: Linux Mint 17.3
- PHP Version 5.6.23
- Laravel Version 5.2
- `Asgardcms/Platform` version 2.0 dev

**Comment by armababy** [comment]
Hey,

Usually, this would point to that no php driver for database setup not found.
Either database settings or php mysql extension (or what kind of driver you use).

**Comment by bishopm** [comment]
Thanks - that'll be it. I had to install php 5.6 to meet the composer requirements and forgot to update the php-mysql package. Will confirm when I'm back at my PC later and close the issue then.
