### ISSUE TITLE
Media Relation one to many problem

### ISSUE THREAD

**Issue by wassimhattab** [AsgardCms/Platform#222]
### Summary of issue
I inserted the include file in the edit blade, and i added the FileRepository in the controller edit function, and i added the MediaRelation in the entity.
When i'm uploading images, it's inserted in the database media__imageables table, but when i go back to the edit page the pictures are not showing.
and when im executing the query in the phpmyadmin its not returning any row while there is a row with the same imageable_id and imageable_type.
Any solution?

**Comment by nWidart** [comment]
Hello,

Make sure you're using the correct methods to fetch your files from the database.

**Comment by wassimhattab** [comment]
I'm facing the problem in the backend 
i added this code in the edit blade:
@include('media::admin.fields.file-link-multiple', [
            'entityClass' => 'Modules\\\\Home\\\\Entities\\\\Home',
            'entityId' => $home->id,
            'zone' => 'slideshow'
 ])

Than used the MediaRelation in the Entity/home

Than added this in the controller edit function :
$slideshow = $fileRepository->findMultipleFilesByZoneForEntity('slideshow', $home);
and added slideshow in the compact function

is there anything else missing ?

**Comment by nWidart** [comment]
If I remember correctly you need to call it `slideshowFiles`

**Comment by wassimhattab** [comment]
Exactly! Thank you

**Comment by nWidart** [comment]
Awesome.

If you're wondering, this whole process has been simplified a lot in upcoming version 2 . 😄
