### ISSUE TITLE
Command to generate entity files after scaffold

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#224]
It would be nice to be able to generate new entities with all their related files after a module has been scaffolded.

This would use : https://github.com/AsgardCms/Workshop/blob/master/Scaffold/Module/Generators/EntityGenerator.php

Command could be:

```
$ php artisan asgard:entity:scaffold <entity-name> <module-name>
```

**Comment by mikemand** [comment]
You could also do it as `module:make-entity <entity> <module>`.

**Comment by nWidart** [comment]
That would mean it's under tha laravel-modules package, which it woudn't be.

**Comment by mikemand** [comment]
Ah, well in that case your command name is fine. :P

**Comment by nWidart** [comment]
This can now be tested in v2: 

Example:
```
// Add a Category entity to the Recipe module
$ php artisan asgard:entity:scaffold Category Recipe
````

**Comment by armababy** [comment]
Tested. Works as expected over here.

**Comment by nWidart** [comment]
Documented as well https://asgardcms.com/docs/v2/workshop-module/generate-entity-files
