### ISSUE TITLE
asgard:install running into a 'file does not exist' error on the 2.0 branch

### ISSUE THREAD

**Issue by SamStenton** [AsgardCms/Platform#228]
When setting up with `php artisan asgard:install` the database details are collected correctly and the .env file is created but when the script gets down to `Starting the User Module setup...` there is a file not exists error pointing to `/site/config/asgard/user/config.php`

### Steps to reproduce
```
composer create-project asgardcms/platform=2.0.x-dev your-project-name
asgard:install
```

![screen shot 2016-08-09 at 23 46 13](https://cloud.githubusercontent.com/assets/5670870/17536237/867b5450-5e8b-11e6-8624-c377ea430862.png)

### System Details

- OSX
- PHP 7.0
- Asgardcms/Platform=2.0.x-dev

**Comment by nWidart** [comment]
Hello,

Thank you for noticing this, it was fixed in the following commit : https://github.com/AsgardCms/Platform/commit/1f95fa96af5960e0c901888bb06c7b81ae17eddb
