### ISSUE TITLE
Unable to upload Media after changing Admin role name

### ISSUE THREAD

**Issue by mikemand** [AsgardCms/Platform#229]
### Summary of issue
When trying to upload media, after changing the name of the "Admin" role, the result is `403: Forbidden` and no media is uploaded.

### Steps to reproduce
* Create a new Asgard 2.0 project, or open an existing one.
* Change the name of the "Admin" role (mine is now "Administrator", per my client's wishes).
* Try to upload Media.
* [Middleware/AuthorisedApiTokenAdmin.php#L34-L47](https://github.com/AsgardCms/User/blob/2.0/Http/Middleware/AuthorisedApiTokenAdmin.php#L34-L47):
```php
if ($found->user->hasRoleName('admin') === false) {
    return false;
}
```
* 403: Forbidden.

Even if you leave the `slug` as "admin", it still does not work.

### Suggested fix
Instead of using `hasRoleName()`, use `inRole()` (from Sentinel). Or, even better, do not require the user to be in a specific group to upload media; use the permissions instead.

### System Details

- Operating System: Mac/Linux
- PHP Version: 7
- Laravel Version: 5.2
- `Asgardcms/Platform` version: 2.0

**Comment by nWidart** [comment]
Thanks for noticing this.

I see it specifically checks on the `name` column.
The check on the role is required since this middleware is _only_ for admins.

However I see the following possible fixes:

- add a `hasRoleSlug` method on the `UserInterface`
- use the `hasRoleId` method already on the `UserInterface`, and use id `1`, since the admin role is always created on installation.

**Comment by mikemand** [comment]
I would create a `hasRoleSlug` method in any event, just to complement the `Id` and `Name` methods.

As a suggested fix, I would use the permissions defined in the media module to check if a user is allowed to upload media.

**Comment by armababy** [comment]
I find this issue to be very much like default_user_role.
`hasRoleSlug` and `hasRoleId` both suffer from lack of costumisation.
You are either set in stone with slug or with id where both for some reason could change.
So i feel like apply same thing as with defaultUserRole, set it in the config.

**Comment by mikemand** [comment]
Some new information:

I have users that are not in the Admin group (and cannot be, because they are not Admins). They cannot do **ANY** API actions, even if they have a valid token because of the `AuthorisedApiTokenAdmin` middleware.

Using this middleware as the default for all API actions does not make any sense to me. It should only be checking for a valid API token. Another middleware can be optionally added to restrict to a specific role, if required.

**Comment by nWidart** [comment]
That sounds like a decent option indeed.

**Comment by mikemand** [comment]
Fixed by all the PRs above. :P

**Comment by nWidart** [comment]
Hehe thanks! 😄
