### ISSUE TITLE
Translation queries, no cache ?

### ISSUE THREAD

**Issue by Fl0ux** [AsgardCms/Platform#231]
### Summary of issue
On the site I am developing, many translations are set using the backend, which use the database to store them. The problem is that now I have hundreds of queries to find each translation. Is there any way to cache those queries or something ?

### Steps to reproduce
Design a page with many translation fields. Translate them using the backend. Watch the result using something like Laravel debugbar.

### System Details

- Operating System
Linux

- PHP Version
5.5.x

- Laravel Version
5.1.x

- `Asgardcms/Platform` version
1.14.1

**Comment by nWidart** [comment]
Hello,

Those will be cached once you enable it in your `.env`, `APP_CACHE` key.
You can also choose to completely disable the GUI for translations via [this config key](https://github.com/AsgardCms/Platform/blob/develop/config/app.php#L47), which will remove the queries and the GUI.

**Comment by Fl0ux** [comment]
APP_CACHE is already set to "true" but the cache driver is set to "array". So I guess this means that cache is only available during the page computation right ?

**Comment by nWidart** [comment]
Indeed array means no cache basically, only at runtime, every time.
Anything but array will work better 😄 .

**Comment by Fl0ux** [comment]
Maybe I could suggest you to use only one request to find all translations keys needed at a time ? (I have not looked into the code to see how it works)

**Comment by nWidart** [comment]
It currently only gets the required translations, not all of them.

**Comment by Fl0ux** [comment]
I agree, but actually each translation key is retrieved by an sql query. Perhaps it would be possible to regroup all those queries into only one ?

**Comment by nWidart** [comment]
Yes, but I don't see the need. Currently it only adds 30-40ms if that, locally (with xdebug). When caching is enabled , 0.
