### ISSUE TITLE
ajax call \Sentinel::check() always return null.

### ISSUE THREAD

**Issue by baotao2006** [AsgardCms/Platform#235]
### Summary of issue

in revisions table, user_id always is null.
### Steps to reproduce

go to the en/backend/translation/translations page, x-edit some translation.
### System Details
- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` 2.0

**Comment by nWidart** [comment]
Hello,

Sorry for the late reply.
This seems to be an issue with revisionable package.

**Comment by baotao2006** [comment]
REST API call ignore session user.

**Comment by baotao2006** [comment]
in Modules\User\Http\Middleware\AuthorisedApiToken.php: 
    private function isValidToken($token)
    {
        $found = $this->userToken->findByAttributes(['access_token' => $this->parseToken($token)]);

        if ($found === null) {
            return false;
        }

        //for rest api current user
        \Sentinel::setUser($found->user);

        return true;
    }



in Modules\User\Http\Middleware\AuthorisedApiTokenAdmin.php: 

    private function isValidToken($token)
    {
        $found = $this->userToken->findByAttributes(['access_token' => $this->parseToken($token)]);

        if ($found === null) {
            return false;
        }

        //for rest api current user
        \Sentinel::setUser($found->user);

        if ($found->user->hasRoleName('admin') === false) {
            return false;
        }

        return true;
    }

**Comment by nWidart** [comment]
Thanks! I will try those out.

**Comment by nWidart** [comment]
Hello,

Sorry for late reply.
I just tested this and it seems to work, thanks! 👍 

I'm not super happy with the fact that it couples sentinel though.

**Comment by nWidart** [comment]
@armababy pointed out ot me that we shouldn't be able to access the session in an API, to have a correct RESTful api, which makes sense.

We'd need to find a way to set that user in API requests found via the token.
And finally Revisionable should have a way to send that user to them, instead of them having to figure it out.

**Comment by nWidart** [comment]
Related: https://github.com/VentureCraft/revisionable/issues/251

**Comment by daoanhvuacc** [comment]
@nWidart , do you have any update to get user by token without access the session?

**Comment by nWidart** [comment]
Yes, you can use this trait: https://github.com/AsgardCms/Platform/blob/2.0/Modules/User/Traits/CanFindUserWithBearerToken.php

**Comment by daoanhvuacc** [comment]
Thanks for help.
