### ISSUE TITLE
User permissions - can't see sidebar without Workshop permission

### ISSUE THREAD

**Issue by joshbrw** [AsgardCms/Platform#237]
### Summary of issue
Assign your role/user the `user.user` permissions, but don't assign any `workshop.*` permissions. The User sidebar links don't show because the Workshop section requires a `workshop.*` permission to be displayed.

https://github.com/AsgardCms/User/blob/master/Sidebar/SidebarExtender.php#L32
https://github.com/AsgardCms/Workshop/blob/master/Sidebar/SidebarExtender.php#L52

### System Details

- Operating System
Ubuntu

- PHP Version
5.5.11

- Laravel Version
5.2

- `Asgardcms/Platform` version
Latest

**Comment by nWidart** [comment]
this was fixed recently. https://github.com/AsgardCms/Workshop/blob/2.0/Sidebar/SidebarExtender.php#L54

**Comment by joshbrw** [comment]
Could this be ported across to v1.0 in Workshop?

**Comment by nWidart** [comment]
Fixed on [workshop 1.17.1](https://github.com/AsgardCms/Workshop/releases/tag/1.17.1)

**Comment by joshbrw** [comment]
Thank you :heart:
