### ISSUE TITLE
Disabling ThrottlingException  

### ISSUE THREAD

**Issue by wassimhattab** [AsgardCms/Platform#238]
### Summary of issue
Hello if i want to use the login on the frontend i used the same action of auth in the backend,
but when i the login is disabled on the frontend because of the ThrottlingException all the emails and the login are blocked is there anyway to disable the ThrottlingException  on he frontend or is there a solution without using the auth of asgard?

**Comment by nWidart** [comment]
You would need to look at Cartalyst/Sentinel for this. 

If I'm not mistaken that exception means you tried to login too many times.

I use the same login for frontend and works fine.

**Comment by wassimhattab** [comment]
Yes it works fine but if i tried to login too many time all the login form will be blocked on all emails not only mine this is my problem

**Comment by nWidart** [comment]
That would be something to ask Sentinel again.

**Comment by armababy** [comment]
You can remove Throttling checkpoint or increase thresholds in [cartalyst.sentinel.php](https://github.com/AsgardCms/Platform/blob/2.0/config/cartalyst.sentinel.php)

**Comment by wassimhattab** [comment]
okay thank you that worked fine
