### ISSUE TITLE
Failing dependencies

### ISSUE THREAD

**Issue by theparker** [AsgardCms/Platform#239]
### Summary of issue
Hi, I am trying out asgardcms but some dependencies are failing including asgardcms/media-module and pingpong/modules. Will using the latest stable versions of these packages break anything? Will be great if you can update the project references. I hope this package is still being maintained. Thanks

https://www.versioneye.com/php/pingpong:modules/dev-feature:5.1

### Steps to reproduce
`composer create-project asgardcms/platform your-project-name`

### System Details

- Operating System Windows 7
- PHP Version 5.6
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
I have no idea what that means, but just update your composer dependencies.

Maybe look at the activity before asking if it's maintained ?
