### ISSUE TITLE
Adding user profile view

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#246]
Continuing https://github.com/AsgardCms/Platform/pull/245 

Still to be discussed.

**Comment by mikemand** [comment]
To summarize what #245 had:

- [ ] Add edit profile page
    - [x] Add routes
    - [x] Add controller actions
    - [ ] Add view
- [x] Add button to top nav for profile
- [x] Add link in sidebar for profile

We agreed to not use permissions for this page, as it will be the currently authenticated user's information in the form and no way to pass another user's ID/Entity to it.
