### ISSUE TITLE
`Themes` not working when run production

### ISSUE THREAD

**Issue by lucduong** [AsgardCms/Platform#248]
### Summary of issue
`Themes` not working when deploy on `Heroku`

```
InvalidArgumentException in compiled.php line 13985:
View [default] not found.
```

`at FileViewFinder->findInPaths('default', array('/app/resources/views')) in compiled.php line 13958`

[Test Link](http://thepizzacompany.herokuapp.com/en)
### Steps to reproduce
Deploy on `Heroku`

### System Details
The newest version of Asgardcms
Running on `Heroku`

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Themes are working on any environment.

What you have looks like a case sensitive issue, so I'd start looking there.

**Comment by tylerssn** [comment]
Ran into this same issue when deploying to Heroku. Were you able to resolve this?
