### ISSUE TITLE
[Blog Module] ReflectionException in Container.php Class does not exist

### ISSUE THREAD

**Issue by LucianoVandi** [AsgardCms/Platform#252]
### Summary of issue
Can't view Blog frontend routes.

Tried to run clear-compiled and optimize command without success. The exception does not even say which class... just _ReflectionException in Container.php line 734: Class does not exist_.

Theme have all files in place, included blog/index.blade.php and blog/show.blade.php

### Steps to reproduce
Install Blog Module, create a post, visit `/en/blog/posts` or `/en/blog/posts/post-slug-en`

### System Details

- Operating System: Ubuntu 16.04 LTS (laravel/homestread)
- PHP Version: 7.0.8-3+deb.sury.org~xenial+1
- Laravel Version: 5.3.9
- `Asgardcms/Platform` version 2.0

**Comment by nWidart** [comment]
Thanks for noticing the issue.

Until a proper fix has been committed you can comment out the middleware options in the routes file.

**Comment by LucianoVandi** [comment]
Thank you @nWidart! So, if I get it the fix consists of adding "middleware" array to config module file? 

Another question regarding the blog module: is it possible to override routes?

**Comment by nWidart** [comment]
That could be but haven't had time to look into it.

You can indeed overwrite any route since this PR https://github.com/AsgardCms/Platform/pull/240

**Comment by LucianoVandi** [comment]
I have applied changes commited with PR #240 and created same routes as frontendRoutes.php from Blog module with modification i needed.

This is the result from php artisan route:list.

```
+--------+----------+-------------------+--------------+------------------------------------------------------+--------------------------+
| Domain | Method   | URI               | Name         | Action                                               | Middleware               |
+--------+----------+-------------------+--------------+------------------------------------------------------+--------------------------+
|        | GET|HEAD | blog              | it.blog      | Modules\Blog\Http\Controllers\PublicController@index | localizationRedirect,web |
|        | GET|HEAD | blog/posts        | it.blog      | Modules\Blog\Http\Controllers\PublicController@index | localizationRedirect,web |
|        | GET|HEAD | blog/posts/{slug} | it.blog.slug | Modules\Blog\Http\Controllers\PublicController@show  | localizationRedirect,web |
|        | GET|HEAD | blog/{$slug}      | it.blog.slug | Modules\Blog\Http\Controllers\PublicController@show  | localizationRedirect,web |
+--------+----------+-------------------+--------------+------------------------------------------------------+--------------------------+
```
It's not working as I expected, default blog routes are still there and yet my custom routes seems to not match.

In fact if I visit /blog or /blog/my-post-slug it throws 404 and the debugbur shows current route "as" => page. What am I doing wrong?

**Comment by armababy** [comment]
The #240 PR loads override routes from `routes/web.php`, so `frontendRoutes` will not not override in your case.

**Comment by LucianoVandi** [comment]
Thanks @armababy, but it says "...allowing to override each routes of the modules directory".

I'm doing some tests extending `Modules\Core\Providers\RoutingServiceProvider` in a new provider and registering it as `App\Provider\CustomRoutesServiceProvider`. This contains the same logic of `Modules\Blog\Providers\RouteServiceProvider` including the routes file from `routes/web.php`.

This seems to work, except that default blog routes are still enabled. It looks like in Laravel you cannot unregister a route...

**Comment by armababy** [comment]
Yes it does override each routes of module directory (means any route registered from modules).
The science is simple, you have to re-define route after module defined it. The `routes/web.php` does that, also you can do this by using module that loads after Blog and redefine blog routes there.

**Comment by LucianoVandi** [comment]
Ok, I see that routes/web.php load after all other routes, but this way I still get NotFoundHttpException when I visit /blog or /blog/post-slug.

This is my routes/web.php:

```
$router->group(['prefix' => 'blog'], function($router){
  $locale = LaravelLocalization::setLocale() ?: App::getLocale();
  $router->get('/', [
    'as' => $locale.'.blog',
    'uses' => 'Modules\Blog\Http\Controllers\PublicController@index'
  ]);
  $router->get('{$slug}', [
    'as' => $locale.'.blog.post',
    'uses' => 'Modules\Blog\Http\Controllers\PublicController@show'
  ]);
});
```

Maybe I'm doing something wrong here...

**Comment by nWidart** [comment]
This was fixed, please update your blog package.
