### ISSUE TITLE
[Feature] Allow permissions on per-page / per-directory base

### ISSUE THREAD

**Issue by amenk** [AsgardCms/Platform#253]
### Summary of issue

As a super-admin I want to create users that can only edit certain pages or upload files to certain subfolders.

**Comment by nWidart** [comment]
I don't think the edit certain pages should be included by default. This would be customised on a per project basis. 

The media module part first needs to be able to create folders. After that this could be considered, but then again I think this is more on a per project basis. 

For both cases the UI wouldn't be that easy to integrate. Where should it be ? How can it be dynamic ? etc.
