### ISSUE TITLE
Admin Backend: View Website should show the current page

### ISSUE THREAD

**Issue by amenk** [AsgardCms/Platform#254]
### Summary of issue

When I am editing a page in the backend, "view website" should/could display the current page

### Steps to reproduce

* Edit a page
* Press view website
* The root page is opened

Instead:

* Open the subpage, in the current language

**Comment by nWidart** [comment]
This is currently the intended behaviour.

There was however a PR sent to allow to preview/view a page (https://github.com/AsgardCms/Page/pull/19), but never quiet finished.
