### ISSUE TITLE
[Feature] Workshop module: allow Admin to update modules from browser

### ISSUE THREAD

**Issue by bishopm** [AsgardCms/Platform#262]
Feature proposal:

The workshop module includes an artisan command to allow asgardcms composer packages to be updated. Would it be possible to allow those commands be run from the browser (like October's module update system - octobercms.com)? - it would allow an administrator to keep a site up to date without having to give that person shell access. Does that create security problems? Would it be easy to extend the same functionality to custom (non-asgardcms) modules (or allow a full 'composer update')?

**Comment by nWidart** [comment]
I don't think is a good idea. 

You should never update packages without testing them first. Hence the composer.lock file.
Packages should always be updated locally, tested, and then deployed on server and installed using `composer install`.
