### ISSUE TITLE
[2.0.x-dev] Method normalInputOfType does not exist.

### ISSUE THREAD

**Issue by arturmamedov** [AsgardCms/Platform#264]
### Summary of issue
Method `normalInputOfType` does not exist.

### Steps to reproduce
When i try to access `/backend/account/profile`

### System Details
- Operating System `Windows 10`
- PHP Version `5.6.12`
- Laravel Version `5.3.10`
- `Asgardcms/Platform` version `2.0.x-dev`

**Comment by arturmamedov** [comment]
I think you need to merge this to v2 https://github.com/AsgardCms/Platform/pull/250

**Comment by mikemand** [comment]
#250 is already merged. Check your version of the Core module: `composer info idavoll/core-module`

![screen shot 2016-09-27 at 11 18 33 am](https://cloud.githubusercontent.com/assets/745184/18884329/39bdb920-84a4-11e6-8000-2b1c0cbeab67.png)

**Comment by arturmamedov** [comment]
Yes i run composer update and all in the place. Thankyou!!
