### ISSUE TITLE
Move app folder

### ISSUE THREAD

**Issue by imamhabib** [AsgardCms/Platform#267]
i have installed asgardcms to my machine but i have a problem because i installed it in wrong folder. i want to move my app to root folder. my installed folder like this c:/xampp/htdocs/folder/asgradcms  i want to move in c:/xampp/htdocs/asgardcms. i have move it manually but occur error when access the URI. how can i change this configuration without new installation... thanks

**Comment by nWidart** [comment]
This is not related to asgardcms, pleaser refer to laravel or general development.

Thanks

**Comment by arturmamedov** [comment]
Why you need to move it? Put a .htaccess that redirect the call from your root to /asgardcms/public ex:
```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule    ^$    asgardcms/public/    [L]
    RewriteRule    (.*) asgardcms/public/$1    [L]
</IfModule>
```
