### ISSUE TITLE
PHP Error - Function mcrypt_get_iv_size() is deprecated

### ISSUE THREAD

**Issue by davidbwaters** [AsgardCms/Platform#271]
Hi, after a (seemingly) successful install, I'm getting this error: 
'Function mcrypt_get_iv_size() is deprecated'

![asgard-error-1](https://cloud.githubusercontent.com/assets/5247627/18988313/1fb64718-86d4-11e6-89db-ce9002cdb6a8.PNG)

Steps to reproduce:
Successfully installed Asgard locally with Composer following docs and tried to access /public

Operating System - Windows 10
PHP Version - 7.1.0beta1
Laravel Version - um used Composer command from docs 09/26/16
`Asgardcms/Platform` version - used Composer 09/26/16

**Comment by baotao2006** [comment]
run
php artisan key:generate

**Comment by davidbwaters** [comment]
okay, i ran this and got
'Application key [ ..key..] set successfully.
but i'm still getting the error.  thanks for the help

**Comment by nWidart** [comment]
Php 7.1 has not been released yet. Try running it on php 7 Thanks.

**Comment by khooz** [comment]
I suggest reopening the issue since PHP 7.1 has just released this December.

By the way, closing this issue just because PHP 7.1 hadn't have been released at that point was sloppy and bad practice. One of the main reasons for pre-release versions is compatibility checks.

**Comment by armababy** [comment]
This is obviously laravel stuff.

**Comment by nWidart** [comment]
You're right @khooz however this wasn't related to AsgardCMS.

**Comment by davidbwaters** [comment]
I ended up reinstalling and got it working

**Comment by flo-sch** [comment]
I'm not even using AsgardCMS but as I faced the same issue with OctoberCMS.

It is indeed a conflict between `php 7.1` and the php `mcrypt` extension.

In `config/app.php`, you most likely have the `cipher` key defined as the `MCRYPT_RIJNDAEL_128` constant, which uses mcrypt.
`mcrypt` is now deprecated, from the PHP official documentation :

> This extension has been deprecated as of PHP 7.1.0 and moved to PECL as of PHP 7.2.0.

And it should be better to relate on `openssl` or even `libressl` (please ensure that your system's openssl version is safe, some versions are vulnerable!)

To do so, first update the Laravel version of the project :

Edit your composer.json file : 

```
{
    "require": {
        "php": ">=5.4",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.1.*",
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~4.0",
        "phpunit/phpunit-selenium": ">=1.2"
    },
    // ...
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}
```

Then execute either :
`composer update`

Or :
`php composer.phar update`

Depending of your composer installation.

Then update the `config/app.php` file with an openssl cipher, such as `AES-256-CBC` :

```
return [
    // [...]
    'cipher' => 'AES-256-CBC',
    // [...]
];
```

Then run once again :

`php artisan key:generate`

(Ensure the generated key is set in `config/app.php` file aswell...)

And you should be able to use php 7.1

**Comment by nWidart** [comment]
Awesome information @flo-sch ! Thanks for taking the time to explain this! 👍

**Comment by nWidart** [comment]
Here go you https://stackoverflow.com/questions/41031076/php7-1-and-laravel-5-3-function-mcrypt-get-iv-size-is-deprecated
