### ISSUE TITLE
Auth Controller get User role and permission

### ISSUE THREAD

**Issue by divyasreem** [AsgardCms/Platform#273]
### Summary of issue

I need to get the use roles and permissions in auth  controller, please help me out because based on roles and permissions need to redirect to a specific page
### System Details
- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by arturmamedov** [comment]
Can you be more specific, i not understand what you need to do. @divyasreem

**Comment by arturmamedov** [comment]
This work always 
```
use Modules\User\Contracts\Authentication;
....
$auth = app(Authentication::class); 
//After for retrive user
$auth->check() // for Asgard v1
$auth->user() // for Asgard v2 also ->check() for bool logged inor not, ->id() for only the id of user
```

**Comment by divyasreem** [comment]
In Postlogin() , Need the role for the logged user based on role I will redirect him to particular page.

Used this $this->auth->check(), but I am getting only logged user details but I need roles data also.

**Comment by mikemand** [comment]
The User entity has a relationship called `roles()` from Sentinel in the `\Cartalyst\Sentinel\Users\EloquentUser` class (which the User module entity extends).

**Comment by arturmamedov** [comment]
Its Laravel Eloquent functionality
```
// You retrive your user
$auth = app(Authentication::class); 
$user = $auth->check()
// And after use `hasRoleName()` for check it
$user->hasRoleName('Admin');
```
