### ISSUE TITLE
Translated Routes

### ISSUE THREAD

**Issue by LucianoVandi** [AsgardCms/Platform#274]
### Summary of issue

Is it possible to handle translated routes for each page or blog post.

I mean: user visit page in english, the url is `website.com/english-page`. User switch language to spanish and gets redirected to `website.com/es/spanish-page`.

Something as documented [here](https://github.com/mcamara/laravel-localization#translated-routes).
### System Details

Operating System: Ubuntu 16.04 LTS (laravel/homestread)
PHP Version: 7.0.8-3+deb.sury.org~xenial+1
Laravel Version: 5.3.16
Asgardcms/Platform version 2.0

**Comment by nWidart** [comment]
You can, you linked the correct documentation to do so.

**Comment by sagsoz06** [comment]
I tested according to the document. Exactly what I'm looking for. Thanks @LucianoVandi

**Comment by LucianoVandi** [comment]
@sagsoz06 I didn't have time to test it yet. Can you share an example? Thanks!

**Comment by sagsoz06** [comment]
First
App/Http/Kernel.php
```
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        // 'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];
```

Second
Modules/Store/Http/frontendRoutes.php

```
$router->group(['prefix' => '', 'middleware' => ['localize']], function (Router $router) {
    $router->get(LaravelLocalization::transRoute('store::routes.products'), [
        'uses' => 'PublicController@index',
        'as'   => 'store.index'
    ]);
    $router->any(LaravelLocalization::transRoute('store::routes.product'), [
        'uses' => 'PublicController@product',
        'as'   => 'store.product'
    ]);
    $router->any(LaravelLocalization::transRoute('store::routes.category'), [
        'uses' => 'PublicController@category',
        'as'   => 'store.category'
    ]);
});
```
Third
Modules/Store/Resources/Lang/en/routes.php

```
return [
    'category' => 'category/{uri}',
    'product'  => 'product/{uri}',
    'products' => 'products'
];
```

Thats it! I hope it helps.

**Comment by armababy** [comment]
Just one side note for easier future updates with the platform itself, you should add `localize` middleware inside one of your modules, and register in ServiceProvider.

**Comment by LucianoVandi** [comment]
Thanks @sagsoz06 but it's not what I'm trying to archive, or maybe I miss something... 

Following this solution I get translated only the "static" segment of the URL. Let's say I have a category called "beer", on the Deutsch version of the site I translate it to "bier".

I expect that when I get to mysite.com/**category/beer** changing the language to Deutsch will redirect me to mysite.com/de/**kategorie/bier**

The official docs show [the event routes.translation](https://github.com/mcamara/laravel-localization#events), but I'm still trying to it figure out...

**Comment by sagsoz06** [comment]
Hi @LucianoVandi,
Sorry I have forgot to write an answer.

I assume you have a language switcher blade file. You need to use a switch like the below.

```
@foreach(LaravelLocalization::getSupportedLocales() as $locale => $supportedLocale)
@php
switch (Request::route()->getName()) {
 case 'page':
    $url = \LaravelLocalization::getLocalizedURL($locale, $page->translate($locale)->slug);
 break;
 default:
 $url = null;
 break;
}
$localizedUrl = LaravelLocalization::getLocalizedURL($locale, $url);
@endphp
<a lang="{!! $locale !!}" href="{{ $localizedUrl }}">{{ $locale }}</a>
@endforeach
```

It was request specific slug in the every module and page. So, you can solve in this way.
