### ISSUE TITLE
Sidebar "Content" group missing if user doesn't have Page permissions

### ISSUE THREAD

**Issue by mikemand** [AsgardCms/Platform#276]
### Summary of issue
The sidebar group "Content" disappears if the user doesn't have permissions for 'page.*', even if they have permissions for another module that has an entry in that group.

### Steps to reproduce
Create/edit a user, set 'page.*' permissions to Deny.

Looks like it is caused by this block of code:
```php
$group->authorize(
    $this->auth->hasAccess('page.*')
);
```
here: [Modules/Page/Sidebar/SidebarExtender.php#L50-L52](https://github.com/AsgardCms/Platform/blob/2.0/Modules/Page/Sidebar/SidebarExtender.php#L50-L52)

Edit: To clarify, this only happens if the user doesn't have ANY permissions for the Page module.

### System Details

- Operating System: Mac/Linux
- PHP Version: 7.0.11
- Laravel Version: 5.3.18
- `Asgardcms/Platform`: 2.0.x-dev

**Comment by armababy** [comment]
Yeah, this is not a good way as discussed on a slack.
And I still stand by the opinion that we need new permission entry for `Core` module to control this.

Something like `core.contents.sidebar.group` if no permission in granted there all Content group is not visible no matter what permissions are set on single items under that.
And of course, if permission is granted to view Contents sidebar group, you still have individual module permissions working.

**Comment by mikemand** [comment]
I agree, a core permission is needed for these AND the Workshop group. @nWidart if you agree I will PR tomorrow to fix the issue.

**Comment by nWidart** [comment]
That could be a good idea indeed.

**Comment by mikemand** [comment]
I don't know why this didn't automatically close. Github says it will, but it didn't. Oh well.

**Comment by armababy** [comment]
Don't know about closes tag but i did it with fixes tag before for automatic resolution of issue.
