### ISSUE TITLE
Change in Laravel 5.3 prevents Dashboard module from accessing current user in constructor

### ISSUE THREAD

**Issue by bishopm** [AsgardCms/Platform#278]
### Summary of issue

A change in Laravel 5.3 documented [here](https://laravel.com/docs/5.3/upgrade#5.3-session-in-constructors) results in not being able to access the current user in a Controller constructor as is currently done in v2.0 of the Dashboard module.
### Steps to reproduce

```
public function __construct(Repository $modules, WidgetRepository $widget, Authentication $auth) {
 parent::__construct();
 $this->bootWidgets($modules);
 $this->widget = $widget;
 $this->auth = $auth;
}
```

In the DashboardController constructor, $this->auth->check() returns false, although the user is logged in. This means that widgets cannot be designed which display data relating to the current user only (eg: in a todo module, the current user's incomplete tasks).
### System Details
- Linux Mint 18
- PHP Version: 7.0.8
- Laravel Version 5.3.18
- `Asgardcms/Platform` version 2.0

**Comment by nWidart** [comment]
Hello,

The constructor of the DashboardController doesn't use the check() method so it shouldn't cause any issues.

**Comment by bishopm** [comment]
Sorry - my miscommunication - I inserted check() to test what was being stored in $this->auth and it returned false.

At present, there is no value passed to $this->auth because of the changes in L5.3

**Comment by nWidart** [comment]
Indeed, you need to run it outside the constructor, or in a closure middleware.

**Comment by bishopm** [comment]
I see - thank you! Running $this->auth->user() in the index method does indeed return the current user's details. 

Is there a way to access the user id from a widget without modifying the Dashboard controller?

**Comment by nWidart** [comment]
Hm you can't call the closure middleware in something else than a controller so that won't work. You would have to call the Authentication contract to get the user id I think.
