### ISSUE TITLE
Authenticate middleware fails to check if user is authenticated

### ISSUE THREAD

**Issue by skvorets** [AsgardCms/Platform#279]
### Summary of issue
In the middleware \app\Http\Middleware\Authenticate.php at handle() method 
$this->auth->guest() always returns true, even if the user is logged in.

### Steps to reproduce
```
public function handle($request, Closure $next)
	{
		dd($this->auth->guest())
		if ($this->auth->guest())
```

After changing to
```
public function handle($request, Closure $next)
	{
		$this->auth = app(Authentication::class);
		if (!$this->auth->check()) {
```
works as it should.

### System Details

- Operating System Windows 7
- PHP Version 7.0.7
- Laravel Version 5.3.18
- `Asgardcms/Platform` version 2.0

**Comment by nWidart** [comment]
There is no guest method.

And the check method will return false, if not logged in.

**Comment by skvorets** [comment]
Yes, there is _no_ guest method that's why I've created this issue.
Please check https://github.com/AsgardCms/Platform/blob/develop/app/Http/Middleware/Authenticate.php
if ($this->auth->guest())  is there.

**Comment by nWidart** [comment]
That's laravel's middleware, not one from asgardcms.

**Comment by skvorets** [comment]
Ah, got it. I'm still new to Laravel, thank you.

**Comment by nWidart** [comment]
no worries.

If you want to use that middleware you need to use the Authentication interface from the User module.
