### ISSUE TITLE
missing (../../Modules/Core/Sidebar/SidebarExtender.php) in Core module

### ISSUE THREAD

**Issue by oimken** [AsgardCms/Platform#284]
### Summary of issue
Fresh install AsgardCms 2.0, after loged in backend, got this error:
```ErrorException in ClassLoader.php line 409: include(../../Modules/Core/Sidebar/SidebarExtender.php): failed to open stream: No such file or directory```

### Solution
Create "/Modules/Core/Sidebar/SidebarExtender.php" with content:
```
<?php

namespace Modules\Core\Sidebar;

use Maatwebsite\Sidebar\Menu;

class SidebarExtender implements \Maatwebsite\Sidebar\SidebarExtender
{
    /**
     * @param Menu $menu
     *
     * @return Menu
     */
    public function extendWith(Menu $menu)
    {
        return $menu;
    }
}
```
everything fine...

### Steps to reproduce
Fresh install AsgardCms 2.0, log in backend

### System Details

- Operating System
- PHP Version 6.5
- Laravel 5.3
- `Asgardcms/Platform` 2.0

**Comment by mikemand** [comment]
That file is here: https://github.com/AsgardCms/Platform/blob/2.0/Modules/Core/Sidebar/SidebarExtender.php

Can you run

```sh
composer show idavoll/core-module
```

and tell me what it says next to the "Source:" line?

Here's mine:
![screen shot 2016-10-22 at 10 26 14 am](https://cloud.githubusercontent.com/assets/745184/19620830/1c035618-9842-11e6-910d-a45a2ce6301d.png)

I'm interested in the commit hash (`cce0dfbb4064f90c242328399dd068611500811e`, in my case).

**Comment by oimken** [comment]
Sorry , I know my problem...   Platform contain all modules in 2.0......
I be away from asgard for months, things are different...

here are my problem:

1. I clone AsgardCms/Platform 2.0, and remove all the modules in /Modules folder
2. I clone every single Module into Platform's Modules folder.
......
I intent to keep every module update, but it seems Platform's module is not the same ?

**Comment by oimken** [comment]
there are `idavoll/core-module`  and  `asgardcms/core-module` ........ i did not pay attention.

**Comment by nWidart** [comment]
idavoll/ is the name organisation with 2.0 modules.

I'll close this for now :)
