### ISSUE TITLE
Problem after install 2.0-dev

### ISSUE THREAD

**Issue by sdalibardgm** [AsgardCms/Platform#289]
Hi everebody,

I have a problem after install Asgard, i can't run php artisan.

My steps : 
`composer create-project asgardcms/platform=2.0.x-dev demo`
=> it's OK
`php artisan asgard:install`
=> it's OK, i have the message "Platform ready! You can now login with your username and password at /backend" but when i go to /backend, i have an error 500.

And if i test to run php artisan, i have an error : 
```
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Modules\User\Contracts\Authentication] is not instantiable while building [App\Exceptions\Handler, App\Exceptions\Handler].' in /var/www/demo/bootstrap/cache/compiled.php:1384
Stack trace:
#0 /var/www/demo/bootstrap/cache/compiled.php(1330): Illuminate\Container\Container->build('Modules\\User\\Co...', Array)
#1 /var/www/demo/bootstrap/cache/compiled.php(1908): Illuminate\Container\Container->make('Modules\\User\\Co...', Array)
#2 /var/www/demo/bootstrap/cache/compiled.php(1431): Illuminate\Foundation\Application->make('Modules\\User\\Co...')
#3 /var/www/demo/bootstrap/cache/compiled.php(1408): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#4 /var/www/demo/bootstrap/cache/compiled.php(1394): Illuminate\Container\Container->getDependencies(Array, Array)
#5 /var/www/demo/bootstrap/cache/compiled.php(1330): Illuminate\Container\Container->build('App\\Exceptions\\...', Array)
#6 /var/ww in /var/www/demo/bootstrap/cache/compiled.php on line 1384
```

Can you help me ?

**Comment by yusidabcs** [comment]
any solution, I upgrade to v2 but get error

PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Modules\User\Contracts\Authentication] is not instantiable while building [App\Exceptions\Handler, App\Exceptions\Handler, App\Exceptions\Handler].

**Comment by armababy** [comment]
Can you try deleting vendor folder and running `composer install` again?

**Comment by yusidabcs** [comment]
@armababy after delete vendor folder and install again still the error. blank page in browser and in log console:

`PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Modules\User\Contracts\Authentication] is not instantiable while building [App\Exceptions\Handler, App\Exceptions\Handler, App\Exceptions\Handler]. in /Applications/MAMP/htdocs/your-project-name/vendor/laravel/framework/src/Illuminate/Container/Container.php:763
`

**Comment by armababy** [comment]
@yusidabcs This is very strange, I was able to get this same error you are having when I first installed 2.0-dev, but after I deleted the project and ran `create-project` again, the error was gone and could not receive it anymore. Even tried to do fresh installs in other folders.

**Comment by nWidart** [comment]
Can you try to remove the condition completely here: https://github.com/AsgardCms/Platform/blob/2.0/app/Exceptions/Handler.php#L62 ?

So that only the following stays:

``` php
    public function render($request, Exception $e)
    {
        return parent::render($request, $e);
    }
```

**Comment by armababy** [comment]
Out of curiosity can you check what Folders are there in `Themes` folder (exact capitalization pls)?

**Comment by yusidabcs** [comment]
@nWidart I've removed the code but the error still there.. 
@armababy sorry for the trouble :D, I also curious since I need upgrade to v2. Some dependency in v1 can't updated now. Here I attach the sc of `Themes` folder

![screen shot 2016-11-29 at 9 51 22 am](https://cloud.githubusercontent.com/assets/4271647/20693553/1d4e522a-b61a-11e6-8dc2-099ee817e58b.png)

**Comment by armababy** [comment]
@yusidabcs Okay, that's kind of great, I was getting the same error on some machines.
So can you try one of these two:
a) do a `mv AdminLTE/ Adminlte` delete vendor folder, delete `bootstrap/cache/compiled.php`
b) do a clean `composer create-project` of asgrad 2.0-dev, after composer finish'es do a `mv AdminLTE/ Adminlte` and run `composer install` again, and only after that try `asgard:install`

trying to pinpoint the problem :)

**Comment by tylerssn** [comment]
I have run into similar "not instantiable while building".  If I remember correctly, `php artisan route:clear` helps.

**Comment by yusidabcs** [comment]
@tylerssn artisan command also throw with same problem, so I can't artisan route:clear
