### ISSUE TITLE
Installer Error:   [ERROR] Undefined variable: output Enter a password:

### ISSUE THREAD

**Issue by MustangZhong** [AsgardCms/Platform#290]
### Summary of issue
when I try to run the command "php artisan asgard:install", after finishing "Last Name"
the screen keeps showing:

>  [ERROR] Undefined variable: output
> 
>  Enter a password:

php artisan asgard:install

### Steps to reproduce
1. run command "php artisan asgard:install"

**[Update]**
it seems that I can't input the new user's password.
after entering the email address, the screen just keep showing "Enter a password" 
but actually I can't input as the keep repeat showing.

### System Details

- Operating System: Centos
- PHP Version: PHP 5.6.24
- Laravel Version: 5.1.45 (LTS)
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Hello, 

Please use the latest version. Let me know if the issue persists.
