### ISSUE TITLE
Not creating thumbnail in media

### ISSUE THREAD

**Issue by wassimhattab** [AsgardCms/Platform#291]
### Summary of issue
When i upload an image in media module it's not creating the thumbnails, any idea about it?

**Comment by motchju** [comment]
Do you have the GD libray installed ?

http://php.net/manual/en/book.image.php

Anything relevant in the logs?

**Comment by wassimhattab** [comment]
There's nothing relevant in the logs
And i didn't change anything in the files i dunno if the GD library installed just when i upload the image the original image is uploaded in the assets/media but the thumbnail is not generated so in the backend it show me a crash link

**Comment by motchju** [comment]
Well to manipulate the image, you need to have the GD library, you can check it easily with a phpinfo()

**Comment by wassimhattab** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20112008/20340817/18be8c9e-abec-11e6-816c-4b835923b7a3.jpg)

This is what phpinfo give me regarding gd

**Comment by motchju** [comment]
Hmm at this stag I can't help more without some logs, did you check also  in the storage/logs ?

**Comment by wassimhattab** [comment]
Nothing u\in the table madmin_log or in the storage/logs still empty

**Comment by motchju** [comment]
And nothing on apache logs or nginx ?

**Comment by motchju** [comment]
When you do the upload, check XHR network (via Chrome enable keep the logs ) and tell me the result

**Comment by wassimhattab** [comment]
i replaced the config files and it worked thank you

**Comment by jdnierth** [comment]
Hi wassimhattab, can you please elaborate which config file you have replaced and with what? I'm experiencing the same issue:
- GD lib installed and lists the same values as your screenshot from Nov 16, 2016
- No PHP_error logs
- No logs within storage
- original file gets generated and in my case added to the corresponding public folder hence it can't be a permission / access issue that the thumbnails are not being generated
- current config/asgard.media.thumbnails.php looks as follows
`return [
    'smallThumb' => [
        'resize' => [
            'width' => 50,
            'height' => null,
            'callback' => function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            },
        ],
    ],
];`

Any hint is highly appreciated.

**Comment by Jaylaxmiaussizz** [comment]
In admin panel no images are displaying....
Even not display in any content after adding images through admin.
Even not at frontend.
