### ISSUE TITLE
Error when scaffold new module with name as camelCase method. 

### ISSUE THREAD

**Issue by vinaykevadia** [AsgardCms/Platform#292]
### Summary of issue
When you scaffold module and use module name as camelCase letter it is giving error as follow while loading backend users page "/backend/user/users" after creating new module, i.e. module name i gave "CompetitiveAdvantage"

``
FatalErrorException in ServiceProvider.php line 59:
Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required '/home/vagrant/Code/bizplan-laravel/Modules/Competitiveadvantage/Config/permissions.php' (include_path='.:/usr/share/php:/usr/share/pear:')
``
### Steps to reproduce
1. scaffold module 
2. use module name as camelcase letter i.e. "CompetitiveAdvantage"
3. add Eloquent entity CompetitiveAdvantage

### System Details

- Operating System Ubuntu
- PHP Version 5.6
- Laravel Version ~5.2
- `Asgardcms/Platform` version V2

**Comment by vinaykevadia** [comment]
Error is there in boot method of module service provider : 
case sensitivity in file path for "competitiveadvantage". 
``
public function boot()
    {
        $this->publishConfig('competitiveadvantage', 'permissions');
    }
``

**Comment by armababy** [comment]
Yes, the scaffold should use camelCase for that `publishConfig`, meanwhile, you can update it manually so you can continue to work. Either full camelCase or just any Camel after first one first one converted automatically)
`$this->publishConfig('competitiveAdvantage', 'permissions');`
