### ISSUE TITLE
Menu Modify not working

### ISSUE THREAD

**Issue by sagsoz06** [AsgardCms/Platform#295]
```
\Menu::modify('main', function ($menu) {
    $menu->add([
       'title' => 'test',
        'url' => 'test'
    ]);
});
```

I want to change or add to menu. But I get an error.

`Call to a member function add() on null`

Previously I added in asgardcms version 1.  Then it worked. But it isn't working version 2.

As far as I can see before it was working on pingpong menu. After that new version it started to work with nwidart menu. Can you fix this?

**Comment by nWidart** [comment]
Hello,

Can you check what class you're getting in the closure ? It should be the MenuItem if I remember correctly.
https://github.com/nWidart/laravel-menus/blob/master/src/MenuItem.php#L225

The package has changed vendor, but logic wasn't changed.
This issue should be posted on that package, not here.

**Comment by sagsoz06** [comment]
Hi,

Thank you for support. I fixed the problem. The problem has in module.json. For menu modify If a created new module, need to be sorting.
