### ISSUE TITLE
Table 'migrations' already exists on fresh install

### ISSUE THREAD

**Issue by nathanjoyes** [AsgardCms/Platform#299]
### Summary of issue

With a default fresh installation, I get a database error that the migrations table already exists. 

### Steps to reproduce
cd ~
rm -rf ~/mla
mkdir -p ~/mla
cd ~/mla
mysql --execute="drop database if exists mla"
mysql --execute="create database mla"
composer create-project asgardcms/platform masters
cd masters
php artisan asgard:install

After entering the MySQL connection and user information I get this error.

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'migrations' already exists (SQL: create table `migrations` (`migration` varchar(255) not null, `batch` int not null) default character set utf8 collate utf8_unicode_ci)

When started, I get an error that the pages__pages table does not exist.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mla.page__pages' doesn't exist (SQL: select * from `page__pages` where `is_home` = 1 limit 1)

### System Details

- Operating System - Fedora 23
- PHP Version - 5.6.27
- Laravel Version - 5.1
- `Asgardcms/Platform` version - 1.14.1

**Comment by nathanjoyes** [comment]
From closed issue 188 I was able to follow @nWidart's fix (https://github.com/AsgardCms/Platform/issues/188#issuecomment-208567771) to start AsgardCMS. It looks like that issue was closed and fixed in version 1.14.1, which is the same version that I am using.

**Comment by nWidart** [comment]
Awesome, good to know. 👍
