### ISSUE TITLE
Target [Modules\Core\Contracts\Authentication] is not instantiable during composer install

### ISSUE THREAD

**Issue by tylerssn** [AsgardCms/Platform#301]
### Summary of issue
Deploying AsgardCms into production - artisan commands cannot execute. Impacts composer install/update

This appears to be somehow connected to asgard:install command. In my vagrant box, which is where the install command was executed and all my staging is performed, I do not see this error. However, if I exit vagrant and run `php artisan` on the host machine or when attempting to deploy to production, I get the error referenced here.

### Steps to reproduce
1. Composer create project (AsgardCms 2.0)
2. php artisan asgard:install
2. Add to git repository
3. Pull repository into production
4. composer update OR composer install --both fail

### System Details

- Operating System: Ubuntu
- PHP Version: 7.1/7.0
- Laravel Version: 5.3.19
- `Asgardcms/Platform` version: 2.0

**Comment by nWidart** [comment]
This usually means another error. 
Go into the Exceptions/Handler.php file and remove the conditions there to use laravels handler, and you will see the actual error.

**Comment by zedee** [comment]
Hmm, suddenly I updated an hour ago or so, and got the very same error.

`php artisan asgard:install` process go well, but a `php artisan module:migrate` after triggers this error.

This morning this haven't happened, as I had to do the same process several times due to solve/debug half-way migrations.

Which conditions we have to remove in order to use Laravel's handler?

**Comment by tylerssn** [comment]
@nwidart, you're right. This wasn't a lack of files or misconfiguration. The underlying issue, for me,  was that I attempted to deploy to "production" before production could communicate to my database - Laravel could not log in to MySQL.

**Comment by zedee** [comment]
Found it too. In my case the real error was a misplaced space in the .env file.

For those who still figures which are the _conditions to use Laravel's handler_, remove temporary the `Authentication $auth` parameter and comment the line `$this->auth = $auth` in the constructor of the `Exceptions/Handler` class.
