### ISSUE TITLE
 Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Modules\User\Contracts\Authentication] is not instantiable while building [App\Exceptions\Handler, App\Exceptions\Handler].'

### ISSUE THREAD

**Issue by esien525** [AsgardCms/Platform#303]
Everything is work fine in my local. When I moved my CMS to server, I get ` PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Modules\User\Contracts\Authentication] is not instantiable while building [App\Exceptions\Handler, App\Exceptions\Handler].' in /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php:763
Stack trace:
#0 /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Modules\\User\\Co...', Array)
#1 /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Modules\\User\\Co...', Array)
#2 /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php(864): Illuminate\Foundation\Application->make('Modules\\User\\Co...')
#3 /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php(819): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#4 /home/ in /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 763
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Modules\User\Contracts\Authentication] is not instantiable while building [App\Exceptions\Handler, App\Exceptions\Handler, App\Exceptions\Handler].' in /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php:763
Stack trace:
#0 /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Modules\\User\\Co...', Array)
#1 /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Modules\\User\\Co...', Array)
#2 /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php(864): Illuminate\Foundation\Application->make('Modules\\User\\Co...')
#3 /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php(819): Illuminate\Container\Container->resolveClass(Object(Reflect in /home/gomutvgo/www/mutvcms/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 763
`

any clue about this error? I am using t2.micro, I am not able to perform `composer update` as well.

- Operating System : windows 10
- PHP Version : php5.6
- Laravel Version : 5.3
- `Asgardcms/Platform` version : v2

**Comment by mikemand** [comment]
Try the method described by @zedee [here](https://github.com/AsgardCms/Platform/issues/301#issuecomment-267001530) to get the underlying error, then post it here (unless you can see what it means and can solve it without help).

**Comment by nWidart** [comment]
This has been comitted https://github.com/AsgardCms/Platform/commit/58cbc388505144ba1dedd799ed2ba2895ec5a5a2 

Please try again and let us know if the issue persists.
