### ISSUE TITLE
Asgardcms theme not pointing to Themes path

### ISSUE THREAD

**Issue by dulabs** [AsgardCms/Platform#304]
### Summary of issue
Asgardcms theme not pointing to Themes path, but to current laravel resources view.

### Steps to reproduce
* install asgard
```bash
php artisan asgard:install
```
* generate key
```bash
php artisan key:generate
```

* cache config
```bash
php artisan config:cache
```
open backend
```
http://[domain]/en/backend
```

and display
```
View [partials.notifications] not found
```

### System Details

- Operating System: Ubuntu Trusty in Windows Vagrant 
- PHP Version: 5.6.28
- Laravel Version: 5.3
- `Asgardcms/Platform` version: 2.0.*-dev

**Comment by mikemand** [comment]
This also happens when you try to go to the login or register pages and don't have an `account.blade.php` in `Themes/{Theme}/views/layouts/`:

```
View [layouts.account] not found
```

As a temporary workaround, you can copy the file(s) from the Flatly theme to yours.

**Comment by dulabs** [comment]
Thank you for response @mikemand 
but, I got
```
FatalErrorException in ThemeHtmlBuilder.php line 59:
Call to a member function hasParent() on null
```
Still searching for solution.

**Comment by dulabs** [comment]
It's solved.

Just delete views cache in ```storage/framework/views```
and config cache in ```bootstrap/cache```
and refresh the browser

**Comment by pleone** [comment]
Just a note that helped me: be sure that you have INSTALLED=true on your .env file

**Comment by JAIHARI** [comment]
thanks, brother after finally resolved.

**Comment by vidhi041** [comment]
Working for me by using  url **http://127.0.0.1:8000/en/backend**
