### ISSUE TITLE
Views: AdminLTE Theme custom error 500 page, causes WSOD with debug disabled

### ISSUE THREAD

**Issue by zedee** [AsgardCms/Platform#305]
### Summary of issue
The custom error 500 page of AdminLTE theme, is not correctly displayed, as there's a miswritten translation key passed to the `trans()` function.
In line 8 of `Platform/Themes/Adminlte/views/errors/500.blade.php`, you'll see:
```
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> {{ trans('core::core::core.breadcrumb.home') }}</a></li>
``` 

And it should be:

```
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> {{ trans('core::core.breadcrumb.home') }}</a></li>
``` 
(Supress the extra `::core`)

### Steps to reproduce

- Set `APP_DEBUG=true` in your `.env` file.
- Trigger something in the backend that could cause an error 500.
- Check out the logs for this warning:
```
PHP warning:  htmlspecialchars() expects parameter 1 to be string, array given in /home/projects/www/myapp/vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 519
```

### System Details

- Operating System
   - Ubuntu Linux 16.10 + Apache 2.4
   - Windows Server 2016 + IIS 10
- PHP Version
   - 7.0.9 x64
- Laravel Version
   - 5.3.19
- `Asgardcms/Platform` version
   - 2.0

I'd do a PR by myself but seems that I cannot checkout 2.0 branch on my cloned fork

**Comment by mikemand** [comment]
This was fixed in 693ec5a22e2c0224d4e52cef5aa7dbf1991af389. Can you confirm?

**Comment by zedee** [comment]
Yes, confirmed it was fixed.

**Comment by nWidart** [comment]
Thanks! 👍
