### ISSUE TITLE
Class Modules\Core\Contracts\Setting does not exist on asgardcms V2 when installing blog module

### ISSUE THREAD

**Issue by rexatgithub** [AsgardCms/Platform#306]
### Summary of issue
Hi i am using Asgardcms V2 works fine. But when i install BLOG module through 'composer require asgardcms/blog-module' i see this error Class Modules\Core\Contracts\Setting does not exist. 

### Steps to reproduce
1. Install asgardcms/blog-module
2. Login to backend

### System Details

- Operating System: Windows
- PHP Version: 5
- Laravel Version : 5.3
- `Asgardcms/Platform` version : v2

**Comment by rexatgithub** [comment]
Well i think i solved it. 

LatestPostComposer.php
instead of use Modules\Core\Contracts\Setting i change it to
use Modules\Setting\Contracts\Setting;

LatestPostsWidget.php
instead of use Modules\Core\Contracts\Setting i change it to
use Modules\Setting\Contracts\Setting;

SidebarExtender.php
instead of use Modules\Core\Contracts\Authentication; i change it to 
use Modules\User\Contracts\Authentication

But i am not sure if i did the right thing

**Comment by mikemand** [comment]
The Blog module has a v2.0.x-dev version (can be used in your `composer.json` as `"asgardcms/blog-module": "~2.0",`).
