### ISSUE TITLE
404 Not Found on fresh install on Windows IIS 10

### ISSUE THREAD

**Issue by PwrSrg** [AsgardCms/Platform#311]
### Summary of issue
I just installed AsgardCMS on Windows IIS and everything installed fine including the database.
But when I view it in the browser, it redirects to /en and gives me a 404 error.
All of my other Laravel sites work just fine.

### Steps to reproduce
Create fresh install on Windows w/IIS
View in browser

### System Details
Windows IIS 10
PHP 5.6.18
Composer 1.4-dev

**Comment by Apatrid** [comment]
May I suggest [Laragon](https://laragon.org/) for PHP/Laravel development on Windows? It works flawlessly.
