### ISSUE TITLE
Theme not working when config is cached

### ISSUE THREAD

**Issue by dulabs** [AsgardCms/Platform#316]
### Summary of issue

Theme not working when config is cached
I got `View [default] not found.`

### Steps to reproduce
`./artisan config:cache`

### System Details

- Operating System
`Windows 8`
- PHP Version
`5.6`
- Laravel Version
`5.3`
- `Asgardcms/Platform` version
`2.0-dev`

**Comment by nWidart** [comment]
This should posted on the https://github.com/floatingpointsoftware/stylist repository probably.

**Comment by dulabs** [comment]
Yes, it is [stylist issue](https://github.com/floatingpointsoftware/stylist/issues/24).
I added code below to boot service
```PHP
$stylist = $this->app['stylist'];
        $paths = $this->app['config']->get('stylist.themes.paths', []);

        foreach ($paths as $path) {
            $themePaths = $stylist->discover($path);
            $stylist->registerPaths($themePaths);
        }

        $theme = $this->app['config']->get('stylist.themes.activate', null);

        if (!is_null($theme)) {
            $stylist->activate($theme, true);
        }
```

**Comment by nWidart** [comment]
Interesting, and that fixed the config caching issue ? Might be worth sending in a PR to Stylist package. 

👍

**Comment by kirkbushell** [comment]
I'll have a fix and new version of Stylist out today guys.

**Comment by kirkbushell** [comment]
Thank you to @dulabs for identifying and resolving the issue.

**Comment by kirkbushell** [comment]
Done, and now using semver :P

**Comment by nWidart** [comment]
Awesome! 👍  Thanks.

**Comment by dulabs** [comment]
You're welcome and thanks for great package @kirkbushell :+1: 

@nWidart please update asgardcms.

**Comment by nWidart** [comment]
What is there to update ? You can run composer update in your project to get it.
