### ISSUE TITLE
Route not found when router is cached

### ISSUE THREAD

**Issue by dulabs** [AsgardCms/Platform#317]
### Summary of issue
Route not found when router is cached
Error `NotFoundHttpException in RouteCollection.php line 161:`

### Steps to reproduce
`./artisan route:cache`

### System Details

- Operating System
`Windows 8`
- PHP Version
`PHP 5.6`
- Laravel Version
`Laravel 5.3`
- `Asgardcms/Platform` version
`2.0-dev`

**Comment by nWidart** [comment]
Hello,

This has been an issue since route:cache was introduced. I think it's related to laravel-modules. 
Though I've never found the solution, or reason why. 
I'll close this unless you know more about this.

**Comment by a-h-abid** [comment]
hey @nWidart, 

While I was looking into the `route:cache` issue, I found that you blocked the Page module's frontend route when running php in CLI mode. [Here](https://github.com/Idavoll/Page/blob/6a9c48416d1a23fa0d80b172008507eba9bcdfe7/Http/frontendRoutes.php#L6)

Is there any reason why it is like this?? When I removed this `if` block, route:cache works.

**Comment by nWidart** [comment]
hmm that's interesting. If I remember the reason was for the tests to pass.
