### ISSUE TITLE
Module::asset not providing proper script template

### ISSUE THREAD

**Issue by gyan111** [AsgardCms/Platform#319]
### Summary of issue
Declaring module assets not providing proper script template rather it is giving the link only.

### Steps to reproduce
Define {{ Module::asset('blog:js/script.js') }} on any view file. (Published the module)

It gives a link like //localhost/tawlaravel/public/modules/blog/js/script.js
but it should produce whole script template like this:
<script type="text/javascript" src="//localhost/tawlaravel/public/modules/blog/js/script.js"></script>

### System Details

- Operating System: Ubuntu 16.04
- PHP Version: 7.0.18-1+deb.sury.org~xenial+1
- Laravel Version 5.2
- `Asgardcms/Platform` version 2.0

**Comment by gyan111** [comment]
Ok!
I think this is the basic feature.
https://nwidart.com/laravel-modules/v1/advanced-tools/facade-methods.

Closing this as it is not an issue. May help others if a newbie comes. But his feature should do this or we can add a flag or something to generate a whole script template or only link.

**Comment by gyan111** [comment]
Expecting some comments.

**Comment by nWidart** [comment]
This is expected behaviour.
