### ISSUE TITLE
Menu Module primary field?

### ISSUE THREAD

**Issue by arturmamedov** [AsgardCms/Platform#325]
### Summary of issue
In menu module there is a `primary` field `tinyInteger->default(0)` and in Validation Rules it must be unique, but in create-fields nor in translatable-create-fields it are set and in Repository create/update() it to not shown. What is the role of this field? In my opinion it not necessary and the name must be unique for call the menu in ::get('name')

### Steps to reproduce
Menu/Database/Migrations/create_menu ...
Menu/Resources/views/admin/menus/create.blade.php
Menu/Resources/views/admin/menus/edit.blade.php

### System Details
- Operating System Windows 10
- PHP Version 7.1.x
- Laravel Version 5.3.x
- `Asgardcms/Platform` version 2.x

**Comment by nWidart** [comment]
That columns is needed to set a default menu.
