### ISSUE TITLE
Settings module worng redirect

### ISSUE THREAD

**Issue by breadlesscode** [AsgardCms/Platform#329]
### Summary of issue
I have deleted the standard language and set a new default. (From English to German) and the next redirection is domain.xy/en/en/backend/setting/settings/core. There are both language keys in the URL.

### Steps to reproduce
- click on "x" from english
- add another language
- click save

### System Details

- Debian based OS (Deepin)
- PHP 7.1
- laravel/framework v5.4.26
- idavoll/setting-module 2.0.1

**Comment by nWidart** [comment]
Hello,

Hm this is a pretty edge case scenario that only happens once at the start of the project usually. Where the app is in English and suddenly there isn't an English language anymore.
Depending on what the underlying issue is, I'm not sure it's something urgent to fix.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
