### ISSUE TITLE
Tab header translation issue

### ISSUE THREAD

**Issue by riseno** [AsgardCms/Platform#332]
### Summary of issue
When the lang file doesn't have the key, the tab will only show the original key in the header instead of utilize translation module to show the value.

In file `form-tab-headers.blade.php` line 19.

So, should it utilize translation module?

**Comment by nWidart** [comment]
What do you mean by the original key? 

The translation module is always used when getting translations (for core modules at least). The translation module contains the translations of all core modules. If that translation does not exist, it will show the key `something::my-key`.

**Comment by riseno** [comment]
Like this,

![screen shot 2017-06-18 at 1 45 02 am](https://user-images.githubusercontent.com/14790405/27255030-cc827a64-53c7-11e7-852a-b1d5b05a8684.png)

**Comment by riseno** [comment]
For your more understanding, i made this changes as below

```php
<li class="{{ App::getLocale() == $locale ? 'active' : '' }} {{ $class }}">
            <a href="#tab_{{ $prefix.$i }}" data-toggle="tab">{{ app('translator')->get('core::core.tab.'. strtolower($language['name'])) }}</a>
</li>
```

**Comment by nWidart** [comment]
That's strange indeed as that key exists https://github.com/Idavoll/Translation/blob/2.0/Resources/lang/core/zh/core.php#L20 

Maybe the parenthesises are causing issues here? Could you try to remove those in the key that file ? For instance by using 

```
 'tab' => [
// ...
        'chinese-simplified' => '简体中文',
        'chinese-traditiona' => '繁体中文',
    ],
```

**Comment by nWidart** [comment]
Hm and that change made it work ? Before (pre-5.4) using `trans` would also use the custom translator class.

**Comment by riseno** [comment]
It did the thing well, but it just for `zh` which is simplified chinese.
https://github.com/Idavoll/Translation/blob/2.0/Resources/lang/core/zh/core.php#L20

But in here, it doesn't contain any key like `chinese (simplified)`, so it has no translated value for sure. (the screenshot i've uploaded that is in English locale)
https://github.com/Idavoll/Translation/blob/2.0/Resources/lang/core/en/core.php#L13

And i'm pretty sure that the parentheses will not be the problem on it. So, in this point of view, i would suggest to utilize `translator` for solve those lang files are not consistency issue.

**Comment by nWidart** [comment]
Ah I see, the `chinese (simplified)` key is not present in the English translation file. 

In that case that key should be added on the English file as well instead of using app('translator').

**Comment by riseno** [comment]
Just an idea for that, coz the CMS have `Translation` section, which listed out all the key of those lang files. 

And normal user might not be able to modify in programming level, that's why i suggest this solution.

**Comment by nWidart** [comment]
Noted, thanks. I personally prefer not using `app()` in views though.

**Comment by joshbrw** [comment]
View Composer that gives the current locale to every view would be preferable, such as `$currentLocale`

**Comment by nWidart** [comment]
there is already a helper for this `locale()`.

**Comment by joshbrw** [comment]
Is `locale()` not as bad as `app()`? :P

**Comment by nWidart** [comment]
No, it's refactorable. Either way this isn't related to the issue.

**Comment by riseno** [comment]
actually i created this issue that was trying to indicate that the translate module can be used over the application. 

As you can find all the translate keys in backend, n also be able to edit the text for different languages. But somehow its not being utilized in backend view(s). 

For my current situation, the backend is developed for different country's company, they have staffs from different countries all around the world. If i modify the lang file in coding level for each language, i'm definitely jumping off from the bridge.

**Comment by nWidart** [comment]
I don't see the issue. There is the UI for admins that want to edit translations via the UI.

**Comment by riseno** [comment]
i dig it in coding level, translation file is not being modified after user edit the text in backend for specific language. It just insert/update/delete the record in database only.

is that expected result? if not, then `There is the UI for admins that want to edit translations via the files.` is failed. 

Even translation file is modified, when the project is updated via `composer update` or using envoyer for deployment, all the lang files are gone for sure.

**Comment by nWidart** [comment]
It's not failed as it works.

The order is always

- Database
- File

So if the key is present in the database, it will have precedence. This is exactly for this reason of non technical people wanting to edit translations w/o of course having to open the files.

Composer update is irrelevant, not sure why you bring this up for the reason mentioned before. Keys in database have precedence.

**Comment by riseno** [comment]
Actually, as you say so, when i update the text in backend, i don't see any of the translation files is modified. you sure it works? 

And yes, it has a writer `TranslationsWriter` in the module, but i can't find any usage on it. No classes are calling this writer to do its job. 

So, base on that, would you mind to take a look on it?

**Comment by nWidart** [comment]
Indeed I see the issue. Must be since the laravel 5.4 upgrade, will look into it.

**Comment by nWidart** [comment]
Found the issue, and fixed it.

Pre 5.4 this worked
```
$translation = $this->model->whereKey($key)->with('translations')->first();
```
In 5.4 though, whereKey, equals to where('id.

**Comment by riseno** [comment]
Great, thanks for that. 

And yes, you're right, its exactly what i contributed on #331. 

But the problem remains, and i don't think that the key problem on it, its about the writer is not using in anywhere in the source code to tell it update the file.

**Comment by nWidart** [comment]
Oh I didn't even see it was you on the PR :P 

That's because the writer isn't used.

I'll close this now as the tag is in progress of being sent to all modules.
