### ISSUE TITLE
When I create a new user, login with the user just created in the media does not work

### ISSUE THREAD

**Issue by linhtinh92** [AsgardCms/Platform#335]

**Comment by nWidart** [comment]
I can't reproduce this locally.

What do you mean by media does not work? Make sure you have the appropriate permissions on disk.

**Comment by motchju** [comment]
I believe you have to create an API Keys for the new user

**Comment by linhtinh92** [comment]
https://www.screencast.com/t/OZIl3oRjo

this is video.

**Comment by nWidart** [comment]
The video required flash 😂 .

**Comment by motchju** [comment]
anyway it's a forbidden, due to lack of API key

**Comment by nWidart** [comment]
I see. This was fixed on the 2.0 branch if you want to use this currently.

**Comment by linhtinh92** [comment]
thanks all 👍
