### ISSUE TITLE
Convert Flatly and Adminlte themes to Laravel Mix

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#336]
Convert Flatly and Adminlte themes to Laravel Mix. They now use Laravel Elixir.

I'm not sure if the migration is easy.

**Comment by nWidart** [comment]
Maybe @motchju has an idea ? 💡:D

**Comment by motchju** [comment]
For Flatly please check https://github.com/AsgardCms/Platform/pull/339

Adminlte will follow soon

**Comment by motchju** [comment]
Update https://github.com/AsgardCms/Platform/pull/340 instead of https://github.com/AsgardCms/Platform/pull/339

**Comment by motchju** [comment]
check https://github.com/AsgardCms/Platform/pull/342

**Comment by nWidart** [comment]
With themes are updated to laravel mix thanks to @motchju ! 👍
