### ISSUE TITLE
User model not found when uploading media files

### ISSUE THREAD

**Issue by Mordeak** [AsgardCms/Platform#345]
### Summary of issue

Symfony\Component\Debug\Exception\FatalThrowableError Class '\App\User' not found 
    vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php:140 Illuminate\Auth\EloquentUserProvider::createModel
    vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php:106 Illuminate\Auth\EloquentUserProvider::retrieveByCredentials
    vendor/laravel/framework/src/Illuminate/Auth/TokenGuard.php:69 Illuminate\Auth\TokenGuard::user
    vendor/barryvdh/laravel-debugbar/src/DataCollector/MultiAuthCollector.php:73 Barryvdh\Debugbar\DataCollector\MultiAuthCollector::resolveUser
    vendor/barryvdh/laravel-debugbar/src/DataCollector/MultiAuthCollector.php:37 Barryvdh\Debugbar\DataCollector\MultiAuthCollector::collect
    vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php:769 Barryvdh\Debugbar\LaravelDebugbar::collect
    vendor/maximebf/debugbar/src/DebugBar/DebugBar.php:246 DebugBar\DebugBar::getData
    vendor/maximebf/debugbar/src/DebugBar/DebugBar.php:302 DebugBar\DebugBar::sendDataInHeaders
    vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php:674 Barryvdh\Debugbar\LaravelDebugbar::modifyResponse
    vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php:60 Barryvdh\Debugbar\Middleware\Debugbar::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:148 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:148 Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
    vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53 Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
    vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102 Illuminate\Pipeline\Pipeline::then
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151 Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
    vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116 Illuminate\Foundation\Http\Kernel::handle
    public/index.php:53 [main]

### Steps to reproduce

Upload a media file in media module.

### System Details

- Operating System: 4.10.0-26-generic #30-Ubuntu
- PHP Version: 7.0.18
- Laravel Version: 5.4
- `Asgardcms/Platform` version: 2.4.0

**Comment by nWidart** [comment]
Hello,

could you check in config/auth.php that you have the `providers.users.model` set to `Modules\User\Entities\Sentinel\User::class` ?

**Comment by Mordeak** [comment]
That has fixed the issue.
