### ISSUE TITLE
No image thumbnails in media overview and media edit page

### ISSUE THREAD

**Issue by Mordeak** [AsgardCms/Platform#346]
### Summary of issue

I get dead image links in the overview and image edit pages. storage path is /storage/media, folder exists and permissions are set correctly.

![no-thumbnails-media-index-page](https://user-images.githubusercontent.com/3075324/28163679-751edaec-67cc-11e7-81a7-1ba16c974a87.png)
![no-thumbnails-media-edit-page](https://user-images.githubusercontent.com/3075324/28163680-751f71b4-67cc-11e7-9299-a59ae2d582f4.png)

### System Details

- `Asgardcms/Platform` version: 2.4.0

**Comment by nWidart** [comment]
You need to configure config/filesystems.php and setup APP_URL in .env. Look at the platform repository for the filesystems file.

**Comment by Mordeak** [comment]
Had missing config in filesystems.php under local namely:

`'url' => env('APP_URL'),
'visibility' => 'public',`

after the permissions setting.

**Comment by nWidart** [comment]
Awesome 👍 

From the footer you posted earlier, you were on 2.0, you can update to 2.4 to get all these changes directly.
