### ISSUE TITLE
Extend EntityGenerator with Request files

### ISSUE THREAD

**Issue by kay899** [AsgardCms/Platform#347]
I would like to suggest to extend the EntityGenerator with also building the following files:
- Create"Entity"Request
- Update"Entity"Request

Then the Admin"Entity"Controller should take care of the Request files also.

If that would be ok to do, I would contribute the code for that.

Best wishes 

kay899

**Comment by nWidart** [comment]
hmm why not yes. With tests this would be good. 😄

**Comment by kay899** [comment]
I have coded it yesterday and WITH tests :-)

**Comment by kay899** [comment]
Code has been contributed:
https://github.com/AsgardCms/Platform/pull/350
