### ISSUE TITLE
Module permission not updating

### ISSUE THREAD

**Issue by nolafs** [AsgardCms/Platform#348]
Hi,

I am having trouble updating the permissions for one of my modules. I extended with a additional permission. The permission doesn't show up on the backend.

Previously I could fixed that by running composer autoload but for some reason on the live server it won't work. Any idea how I can refresh the permission list for the module?

Cheers
Olaf

**Comment by nWidart** [comment]
HI,

If you have caching enabled in your `.env` file, you need to clear the application cache using `php artisan cache:clear` command.

**Comment by nolafs** [comment]
Hi,

Thanks for the quick reply, yes, I am being clearing the cache but it has not effect what so ever. 

'services.treatments' => [
        'index',
        'create',
        'store',
        'edit',
       'edit_service',
        'update',
        'destroy',
	'continues'
    ],

edit_service and continues permission do not show up at all. The main administrator does have permission but I cannot sign the permission to admin role. 

Cheers
Olaf

**Comment by nWidart** [comment]
You must have some sort of cache somewhere. Maybe opcache.

Are these permissions in `permissions.php` ?

**Comment by nolafs** [comment]
Hi,

The server has not cache running. It only the part of the two permission that won't work. I had the same issue with a complete different module on my vagrant development platform but I could fix this by clearing the cache and running composer dumbautoload.

**Comment by nWidart** [comment]
I can't tell you what wrong then. Only to double check your environment.

**Comment by nolafs** [comment]
ok, thanks for your help.

**Comment by nolafs** [comment]
Even on my vagrant, asgard ignores any changes to the permissions.php. Nothing works, php artisan cache:clear. 

Anybody had same issue?

Cheers
Olaf

**Comment by joshbrw** [comment]
I've had general issues with Laravel's caching, but nothing specific with Asgard. Try deleting your cache directory, or if you're using a driver like redis/memcached, flush it

**Comment by nolafs** [comment]
I don't have any cache running at moment but I found out that I cannot add additional permission to a group. 

If I would add test to the blog post:
'blog.posts' => [
        'index',
        'create',
        'store',
        'edit',
        'update',
        'destroy',
	      'test'
    ],

Test permission won't show up at all. However if I would add a new group, no issue at all. They show up.

Any idea why?

Cheers
Olaf

**Comment by nWidart** [comment]
I could not replicate this. My new test permission is showing up.

Make sure you're editing the published file.

![image](https://user-images.githubusercontent.com/882397/28316374-e907778a-6bc2-11e7-9fcd-bb60366669ce.png)

**Comment by nolafs** [comment]
I have no idea myself. The server has no cache and even the workaround doesn't work. I get the permission but it won't update the views routes. Nothing works, clearing cache , clearing routes and restarting apache.

I am getting: Permission denied. (required permission: "services.treatments.continues") even when i have changed it to services.continues. :(

**Comment by nWidart** [comment]
> Make sure you're editing the published file.

**Comment by joshbrw** [comment]
Do a whole codebase search for `services.treatments.continues`

**Comment by nolafs** [comment]
Already did this, no record of it.

**Comment by nWidart** [comment]
Could take some time to answer my questions?

- https://github.com/AsgardCms/Platform/issues/348#issuecomment-316013888
- https://github.com/AsgardCms/Platform/issues/348#issuecomment-316044863

**Comment by nolafs** [comment]
Hi,

#348 - The server doesn't cache anything. No cache is installed on the server. Yes, all the permission are in the permissions are in permissions.php file for each module. I was able to add new permission groups.

 Adding new group works find on my vagrant setup and on the live server but the live server won't update the routes permission. I checked the routes with route:list which all seems perfectly fine. The route services.treatments.continues is not listed but the view still request this permission.

Cheers
Olaf

**Comment by nWidart** [comment]
I'll close this as it's an environment related issue.

My guess would be that you're not editing the published configuration file, but you're not responding to that.

**Comment by nolafs** [comment]
Ah, sorry. No I am not editing the publishing configuration file. I update my project via git.

**Comment by nolafs** [comment]
I just check it the file and you right, the permissions are not update.
