### ISSUE TITLE
[Illuminate\Contracts\Container\BindingResolutionException]

### ISSUE THREAD

**Issue by karneaud** [AsgardCms/Platform#360]
### Summary of issue
Cannot run php artisan route:list I keep getting and error
[Illuminate\Contracts\Container\BindingResolutionException]
  Target [Modules\Translation\Repositories\TranslationRepository] is not instantiable while building [Modules\Translation\Http\Controllers\Api\TranslationController].
### Steps to reproduce
run `composer create-project asgardcms/platform your-project-name`
run `php artisan asgard:install`
run `php artisan asgard:module:scaffold`
run `php route:list`
### System Details

- Vagrant Homestead
- PHP PHP 7.1.3-3+deb.sury.org~xenial+1
- Laravel 5.4.30
- `Asgardcms/Platform`  2.5.1

**Comment by nWidart** [comment]
Hi,

Thanks for bringing this up. I think this must have been introduced in this commit https://github.com/AsgardCms/Platform/commit/e0a616b2f978de46845c105c437fb78035eb1602 which was a PR by @MehediDracula

**Comment by nWidart** [comment]
This was fixed in 2.5.2.
