### ISSUE TITLE
localizationRedirect web redirects on post routes

### ISSUE THREAD

**Issue by karneaud** [AsgardCms/Platform#361]
### Summary of issue

when using the middleware
> 'middleware' => ['localizationRedirect', 'web'],
any route gets redirected to the locale prefixed version of the application. This does not fair well with post route methods as you cannot pass on post data. This causes the application to error out or redirect o a default route. Disabling the middle where seems to rectify the issue

### Steps to reproduce
create a post route 
send post data to route
### System Details

- Operating System - Vagrant Homestead
- PHP Version - 7
- Laravel Version - 5.4.30
- `Asgardcms/Platform` version - 2.5.1

**Comment by nWidart** [comment]
that's not that middleware. I can use post without issues.

**Comment by karneaud** [comment]
Well this is strange. I'm running into this problem and disabling the middleware resolves the issue

**Comment by nWidart** [comment]
Hm strange indeed. Probably worth asking on the package itself in that case https://github.com/mcamara/laravel-localization

**Comment by jimmitjoo** [comment]
I am having this issue as well when working against the api in a SPA, but it does not occur when working in postman.
