### ISSUE TITLE
Installation instructions missing step

### ISSUE THREAD

**Issue by wowcut** [AsgardCms/Platform#362]
Currently the [installation instructions](https://asgardcms.com/docs/v2/getting-started/installation) will lead to this error what could be a very frustrating experience for newbies:
```
-> php artisan asgard:install
Could not open input file: artisan
```
This happens because there is no instruction to change into the directory that was created with the ```asgardcms``` command. To fix it add one sentence as the first sentence of the "Run the install command" paragraph: 

_Now change (cd) into the generated directory._

**Comment by nWidart** [comment]
Good point! Will change that. Thanks for bringing it up.

**Comment by nWidart** [comment]
I just added the missing step.

Thanks again.
