### ISSUE TITLE
Issue with fresh installation of asgardcms 1.0

### ISSUE THREAD

**Issue by naveenv1985** [AsgardCms/Platform#365]
Hi, Could you please take a look at the below issue and let me know why its not working now while the same was working fine few months back.

### Summary of issue
When running a fresh installation of asgard 1.0 getting errors and installation is not complete. Errors are as below:
1. Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsers" was found.
2.PHP Notice:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128'.
3. [Symfony\Component\Console\Exception\RuntimeException]  - Script php artisan module:migrate handling the post-update-cmd event returned with error code 1.
4. Run php artisan asgard:install. You get an Error: No user driver was installed. Please check the presence of a Service Provider after the db is successfully configured and system begins "User Module
Starting the User Module setup... "

### Steps to reproduce
composer create-project asgardcms/platform=1.0 <project-name>
php artisan asgard:install

### System Details

- Operating System - Mac OS Sierra Version 10.12.6
- PHP Version - 5.6.31
- Laravel Version - 5.1.46 (LTS)
- `Asgardcms/Platform` version - 1.0
![screen shot 2017-08-21 at 1 55 28 pm](https://user-images.githubusercontent.com/28868843/29505383-91843bb2-8678-11e7-8e83-be2ac10ca684.png)
![screen shot 2017-08-21 at 1 56 20 pm](https://user-images.githubusercontent.com/28868843/29505384-9199f3da-8678-11e7-87d1-cea47ec874d3.png)

**Comment by abidhussainsafi** [comment]
same problem when i installing using mysql database.

**Comment by abidhussainsafi** [comment]
<img width="1052" alt="screen shot 2017-08-21 at 10 42 23 am" src="https://user-images.githubusercontent.com/16850191/29506579-784916e2-865d-11e7-9197-c79d4173cd2e.png">

**Comment by nWidart** [comment]
That means laravel isn't able to connect to your database. Make sure your credentials are correct. If you're using a VM (vagrant/docker) make sure you're inside the vm when running the install command.

Also, note that installing 1.0 isn't a good idea since 2.0 is released.

**Comment by naveenv1985** [comment]
@nWidart, since im using an existing project which runs on asgardcms 1.0, im trying out the new installation coz there are code setup issues with the project now as it is tied to some custom repository who had worked on this project before. If i can do a fresh installation then the dependencies could be updated and can continue to use the same same codebase. Could you please let me know the issues with 1.0 installation?

**Comment by nWidart** [comment]
1.0 isn't supported anymore. You can still find the cause of the issue by looking at the installation command, more specifically in the user part.

**Comment by naveenv1985** [comment]
Even if 1.0 is not supported, do we have a fully working installation for it which does not have above issues?

**Comment by nWidart** [comment]
Since you're having those issues, I think it's pretty clear answer.

**Comment by naveenv1985** [comment]
Thank you @nWidart
