### ISSUE TITLE
when module is inactive throw exception

### ISSUE THREAD

**Issue by miadz** [AsgardCms/Platform#368]
### Summary of issue
when module is inactive throw exception but other module need it 
for example i disable media module (i know that is a core module) , then i get error on view or route not found.

### System Details

- Operating System
- PHP Version 7
- Laravel Version 5.4
- `Asgardcms/Platform` version 2.5.2

**Comment by nWidart** [comment]
Did you disable the media module via the GUI on the backend? If so it's a bug, and shouldn't happen.

**Comment by miadz** [comment]
Yes, I change core config then try disable by GUI, now i change all to default and working like a charm.

I have another question
why this lines isn't at every module
$this->publishes([
    __DIR__ . '/../Resources/views' => base_path('resources/views/asgard/user'),
]);

because i want create new backend theme,
and need to publish all scaffold view to resource then (for now) move to my theme folder for editing.
i think be good if theme scaffold builder publish all module view to new theme folder.

at last ,
I your  like your asgard structure , but i think a dynamic form generator (symphony or kris form builder) and datatable builder (yajra) can be very useful because when someone create new theme or module don't need change every form field or create index view for every .also form and index b more dynamic for easy and fast change ,this two package behind of module scaffold builder be lovely, or maybe i am lazy 😄

**Comment by nWidart** [comment]
That how laravel works. It needs that to load views.

You're absoletly free to use the laravel datatables package. I use it on pretty much every project.
