### ISSUE TITLE
partials and theme path

### ISSUE THREAD

**Issue by truongphitam** [AsgardCms/Platform#371]
### Summary of issue
It error when i settup cms for document
### Steps to reproduce
composer create-project asgardcms/platform your-project-name

php artisan asgard:install

### System Details

- Operating System
- PHP Version: 5.6.30
- Laravel Version 5.4
- `Asgardcms/Platform` version 2

![1](https://user-images.githubusercontent.com/8310451/30162290-778f6f9a-93fe-11e7-9e7b-fc850bf988eb.PNG)
![2](https://user-images.githubusercontent.com/8310451/30162291-7792cd84-93fe-11e7-9a22-aa843c7655f5.PNG)

**Comment by nWidart** [comment]
Did the installation go without errors?

**Comment by truongphitam** [comment]
Yes 

i setup for https://asgardcms.com/install

**Comment by nWidart** [comment]
Something must have gone wrong with the installation.

**Comment by nWidart** [comment]
The video does not ask you to install laravel first. I can't reproduce your issue so make sure you follow the instructions.
