### ISSUE TITLE
I don't have the menu on my home page 

### ISSUE THREAD

**Issue by fredmj** [AsgardCms/Platform#373]
### Summary of issue
I can't see sidebar menu.

### Steps to reproduce
* Install laravel5 via `composer`
* Install asgardcms from github repo with `git clone`
* add a menu in the 'menu management' subsection of the admin backend
* Edit the menu and create severals `menu items` under `root`

### System Details

- Operating System : CentOS7.3 on virtualbox5.1.26
- PHP Version 7.1
- Laravel 5.5
- `Asgardcms/Platform` 2.5.2

**Comment by nWidart** [comment]
It looks like you didn't install asgardcms as needed.

You don't need to install laravel. Instead run the composer create-project command directly with asgardcms, as provided in the documentation.

**Comment by fredmj** [comment]
Well I've give a try again following *exactly* the doc but I can't see the Menu.
Here what I have made :

> 
>   285  mysql -u root -p **## to create database and give user privileges on**
>   286  composer create-project asgardcms/platform fmjconsultingv2 **## v2 for asgradv2.6.1
>   287  cd fmjconsultingv2/
>   288  vi /etc/httpd/conf/httpd.conf **## to point to the right DocumentRoot
>   290  php artisan asgard:install
>   ...
>   296  chown -R apache:apache fmjconsultingv2/
>   297  systemctl restart httpd.service

Here the page :
![asgardcms_where_is_the_menu](https://user-images.githubusercontent.com/8500020/30366123-5264b020-986a-11e7-9fa6-3a153eb0c281.png)

Here the menu I have created from the backend :
![asgardcms_adminmenu_creation](https://user-images.githubusercontent.com/8500020/30366231-b01cce28-986a-11e7-87c6-6677a8980ab1.png)

I don't see what I miss.
Is the menu's colors are the same as the background ?

**Comment by nWidart** [comment]
Hm that's seems correct. Did you set the "Blog" menu item as online as well?

**Comment by fredmj** [comment]
Yes I've done that :
![capture d ecran de 2017-09-13 10-43-07](https://user-images.githubusercontent.com/8500020/30368107-7603c8c6-9870-11e7-88f5-2fd58ceff9ce.png)

May I have to write in `app.js` or something a line like : 
````
{!! Menu::get('MyMenu') !!}

````
?

**Comment by nWidart** [comment]
App.js doesn't need anything for menus. However your frontend template does.
I assume you called `{!! Menu::get('MainMenu') !!}` in your theme?

**Comment by fredmj** [comment]
Ooops.
No I didn't. I guess I have to read the documentation *:shame_on_me*
I don't know precisely where I have to add that line ...

**Comment by nWidart** [comment]
No worries. :)
You can add it where you want the menu to show. Usually, this would be in the top nav bar for instance.

**Comment by fredmj** [comment]
Well, **Thank you** Nicolas for the help on **my** mistake.
I don't really know where is the top nav bar.
I guess I have to read and train myself much more with Laravel to figure out this sort of 'basics'.

For the moment I have added the `{!! Menu::get('MenuName') !!}` in the `<installation_folder>/Themes/Flatly/views/layouts/master.blade.php` file
like that :
```
[...]
<body>
        {!! Menu::get('Blog') !!}
        {!! Menu::get('Services') !!}

@include('partials.navigation')
[...]
```
I don't know if it's a best practice, but it give me a result.
![capture d ecran de 2017-09-13 13-20-33](https://user-images.githubusercontent.com/8500020/30375133-bc5b2014-9887-11e7-99c3-a7ed99661ae9.png)

Next I'll play a bit with all the stuff.
Thank you again.
Fred.

**Comment by nWidart** [comment]
No worries, glad I could help. 👍

**Comment by luchiniii** [comment]
Really? You need no add that code for every single menu item?. I give it a try, And in the last version It seems doesn't work
