### ISSUE TITLE
Fresh installation NotFoundHttpException

### ISSUE THREAD

**Issue by maguilar92** [AsgardCms/Platform#375]
### Summary of issue
After install asgardcms and execute command all pages return NotFoundException.

### Steps to reproduce

Install asgardcms.

Execute command:
`php artisan clear-compiled && php artisan view:clear && php artisan route:clear && php artisan config:clear && php artisan debugbar:clear && composer dump && php artisan route:cache && php artisan config:cache"`

### System Details

- Operating System MacOS Sierra 10.12.6
- PHP Version 7.1.1
- Laravel Version 5.4.36
- `Asgardcms/Platform` version 2.1

**Comment by nWidart** [comment]
Hello,

I can't reproduce this on the latest version, 2.6. Could you try with that one?

**Comment by maguilar92** [comment]
I tried in 2.6 version an same error. I'm using MAMP 4.1.1 with predis 1.1.* for:

CACHE_DRIVER=redis
TRANSLATIONS_CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_DRIVER=redis

<img width="1392" alt="captura de pantalla 2017-09-17 a las 9 32 14" src="https://user-images.githubusercontent.com/25102127/30518936-1f93ba6e-9b8b-11e7-887d-7ae1a30edd18.png">

In another website working only with laravel modules this command works but with asgardcms break routes without changes on git repository:
<img width="326" alt="captura de pantalla 2017-09-17 a las 9 33 02" src="https://user-images.githubusercontent.com/25102127/30518939-3b72a5d8-9b8b-11e7-86bf-a2d99737480f.png">

**Comment by maguilar92** [comment]
I checked exiting routes in Router.php and routes exists.

<img width="700" alt="captura de pantalla 2017-09-17 a las 9 36 46" src="https://user-images.githubusercontent.com/25102127/30518972-d5402690-9b8b-11e7-923d-add2f22d418d.png">

**Comment by maguilar92** [comment]
Doing test I check that command route:cache break routes and doing route:clear routes works but generate another error:

<img width="902" alt="captura de pantalla 2017-09-17 a las 9 47 22" src="https://user-images.githubusercontent.com/25102127/30519057-5e681288-9b8d-11e7-9892-0779f023c8de.png">

**Comment by maguilar92** [comment]
After delete bootstrap/cache/routes.php and bootstrap/cache/config.php asgardcms works:

<img width="837" alt="captura de pantalla 2017-09-17 a las 9 57 20" src="https://user-images.githubusercontent.com/25102127/30519118-9ed54c2c-9b8e-11e7-8356-0618b5f25095.png">

**Comment by nWidart** [comment]
Aha ok I didn't see you ran route:cace in you first post.

Indeed route:cache does not work in asgardcms.
