### ISSUE TITLE
Redirecting to http://localhost/en/auth/login.

### ISSUE THREAD

**Issue by maguilar92** [AsgardCms/Platform#376]
### Summary of issue
I installed fresh asgardcms and when I go to login always redirect me to /auth/login

### Steps to reproduce
Install asgardcms 3
Run installer
Login to backend

### System Details

- Operating System macOS Sierra 10.12.6
- PHP Version 7.1.1
- Laravel Version 5.5.5
- `Asgardcms/Platform` version 3

**Comment by JulienTant** [comment]
What are you using to run AsgardCMS ? (MAMP, homestead, valet, docker ? ...)

**Comment by maguilar92** [comment]
I'm using MAMP

**Comment by nWidart** [comment]
Sadly MAMP is incompatible with v3 & laravel 5.5.

**Comment by nWidart** [comment]
You can view this new video on how to install asgardcms with docker. https://www.youtube.com/watch?v=uZo5BHbv_lY

**Comment by maguilar92** [comment]
Thanks :)
