### ISSUE TITLE
Uncaught TypeError: this.spawn_widget is not a function

### ISSUE THREAD

**Issue by maguilar92** [AsgardCms/Platform#378]
### Summary of issue
Dashboard widgets not displaying.
Uncaught TypeError: this.spawn_widget is not a function on:
/Modules/Dashboard/Resources/views/admin/dashboard.blade.php on line 70 **this.spawn_widget(node);**

### Steps to reproduce
Install Blog module
Go to dashboard
Check developer tools console

### System Details

- Operating System macOS Sierra 10.12.6
- PHP Version 7.0.23-1+ubuntu16.04.1+deb.sury.org+1
- Laravel Version 5.5.5
- `Asgardcms/Platform` version 3.0.2

**Comment by nWidart** [comment]
Hello,

Blog module has not yet been upgraded to asgard v3.
Though the error seems strange.

I'd welcome you to submit a PR to make the blog work on v3. 😄

**Comment by maguilar92** [comment]
I will look to update blog module but the error is generated in the dashboard javascript with widgets.

**Comment by nWidart** [comment]
Yes, because the blog module has widgets.

**Comment by maguilar92** [comment]
@nWidart I has make update to work with Asgardcms 3.

I checked Widgets and all seems work.

**Comment by maguilar92** [comment]
The error continue :(

**Comment by nWidart** [comment]
Hm odd I'll try to take a look at it asap. 

The current widget system will be replaced though so not sure if it's worth spending too much time on it if it's something complex.

**Comment by maguilar92** [comment]
The Widgets are created as: https://asgardcms.com/docs/v3/dashboard-module/widgets

**Comment by maguilar92** [comment]
Thanks for everything

**Comment by maguilar92** [comment]
It seems to be what you say because in version 2 it worked correctly
