### ISSUE TITLE
Multi Auth Support

### ISSUE THREAD

**Issue by uwascan** [AsgardCms/Platform#387]
### Summary of issue
Does Asgard Cms support Multi Auth? I have a requirement for two or more user types that should be able to Login through the frontend

- Operating System
- PHP Version 7.1
- Laravel Version 5.5
- `Asgardcms/Platform` version 3.0

**Comment by nWidart** [comment]
Hello,

Not sure I follow what you mean by multi-auth. However, you can have roles to indicate multiple user types.
You could also use laravel's auth guards.

**Comment by uwascan** [comment]
I have different classes of users for my web app (Lenders and Borrowers for example). I want to separate  their info (Registration data) into different tables and Entities and support Logging in with theses entities instead of a Single User Entity.  I need to create multiple user types for my app, with individual registration and login pages.
Originally I started by creating a role entry in the database, but the application has outgrown this and I need to store different user data.
Any Guidance?

https://github.com/Hesto/multi-auth
https://laracasts.com/discuss/channels/laravel/multi-auth-example
http://www.expertphp.in/article/how-to-implement-multi-auth-in-laravel-5-4-with-example

Will the ideas in the above links workwith Asgard?

**Comment by nWidart** [comment]
That's totally possible yes.
I had a recent project with a similar need, where I have other classes extending the User entity to create different types of users. 
Each user type had a completely different backend UI.

You will have to customise the User module, but that's not difficult to do.

**Comment by uwascan** [comment]
Thanks I will try it out

**Comment by nWidart** [comment]
I'll close this as it's related to your use-case. 😄
