### ISSUE TITLE
 Media Multiple Select

### ISSUE THREAD

**Issue by bajki** [AsgardCms/Platform#388]
Is there an option to select multiple images?

**Comment by nWidart** [comment]
Yes, that's explained here: https://asgardcms.com/docs/v3/media-module/linking-media-to-entities

```php
@mediaMultiple('gallery')
```

**Comment by bajki** [comment]
Yeah but like this                             
<single-media zone="image" @singleFileSelected="selectSingleFile($event, 'page')" entity="Modules\Page\Entities\Page" :entity-id="page.id"></single-media>

**Comment by nWidart** [comment]
Ah you were talking about the vuejs integration. No the multiple select is not done yet for vuejs integration.

**Comment by LukaszNiziol** [comment]
When can I you expect an update?

**Comment by nWidart** [comment]
Not anytime soon. You can still implement it yourself though. 😄
