### ISSUE TITLE
No validation and exception when adding role

### ISSUE THREAD

**Issue by blendsoft** [AsgardCms/Platform#389]
### Summary of issue
No validation and exception when adding role

### Steps to reproduce
Try to add second admin role

### System Details

Asgard 3.0.2

**Comment by nWidart** [comment]
You mean a unique role name? That's a good idea.

**Comment by nWidart** [comment]
Thank you for the suggestion, [fix has been applied](https://github.com/AsgardCms/Platform/commit/663bac77d7873602f9813177db3ed0f55adca5e3), targetted at 3.1.
