### ISSUE TITLE
Can't add module in subdirectory

### ISSUE THREAD

**Issue by blendsoft** [AsgardCms/Platform#395]
### Summary of issue
Cant create module in other directory than default

### Steps to reproduce
I made module in Modules/Moonbite/MoonUsers
with module.json

``
{
    "name": "MoonUser",
    "alias": "moonuser",
    "active": 1,
    "order": 1,
    "providers": [
        "Modules\\Moonbite\\MoonUser\\Providers\\RouteServiceProvider"
    ],
    "aliases": {
    },
    "files": [
    ]
}
``
and config:
`
'scan' => [
        'enabled' => true,
        'paths' => [
            //base_path('vendor/*/*'),
            base_path('Modules/Moonbite/*'),
        ],
    ],

`
Now I can't start
`
php ./artisan serve
                                                           
[Illuminate\Contracts\Filesystem\FileNotFoundException]  
File does not exist at path /module.json        
`

`
but when I disable module cache:
 'cache' => [
        'enabled' => false,
        'key' => 'laravel-modules',
        'lifetime' => 60,
    ],
`
it works

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
This isn't related to AsgardCMS. Please submit your issue to the relevant package, laravel-modules.
