### ISSUE TITLE
Page Status Colours Not Colour Blind Friendly

### ISSUE THREAD

**Issue by moebrowne** [AsgardCms/Platform#407]
### Summary of issue

The red and green dots used to show the status of a Page are quite close together. Here is what the page index looks like to someone with Protanopia:

![index](https://user-images.githubusercontent.com/8448512/31299583-f35625a2-aae6-11e7-8adf-d768d193cf28.png)

See https://www.toptal.com/designers/colorfilter for a really good tester for these kinds of things

**Comment by moebrowne** [comment]
Probably should've added (and spoiler alert) the first page is disabled:

https://www.toptal.com/designers/colorfilter?orig_uri=https://www.mountainofcode.co.uk/asgard-colour-test.html&process_type=protan

**Comment by nWidart** [comment]
Hopefully this is better:
![image](https://user-images.githubusercontent.com/882397/31306528-5e5f7306-ab52-11e7-8c52-24732e4ae6f5.png)

**Comment by moebrowne** [comment]
Looks better:

![index](https://user-images.githubusercontent.com/8448512/31307597-901562fe-ab5f-11e7-9a78-ddf300dcd914.png)

What do you think @joestrong ?

**Comment by joestrong** [comment]
It's certainly better, but it's still an issue for me. Could we have an icon as well, or text?

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

Or send a PR for an even better compatibility 😄
