### ISSUE TITLE
Translations Can't Be Updated

### ISSUE THREAD

**Issue by moebrowne** [AsgardCms/Platform#408]
### Summary of issue

If one or more translations are enabled and you try to edit one of them it fails

### Steps to reproduce

- Enable En & Ja translations
- Create a page with En and Ja content
- Try to edit the new page
- Error as follows:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'status' cannot be null (SQL: insert into `page__page_translations` (`locale`, `page_id`, `title`, `slug`, `status`, `body`, `meta_title`, `meta_description`, `og_title`, `og_description`, `og_image`, `og_type`, `updated_at`, `created_at`) values (ja, 1, JP, jp, , <p>content jp</p>, , , , , , , 2017-10-06 22:57:32, 2017-10-06 22:57:32))
```

This is the translation part of the POST request:

![screenshot from 2017-10-07 00 01 10](https://user-images.githubusercontent.com/8448512/31301610-1b5d38c2-aaf3-11e7-9da6-b83b09e1fd4c.png)

Note that `page_id` and `status` are null for Ja

**Comment by nWidart** [comment]
I just worked on fixing an issue with the `Indonasian` locale and I could save its translations. Could you make sure the issue is still present on `3.0` branch too?

**Comment by nWidart** [comment]
This was tagged.

**Comment by moebrowne** [comment]
@nWidart I can confirm this issue has been fixed

**Comment by nWidart** [comment]
Awesome! 👍
