### ISSUE TITLE
CKEditor configuration/bug - content not posting after editing from the source

### ISSUE THREAD

**Issue by mdcass** [AsgardCms/Platform#413]
### Summary of issue

After editing the source of a page within CKEditor and clicking save (without navigating anywhere else within the editor), the new contents are not **POST**ed.

### Expected behaviour

Editing using the source view of the CKEditor should POST the edited contents - not the seemingly unchanged WYSIWYG view contents.

### Steps to reproduce

* Head to page edit
* Select the `Source` toolbar option in the CKEditor
* Edit something in the page
* Select the primary `Save` button on the page
* See the change has not been applied

#### Steps to workaround

Follow the above steps, but before hitting the primary `Save` button, toggle the `Source` button back to the WYSIWYG view, then toggle again back to the source edit view. The expected content is now POSTed.

#### Research

A [Drupal Issue](https://www.drupal.org/node/1606596) (solution [#9](https://www.drupal.org/node/1606596#comment-8399883)) points to a solution setting the `CKEDITOR.config.allowedContent` option to `true` however this is already done in `public/themes/adminlte/js/vendor/ckeditor/config.js:39`

### System Details

- Ubuntu 16.04 (Laravel Homestead 6.3 running on Windows 10 Host)
- PHP Version 7.1.7
- Laravel Version 5.5
- `Asgardcms/Platform` 3.0

**Comment by nWidart** [comment]
Hello,

I've created your issue on the CkEditor component which is responsible for this.

https://github.com/dangvanthanh/vue-ckeditor2/issues/48

**Comment by mdcass** [comment]
Closing as issue resides with the Vue Component for CkEditor
