### ISSUE TITLE
cURL error 60

### ISSUE THREAD

**Issue by Rotho98** [AsgardCms/Platform#414]
### Summary of issue
When Using Composer to install modules I get the following error 

> cURL error 60: SSL certifacate problem: unable to get local issuer certificate

### System Details

- Operating System - Windows 10
- PHP Version - 7 
- Laravel Version - 5.5.0
- `Asgardcms/Platform` version - latest

**Comment by nWidart** [comment]
Hello,

This seems to be an issue on your end, I can't reproduce this.
Make sure composer is installed/configured correctly maybe.
