### ISSUE TITLE
View not found

### ISSUE THREAD

**Issue by root-zero** [AsgardCms/Platform#415]
### Summary of issue

The cms frontend as well as the backend stopped working after i ran these commands in command line.
php artisan view:clear
php artisan config:cache
composer dump-autoload

The frontend (website) show this error
---------------------------------------
(1/1) InvalidArgumentException
View [default] not found.
---------------------------------------

and the backend show this error
------------------------------------
(2/2) ErrorException
View [layouts.master] not found.
------------------------------------

### Steps to reproduce

run these command from the command line
php artisan view:clear
php artisan config:cache
composer dump-autoload

### System Details

- Operating System: Windows 10 Professional version 1703
- PHP Version: 5.6.25
- Laravel Version: 5.4.36
- `Asgardcms/Platform` version:  3

**Comment by nWidart** [comment]
You can't use config cache in asardcms.

**Comment by root-zero** [comment]
so what should i do now?

**Comment by nWidart** [comment]
Just don't use the config cache command.
Clear the config cache now...

**Comment by root-zero** [comment]
already cleared the config cache, the website stopped working
![untitled](https://user-images.githubusercontent.com/32862022/31651941-eaf6134c-b336-11e7-8089-8a6ba2fb8b1c.png)

**Comment by nWidart** [comment]
That means it's not cleared. You can see to remove the cached config files in laravel. I don't remember where exactly it's stored.

**Comment by root-zero** [comment]
i have tried both of these commands
php artisan config:cache
php artisan cache:clear

**Comment by nWidart** [comment]
Or:

> You can see to remove the cached config files in laravel.

**Comment by root-zero** [comment]
problem solved. thanks.
this command worked
php artisan config:clear
