### ISSUE TITLE
Asgard custom module creation issue

### ISSUE THREAD

**Issue by namitasurve177** [AsgardCms/Platform#420]
### Summary of issue

Steps to reproduce: im the issues when i created new custom module projects its not visible in admin panel and rest migrations files too missing.whether module not successfully not created or is there something else i need to do.

**Comment by nWidart** [comment]
Hello,

It's not visible because you don't have the permissions possibly.
Migrations files are only created if you entered one or more entity names.

**Comment by namitasurve177** [comment]
how can i get the permission for that newly created module and what entity names need to be given while creation?

**Comment by nWidart** [comment]
By given you the permissions via the admin users/roles.
The entities you need.

**Comment by namitasurve177** [comment]
i cant see that custom module in admin -> roles list too

**Comment by nWidart** [comment]
Open the config/permissions file in your module, to see if there are some.
If you didn't generate entities, you obviously won't have any.

**Comment by namitasurve177** [comment]
that file is empty

**Comment by namitasurve177** [comment]
after successfully creating module while inserting data in module it gives me error like Undefined property: Modules\Projects\Entities\Testimonial::$translatedAttributes.i cant create data inside that module what steps did i miss?
