### ISSUE TITLE
Media Module can not add new folder!

### ISSUE THREAD

**Issue by zhousak** [AsgardCms/Platform#424]
### Summary of issue
there is no place to input folder name...

### Steps to reproduce
install, no other steps 

### System Details

- Chrome 62.0.3202.75
- Operating System: ubuntu16.04.1
- PHP Version:7.1.7
- Laravel Version: 5.5
- `Asgardcms/Platform` version 3.2.1
<img width="1208" alt="2017-10-31 1 00 52" src="https://user-images.githubusercontent.com/2068588/32184585-98ca7594-bdd7-11e7-9bbf-75667cf6e4b8.png">

**Comment by nWidart** [comment]
Hello,

This is due to element-ui 2.0, revert back to 1.x or you can use the master branch which has the fix for it.
Will tag tomorrow.

**Comment by zhousak** [comment]
Thanks a lot. I use the 3.0-master branch and fix it.

**Comment by nWidart** [comment]
This has been tagged as [`3.3.0`](https://github.com/AsgardCms/Platform/releases/tag/3.3.0)
