### ISSUE TITLE
asgardcms while linking media to entity

### ISSUE THREAD

**Issue by namitasurve177** [AsgardCms/Platform#426]
while linking media module to object im getting this error when i add use \Modules\Media\Support\Traits\MediaRelation. first it was giving error for media relation then i put slash before modules and now it is giving error as below.
Class Modules\Projects\Http\Controllers\Admin\FileRepository does not exist

**Comment by nWidart** [comment]
Hello,

I can't reproduce this. Make sure you're using those classes and import correctly.
