### ISSUE TITLE
Menu doesn't appear in template

### ISSUE THREAD

**Issue by seanthepottingshed** [AsgardCms/Platform#43]
Followed instructions here:

https://asgardcms.com/en/docs/menu-module/managing-menus

Menu is referenced in ```views/partials/navigation.blade.php``` as the default  ```{!! Menu::get('main') !!}``` and menu added as per below:
 
![screen shot 2015-06-09 at 11 11 06](https://cloud.githubusercontent.com/assets/12046965/8055558/4969c7de-0e98-11e5-8528-4f392dd007c7.png)

...however menu fails to appear in front end.

**Comment by Thorazine** [comment]
I fairly certain this is related.

I found that when:
- English is not the main language.
- you create a new menu

The first item in the menu builder stays empty (no name, no options). There is no record created in menu__menuitem_translations. When the default is english it does get created.

When the said item is not found in the db, the frontend Menu::get() function returns a presenter with an empty menu. 

Workaround I use for now: 
- make the default english. 
- create your menus 
- switch back

Al is functional when adding items (as far as I know)

**Comment by nWidart** [comment]
This is because the first item is called 'root', not sure this is related.

**Comment by Thorazine** [comment]
If your main language is not english (in our case dutch) the menu breaks. Even if you call it root.

**Comment by nWidart** [comment]
Yes, it's absolutely not the best implementation. Currently thinking of a better way of handling this root item creation, instead of hardcoding English, using the active languages.

Shouldn't be too hard to implement, I'm curious to see if this will fix this issue.

**Comment by nWidart** [comment]
I've pushed this change in the [1.7](https://github.com/AsgardCms/Menu/releases/tag/1.7.0) tag, please update and let me know if this fixes this issue.

Thank you,

**Comment by Thorazine** [comment]
The Menu::get and Menu::all both return null in the 1.7 for me. They return empty in english now too

**Comment by nWidart** [comment]
Hm, strange, if you look into the database, in the menu items table, you should see the root item translated for all active languages.

Strangely enough, I can still get the main menu locally.

**Comment by Thorazine** [comment]
In the database it seems alright. Im requesting by the entered name, just no data.
Just switched to the 1.7 menu, but no change in result.

**Comment by nWidart** [comment]
Are you sure you menu is online in all the languages , as well as the menu items ?

**Comment by Thorazine** [comment]
Ah, excuse. it was indeed not online. Now its not null, but it has no data in it (there is in the menu in that language, but no html output except the bootstrap nav div). 

Switching back to english: "root" or any other name you called the menu is empty. With that obviously no db entry for that language, which is why it's empty.

**Comment by nWidart** [comment]
Alright so sounds like it's working like intended.
If all the menu items (or just the ones you want to display), are online they will show up.

**Comment by Thorazine** [comment]
well, the menu div shows, not the menu items.
When requesting Menu::all(), the items array is empty.

**Comment by nWidart** [comment]
Again, you menu items need to be online.

**Comment by Thorazine** [comment]
Ah, not only the menu, but the individual items too. Check.
Thanks!

**Comment by nWidart** [comment]
Awesome! :smile:

**Comment by koppenhoefer** [comment]
Umm,... I'm coming to the discussion more than 1year later,.. and unsuccessful (N00b that I am).
I've created my menu (in AsgardCMSv2), calling it 'main', aok. I think to understand that I should add the code '{!! Menu::get('main') !!}' to views/partials/navigation.blade.php (not sure where,.. but everywhere I try has no effect). 

So was there ever an answer to seanthepottingshed 's question?

**Comment by bchellingworth** [comment]
Just for anyone still having issues with this, I had the same problem and although I had ticked the checkbox for the menu to be online, there is also a checkbox for each menu item to be online, which I had not ticked.

Ticking all of the menu items as online as well as the menu itself solved the problem.
