### ISSUE TITLE
User Profile data not show inputs for edit

### ISSUE THREAD

**Issue by arturmamedov** [AsgardCms/Platform#430]
### Summary of issue
User Profile data inputs doesn't show for me. But if i remove the slot-scope=label it work.

### Steps to reproduce
Fresh install of Asgard 3.3.0, try to change profile data in backend.

### System Details

- Operating System - Windows 10
- PHP Version - 7
- Laravel Version - 5.5
- `Asgardcms/Platform` 3.3.0

`Modules/User/Assets/js/components/UserProfiel.vue` 
line:28

with this it not work
```
<span slot-scope="label"
                                          :class="{'error' : form.errors.any()}">
                                        {{ trans('users.tabs.data') }}
                                    </span>
```

without `slot-scope="label"` it work and show me the input

I not familiar with vue and can't understand the slot-scope as well for understood what happens here.

**Comment by nWidart** [comment]
Thank you, this is fixed in [3.4](https://github.com/AsgardCms/Platform/releases/tag/3.4.0)
