### ISSUE TITLE
No output of non-english characters

### ISSUE THREAD

**Issue by xtf1** [AsgardCms/Platform#431]
Hello,

if the data contains a umlaut {{ $data }} outputs nothing.
If converted to html chars &uuml; data displays.
Tried it with some accent, doesn't work ether.

Happens with database entries and translations so far.
Worked in 2.x

Win7/Nginx/PHP7, Laravel 5.5 as of Asgard 3.20

**Comment by nWidart** [comment]
Hm strange, maybe something changed with blade? Does it work with `{!! !!}` ?

**Comment by xtf1** [comment]
Sorry to write this late,

it outputs ú instead of ü.
