### ISSUE TITLE
v3.3 Icons not showing in backend panel

### ISSUE THREAD

**Issue by a-h-abid** [AsgardCms/Platform#434]
### Summary of issue
Icons are not showing in admin panel. Some error are showing in the Console.

![chrome_2017-11-14_15-17-22](https://user-images.githubusercontent.com/2020773/32772139-2af1712a-c94f-11e7-96b0-64859c4b3165.png)

### Steps to reproduce
Install a fresh Asgard v3.3 and visit the backend admin panel.

### System Details

- Operating System: Windows 10 Pro
- PHP Version: 7.1.6
- Laravel Version: 5.5.x
- `Asgardcms/Platform` version: 3.3.x

**Comment by a-h-abid** [comment]
Hello, it seems the font-awesome font files you included with the project are somehow corrupted. I downloaded a fresh font-awesome copy and replaced only the fonts. Now all icons are showing and those errors were gone.

**Comment by nWidart** [comment]
Hello,
This is an annoying issue that I wasn't able to fix even after re-installing fontawesome etc.

However, I've tried something new now, to remove the files, commit that, and re-add them via npm afterwards. This change is on the `3.0` branch and hopefully works now.

**Comment by Naoray** [comment]
Facing the same issue... is there going to be a fix?

**Comment by nWidart** [comment]
Yes, read my message before yours.

**Comment by Naoray** [comment]
how can I specify which branch to download when using `composer create-project asgardcms/platform your-project-name` for installation?

**Comment by joshbrw** [comment]
@Naoray A quick Google brings up an answer. https://stackoverflow.com/questions/23754260/installing-specific-laravel-version-with-composer-create-project

**Comment by Naoray** [comment]
@joshbrw why not updating the latest version of asgardcms to include this bugfix?

**Comment by joshbrw** [comment]
@nWidart will release a new version when he feels he should @Naoray

**Comment by Naoray** [comment]
@joshbrw ok, sorry for asking.

**Comment by nWidart** [comment]
This has been tagged as 3.4 https://github.com/AsgardCms/Platform/releases/tag/3.4.0

**Comment by Naoray** [comment]
@nWidart thanks!

**Comment by Naoray** [comment]
@nWidart still not working.. Am I missing something?

![image](https://user-images.githubusercontent.com/10154100/33118097-067c3be6-cf6b-11e7-95ef-863d367bc2d0.png)

**Comment by nWidart** [comment]
I heard yes. I don't know how to fix the issue.

**Comment by a-h-abid** [comment]
@nWidart Do you remember since when you and people are having this problem? Just a guess, maybe some commit is causing this issue... Maybe if you can figure out that commit and revert it, then it might work out.

**Comment by tehuel** [comment]
I'm having the same problem on a fresh v3.4.0 installation 😞.

![imagen](https://user-images.githubusercontent.com/1787206/33221838-7f8635ce-d131-11e7-92b3-6072cf002cb7.png)

However, on Firefox im not seeing any error on console. Also i've deleted and replaced the font awesome files inside ```\public\themes\adminlte\vendor\font-awesome``` AND ```public\fonts\vendor\font-awesome``` with no luck fixing it.

**Comment by richardfeliciano** [comment]
Dudes, i`ve manage to fix downloading the fonts on http://fontawesome.io/ and replacing it on /themes/adminlte/vendor/font-awesome/fonts

**Comment by matijakovacevic** [comment]
https://stackoverflow.com/questions/41643230/fontawesome-and-git

**Comment by a-h-abid** [comment]
@nWidart Look into the link posted by @matijakovacevic . I think this may solve your problem.

Might be because in your `.gitattributes` file of adminlte-theme you set the font files attributes to text, after a git checkout it is messing with the files.

**Comment by darron1217** [comment]
How about utilizing CDN?

For performance + stability :)
https://cdnjs.com/libraries/font-awesome

**Comment by nWidart** [comment]
Indeed, you maybe even upgrade to v5 while at it. https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by GetaPub** [comment]
@nWidart 
```shell
git config --global core.autocrlf false
```

**Comment by ivansammartino** [comment]
Having the same problem, and let just an idea as @darron1217 suggested: you could link all those "static" CSS and JS assets from a CDN... please, can you add this?

**Comment by wildcard27** [comment]
The only way I have got around this is replacing the font URLs in the CSS to use the Font Awesome CDNs Can we get a proper fix for this please?

**Comment by ivansammartino** [comment]
Looking at code I found an easy way to switch local assets with CDN ones, without touching Blade templates.
Go to config/asgard/core/core.php files and look for the "admin-assets" array.
Replace your local asset (i.e. `'font-awesome.css' => ['theme' => 'vendor/font-awesome/css/font-awesome.min.css'],`) with a CDN one (`'font-awesome.css' => ['cdn' => 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'],`)

**Comment by Husky110** [comment]
And I just wonder why we still have to patch arround instead of getting a fix... ;)

**Comment by nWidart** [comment]
The fork button is at the top right.

**Comment by yassabdulrhamn** [comment]
Dears,
Try this, it used work with me


For Laravel >= 5.5

    Run npm install font-awesome --save
    Add @import "~font-awesome/scss/font-awesome.scss"; in resources/assets/saas/app.scss
    Run npm run dev (or npm run watch or even npm run production)

> https://stackoverflow.com/questions/43451509/how-to-install-font-awesome-in-laravel-mix

**Comment by bl3** [comment]
My solution was to compile the assets for the adminlte theme 

- cd /Themes/Adminlte
- npm install
- npm run production

**Comment by chiragpipariya** [comment]
First 
Go to below file and make it  'hideDefaultLocaleInURL' => false, 
config/laravellocalization.php

than 
do set below all code in .htaccess file 
`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    RewriteRule ^(themes|modules|css|js|fonts|assets)/(.*) /public/$1/$2 [L]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ /public/index.php [L]
</IfModule>
`
i hope this work for you i done this problem by this

**Comment by AgustinJimenez** [comment]
tanks @yassabdulrhamn

**Comment by nWidart** [comment]
A fix was _finally_ released regarding this issue.

Fontawesome is now being served via a cdn.

https://github.com/AsgardCms/Platform/releases/tag/3.5.2

**Comment by MirShaon** [comment]
```
.main-header .sidebar-toggle:before {
font-family: "Font Awesome 5 Free";
font-weight: 900;
content: "\f0c9";
}
```
Add bunch of css in AdminLTE.css then it will work.
