### ISSUE TITLE
Problem resource app.css and app.js

### ISSUE THREAD

**Issue by hunterbit** [AsgardCms/Platform#439]
### Summary of issue
I have problem in backend because server not found app.css and app.js. I post picture of this problem
![screenshot_1](https://user-images.githubusercontent.com/3189486/33637982-0e0deeb8-da24-11e7-83fc-de51bec096df.png)

### Steps to reproduce
Version that I download and install is 3.0

### System Details

- Operating System windows 7
- PHP Version 7
- Laravel Version 
- `Asgardcms/Platform` version 3.0

**Comment by nWidart** [comment]
That's related to how you have set up your server. You ned to point nginx/apache to the public dir.
