### ISSUE TITLE
Problem with module MEDIA - USER - GROUP

### ISSUE THREAD

**Issue by hunterbit** [AsgardCms/Platform#440]
### Summary of issue
I have problem with module because I don't see nothing. I click on link but page is empty
![screenshot_1](https://user-images.githubusercontent.com/3189486/33678409-f6f14cfa-dabb-11e7-9598-4922f6062719.png)
![screenshot_2](https://user-images.githubusercontent.com/3189486/33678431-ff752a5e-dabb-11e7-913a-89d46f401f75.png)

### Steps to reproduce
Only click on link

### System Details

- Operating System Windows 7
- PHP Version 7
- Laravel Version 5.5
- `Asgardcms/Platform` version 3.4

**Comment by nWidart** [comment]
Hello,

Have you recently updated asgardcms?

**Comment by hunterbit** [comment]
I download from github version 3.4 and after launch composer install and after php artisan asgard:install
and at the first access I have this problem

**Comment by nWidart** [comment]
do you see any errors in console or network tabs?

**Comment by hunterbit** [comment]
![screenshot_3](https://user-images.githubusercontent.com/3189486/33681048-b8540f2a-dac3-11e7-95b8-804e438eda7e.png)
![screenshot_4](https://user-images.githubusercontent.com/3189486/33681049-b87301c8-dac3-11e7-8509-a74e25a1ea57.png)
![screenshot_5](https://user-images.githubusercontent.com/3189486/33681050-b894c0f6-dac3-11e7-9856-7f9e4a4e51f2.png)

**Comment by nWidart** [comment]
odd, can't reproduce this.
You could try to run `npm install` and `npm run dev` to recompile the assets.

**Comment by hunterbit** [comment]
Ok,
now I try this

**Comment by hunterbit** [comment]
I have this error when I run -> npm run dev
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'predev', 'dev', 'postdev' ]
6 info predev @
7 info dev @
8 verbose unsafe-perm in lifecycle true
9 info @ Failed to exec dev script
10 verbose stack Error: @ dev: `npm run development`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid @
12 verbose cwd c:\xampp\htdocs\asgard
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error @ dev: `npm run development`
18 error Exit status 1
19 error Failed at the @ dev script 'npm run development'.
19 error This is most likely a problem with the  package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm run development
19 error You can get their info via:
19 error     npm owner ls
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]`
