### ISSUE TITLE
How to add vue route file without adding a line to app.js? (for complete Modularity)

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#444]
### Summary of issue
How to add vue route file without adding line to app.js? (for complete Modularity)

Currently, if I want to add a `Product` module's page built with vue, I should add the line below to app.js
```
import ProductRoutes from '../../../Modules/Product/Assets/js/ProductRoutes';
```

Is there any plan updating this functionality to improve modularity (just like angular) using webpack?

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
If anyone knows how do to this, yes. Until then this works for now. 😄
