### ISSUE TITLE
Remove public/themes and public/modules from repo

### ISSUE THREAD

**Issue by plakhin** [AsgardCms/Platform#448]
If I understand right - `public/themes/adminlte` duplicates `Themes/Adminlte/assets`. The same with `Flatly` theme and with all `Modules` assets. Why should we duplicate almost **6 thousands** of files in repository? Isn't it better to remove them from repository and add `public/themes` and `public/modules` to `.gitignore`?

And if I do it for my repository what will be the step to publish these assets after cloning repository? 
`asgard:publish:module` and `asgard:publish:theme` or something else?

**Comment by nWidart** [comment]
That's up to you yes. You can still do that on your projects.
