### ISSUE TITLE
CRUD operation is not working in newly created module

### ISSUE THREAD

**Issue by developr007** [AsgardCms/Platform#449]
CRUD opertainon is not working in newly created module. i can't access form  input values in controller store function( I am not getting value. $request->all())
![2](https://user-images.githubusercontent.com/30045765/34480975-7cd6c6dc-efd5-11e7-8b58-d89c8293734a.jpg)

**Comment by nWidart** [comment]
This doesn't seem to be related to asgardcms but to how you have setup your module. This is a usual mysql error which means you either have to set that column to nullable or set a default value.

**Comment by developr007** [comment]
i can't access input values in controller
    public function store(CreateMymoduleRequest $request)
    {
		
 echo $request->input('name');
       
     exit;
        $this->mymodule->create($request->all());

        return redirect()->route('admin.mymodule.mymodule.index')
            ->withSuccess(trans('core::core.messages.resource created', ['name' => trans('mymodule::mymodules.title.mymodules')]));
    }

**Comment by nWidart** [comment]
Please read the laravel documentation.

**Comment by developr007** [comment]
$this->mymodule->create($request->all());

**Comment by developr007** [comment]
i know laravel

**Comment by joshbrw** [comment]
@developr007 You have provided no helpful information relating to the problem, and the problem itself is not relating to AsgardCMS.

**Comment by developr007** [comment]
i created new module using php artisan asgard:module:scaffold

**Comment by joshbrw** [comment]
Awesome. This error isn't AsgardCMS-specific.
