### ISSUE TITLE
FatalException Declaration of SentinelUserRepository::create() must be compatible 

### ISSUE THREAD

**Issue by karneaud** [AsgardCms/Platform#450]
### Summary of issue
> Declaration of Modules\User\Repositories\Sentinel\SentinelUserRepository::create(array $data, $activated = false) must be compatible with Modules\User\Repositories\UserRepository::create($data)

### Steps to reproduce
- Install Asgard version 2 with default sentinel user module
- try `$user = app(UserRepository::class)->find($user_id);`

### System Details

- Operating System - Vagrant 1.9.5
- PHP Version - PHP 7.1.3-3+deb.sury.org~xenial+1 (cli) (built: Mar 25 2017 14:00:03) ( NTS )
- Laravel Version - Laravel Framework 5.4.27
- `Asgardcms/Platform` version 2

**Comment by nWidart** [comment]
Hello,

As mentioned on the slack channel version 2 isn't supported anymore. 
You can however still send a PR to the 2.0 branch if you like.

I suggest using version 3 to stay up to date with the fixes and new features
