### ISSUE TITLE
Problem in ThemeManager Test for Theme backend edition

### ISSUE THREAD

**Issue by flixart33** [AsgardCms/Platform#451]
### Summary of issue
In Modules\Workshop\Manager\StylistThemeManager.php - line 45

`foreach ($this->getDirectories() as $directory) {
            if (! str_contains(strtolower($directory), strtolower($themeName))) {
                continue;
            }
            return $this->getThemeInfoForPath($directory);
        }
`

This is too generalist, if le path of project include the theme name, all directories of themes will contain the theme name and first theme will be returned

Can you test only last member of path ?

### Steps to reproduce

Create a theme in a path with the theme name.
Sample : /home/www/society-fr/web/Themes/Society

**Comment by teoni** [comment]
+1
Thanks I was wasting an hour figuring out what causes the problem.

**Comment by nWidart** [comment]
Fixed and tagged in 3.5.1 🚀
