### ISSUE TITLE
Update Translation module on composer

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#452]
### Summary of issue
I recently send merge request for Korean Translation and it accepted.
But the merge seems does not applied to Composer..
Will you publish it?

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Hello,

Sorry for the late reply, I've been busy with work lately.
I'll try to make a release this weekend.

Thank you,

**Comment by nWidart** [comment]
This has been tagged as 3.5. 👍
