### ISSUE TITLE
How to insert multiple files with element-io?

### ISSUE THREAD

**Issue by daothanh** [AsgardCms/Platform#454]
### Summary of issue
I need insert multiple files but I can't find MultipleMedia component in media module

- Operating System: MacOs
- PHP Version 7.0
- Laravel Version 5.5
- `Asgardcms/Platform` v3.4.0

**Comment by ducdc91** [comment]
Hello, is this what you're looking for?

https://asgardcms.com/docs/v3/media-module/linking-media-to-entities#display-input-on-views

// Create view
@mediaMultiple('gallery')

// Edit view
@mediaMultiple('gallery', $article)

**Comment by daothanh** [comment]
@ducdc91 No.  I look for a vuejs component.

**Comment by nWidart** [comment]
This isn't built in yet. You'll have to make it yourself.
Also there's a [PR](https://github.com/AsgardCms/Platform/pull/437) that does this, but I haven't had the chance to review it yet.
