### ISSUE TITLE
Tags module does not support multi language... (Non ASCII word cannot be saved)

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#455]
### Summary of issue
Tags module does not support multi language...
Non ASCII word cannot be saved.
Is there a way to use tag without slug?
How about UTF-8 slug? :)

#LetsMakeItBig

### Steps to reproduce
ex) Korean Language `태그입니다` cannot be saved because slug is empty field...

Actually, first saving is okay because Tag with empty slug can be inserted into database. But every tag (without ASCII code) gets same empty slug so they override themselves...

### System Details

- Operating System
- PHP Version
- Laravel Version
v5.5.0
- `Asgardcms/Platform` version
v3.4.0

**Comment by nWidart** [comment]
Closing since merged. 
Thanks! 👍
