### ISSUE TITLE
Select image modal (ckeditor) loads all images at once.

### ISSUE THREAD

**Issue by flakyspark** [AsgardCms/Platform#457]
### Summary of issue
If you have a lot of images in Media - you have problems with 'Select image dialogue'. This dialogue (/backend/media/media-grid/ckIndex) loads all images at once. And this is too slow. In other hand - standart UI of Media uses ajax-pagination (through API as i understand). It works perfect and fast. Why not use this approach in 'Select image dialogue' ?

**Comment by nWidart** [comment]
This is fixed with the vuejs version on the image selector.

**Comment by flakyspark** [comment]
Thx for answer. Must i enable something in cofig or only update CMS?

**Comment by nWidart** [comment]
If you're on v3 you already have it. However you need to have vuejs setup etc.

**Comment by flakyspark** [comment]
I am on v3 and seems in /backend/media/media i have vue version (so seems it is installed), but in /backend/media/media-grid/ckIndex still no vue.

**Comment by nWidart** [comment]
yes because it's a new vue component. Look at the PageForm component it has a media component on it.

**Comment by flakyspark** [comment]
Ok thx
