### ISSUE TITLE
Create page fields not sticky

### ISSUE THREAD

**Issue by seanthepottingshed** [AsgardCms/Platform#46]
If you create page without entering template name, the following forms are not sticky when the page reloads:

* Meta description
* Facebook description
* Body WYSIWYG editor

![unsticky-form-fields](https://cloud.githubusercontent.com/assets/12046965/8101986/54ad9378-1014-11e5-8d48-db81a857b6cd.png)

**Comment by nWidart** [comment]
Thanks for reporting, I'll get to this asap.
