### ISSUE TITLE
Use module alias instead of module name when generating view namespaces for modules

### ISSUE THREAD

**Issue by teoni** [AsgardCms/Platform#461]
When Asgard generates the module view namespaces, it uses the module name. It should use the module alias IMHO.

So now I have this module for example:
`{
    "name": "Revolution Slider",
    "alias": "revslider",
    "description": "",
    "keywords": []
}
`
And the view namespace is the following: "revolution slider" so
`view("revolution slider::index")`

And it should be: "revslider" - generated from the alias.

Asgard 3

**Comment by nWidart** [comment]
Hm, this is an interesting view. 
I do agree with the idea, but I'm not sure of the repercussions this could have, it might be a breaking change for some.

**Comment by teoni** [comment]
Yes surely. So now basically there's no reason to use different module name and alias, as I can see.

Maybe if you agree, but don't want to make a breaking-change, let's add some prefixed view namespace for the modules beside the default one (which is generated from the module name). So every modules will have two namespaces. Then you could mark the first as deprecated and remove from the next version.

But this is just an idea, it's not a big deal to define the same name and alias for a module. Or using a one-word module name.

**Comment by nWidart** [comment]
Maybe this is something to do for the next major release.

I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
