### ISSUE TITLE
Ziggy @routes Blade Directive Not working

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#464]
### Summary of issue
![image](https://user-images.githubusercontent.com/8064923/35849610-915fa7c6-0b65-11e8-8b53-3634a24c7035.png)

https://github.com/tightenco/ziggy/issues/115
This bug caused by Ziggy package
Maybe we should update version of Ziggy at core-module

### Steps to reproduce
Install new AsgardCMS on 3.5.0 version

### System Details

- Operating System Alpine
Linux + Nginx
- PHP Version
7.1
- Laravel Version
5.5.33
- `Asgardcms/Platform` version
3.5.0

**Comment by darron1217** [comment]
Sorry, this problem was solved after one more update....

**Comment by darron1217** [comment]
It is fixed on ziggy  version  0.6.0

**Comment by darron1217** [comment]
No it's not fixed....
I also removed view cache but still not rendering...

**Comment by nWidart** [comment]
Maybe worth reporting this to their package then.

**Comment by darron1217** [comment]
Yep, I've submitted PR on their package :)
I'll close this issue by myself after the PR is accepted

**Comment by darron1217** [comment]
https://github.com/tightenco/ziggy/pull/127

My fix merged into master branch, but not yet released on composer

**Comment by nWidart** [comment]
Thanks for the heads-up!

**Comment by nWidart** [comment]
Was this tagged on their part?

**Comment by darron1217** [comment]
They released v0.6.2 and my fix included.

This issue is solved :)
