### ISSUE TITLE
Test not passing after installation

### ISSUE THREAD

**Issue by wildcard27** [AsgardCms/Platform#465]
### Summary of issue
Running phpunit.xml, after installation, fails at the following test:
```
\Modules\Media\Tests\MaxFolderSizeRuleTest::it_validates_max_folder_size_is_valid
```

### Steps to reproduce

1. Install AsgardCMS as per instructions.
2. Run PHPUnit on `phpunit.xml` in the project root.

### System Details

- Operating System - Ubuntu 17.04
- PHP Version - 7.0.22
- Laravel Version - 5.5.3
- `Asgardcms/Platform` version - 3.0

**Comment by wildcard27** [comment]
We were trialling Asgard as a possible candidate for being our agency's "go-to" CMS. Unfortunately, the lack of support has caused us to drop it.

**Comment by nWidart** [comment]
That's unfortunate. Tests are passing on travis so I cannot reproduce your setup. This is open source though, if you see an issue and you can fix it, you can contribute to it.

**Comment by nWidart** [comment]
For your information, if you want quick support you can take a look at this: https://asgardcms.com/premium-support

**Comment by pascal08** [comment]
I can confirm this is an issue with a fresh install.

**System Details**
Operating System - Ubuntu 18.04
PHP Version - 7.2.23
Laravel Version - 5.5.40
Asgardcms/Platform version - 3.5.3

I've had a quick look at what's going on here.

1. The uploaded file in this test is not placed in /assets/media.
2. The directory that is tested is /public which is 4096 bytes (default on unix) and therefore this test is not passing (i.e. the size should not be bigger than 1000 bytes)

**Comment by nWidart** [comment]
I see that's interesting. I'd accept a pull request that fixes this :)
