### ISSUE TITLE
Locale is still in menu item urls although hideDefaultLocaleInURL is true

### ISSUE THREAD

**Issue by JayyWalker** [AsgardCms/Platform#466]
### Summary of issue
I have set `hideDefaultLocaleInURL` to true, but the menu items still seem to apply the locale.

E.g. If I have a sports menu item, I would expect the uri to be `sports`, but instead it is `en/sports`. If I actually go to the page, the uri is `sports` as I would expect it to.

This prevents matching urls which I need so that the active menu item can be found. 

### Steps to reproduce
1. In `config/laravellocalization.php`, change `hideDefaultLocaleInURL`  to true.
2. Create a menu with menu items.
3. Display the menu in your theme's master template using the blade directed @menu('<menu-name-here>').
4. Check the urls in the menu item.

### System Details

- Operating System: Ubuntu 16.04.3 LTS
- PHP Version: 7.2
- Laravel Version:  5.5.31
- `Asgardcms/Platform` version: 3.5.0

**Comment by kamekun** [comment]
Fixed on the pull request #517 tested and working fine.
