### ISSUE TITLE
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.

### ISSUE THREAD

**Issue by twocngdagz** [AsgardCms/Platform#468]
### Summary of issue
I got this message when installing

### Steps to reproduce
composer global require asgardcms/asgardcms-installer

### System Details

- Operating System - Mac OS High Sierra v 10.13.3
- PHP Version - PHP 7.1.14
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Thanks, this isn't posted on the right repository though. This is the correct one: https://github.com/AsgardCms/asgardcms-installer
