### ISSUE TITLE
blocking usage of flysystem : some missing stuff

### ISSUE THREAD

**Issue by Grummfy** [AsgardCms/Platform#47]
Just a reminder
not available : isDIrectory, isFile

SO we need to check the usage and check if we need to create a fix or whatever.

**Comment by mvdstam** [comment]
I don't understand how this is a Asgard issue.

**Comment by Grummfy** [comment]
Like I said on slack : 

you can close it if you want but before reporting in another place we need to analyse it => issue on our side => then reporting => issue is not related to us anymore

**Comment by joshbrw** [comment]
Closing
