### ISSUE TITLE
Is there a proper way to upload logo, which should be appeared at the header of frontend?

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#474]
### Summary of issue
I think every CMS has this function because it's important to show site's identity.

Modifying Themes to achieve this is not the proper way, I thought.

How about adding it to site config?

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
You could add this in your "core" module configuration. 
I usually have a module named after the project, with things like these.

**Comment by nWidart** [comment]
Closing due to merged PR 👍
