### ISSUE TITLE
Is there any plan to make api key expiration option?

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#475]
### Summary of issue
I wondered how to set expiration date on api key

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by darron1217** [comment]
How about using JWT?
https://github.com/tymondesigns/jwt-auth

In my experience, JWT was simple & secure

**Comment by nWidart** [comment]
Hello,

Jwt would indeed be a possibility. However, with the little time availability I have now, I'm not sure it's worth the investment.
If and when it gets asked more it's definitely a possibility though.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by samier** [comment]
@nWidart  if the token is not expired then how to make api secure? as a token is fixed and not getting changed, so anyone can able to access API with the same token? Please suggest better solution
