### ISSUE TITLE
Page template name not displayed

### ISSUE THREAD

**Issue by hunterbit** [AsgardCms/Platform#476]
Hello to all,
I created my template but when I go to create a new page I can not see all the "template page names" but in the dropdown I see only error / 400 and error / 500.
What should I do to have the other "template page names" displayed?

- Operating System Windows 10
- PHP Version 7
- Laravel Version 5.4
- `Asgardcms/Platform` version 3.5

![image](https://user-images.githubusercontent.com/3189486/36167780-4e6f2904-10f7-11e8-9f77-b29250632127.png)

**Comment by teoni** [comment]
Hi,

Check this out: https://github.com/AsgardCms/Platform/issues/451

**Comment by hunterbit** [comment]
Thanks now it's all ok.

**Comment by nWidart** [comment]
Fixed and tagged in 3.5.1 🚀
