### ISSUE TITLE
[Media Module] GET api/media/all returns error

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#477]
### Summary of issue
`Non-static method Modules\\Media\\Image\\Imagy::getThumbnail() should not be called statically`
This error message returned from all() method in Api\MediaController

https://github.com/AsgardCms/Platform/blob/a96dec0874fe042019d79fa95d90ccb85c5427b4/Modules/Media/Http/Controllers/Api/MediaController.php#L56

`Imagy::getThumbnail($file->path, 'smallThumb')`
should be changed into
`$this->imagy->getThumbnail($file->path, 'smallThumb')`

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Fixed and tagged in 3.5.1 🚀
