### ISSUE TITLE
[Feature Request] Adding Trash Can to Media Module

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#480]
### Summary of issue
I thought it is dangerous to expose 'permanent delete' button on the file list. (Even more dangerous to expose folder removing button)

How about changing the action of delete button as 'Move to Trash Can'.

Then, we can flush it whenever we want to remove it permanently

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Hello, 

I like this idea. Basically adding soft-delete on files and directories, allowing them to be recovered.

**Comment by darron1217** [comment]
@nWidart Yes, laravel supports perfect solution for this issue, but we need some more...
How about adding 'Trashed Media' menu&page on admin to show only trashed media?

**Comment by darron1217** [comment]
Also, we should handle the file's url issue.
I think we should move the file to 'trashcan' area, so that users can realize the file is abandoned (by showing 404)

**Comment by nWidart** [comment]
That's a good idea indeed. Storing both paths will allow us to have a "restore" button for instance.

When viewing the trashcan, there could be an option to completely delete the file.

**Comment by mikemand** [comment]
Why not just use [Soft Deleting](https://laravel.com/docs/5.7/eloquent#soft-deleting)? No need to deal with moving the media, it can stay where it is.
