### ISSUE TITLE
[Core Module] Is it really needed to publish assets of Sentinel during installation?

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#481]
### Summary of issue
I found this file does nothing (while we are using User Module for default)
`database/migrations/2014_07_02_230147_migration_cartalyst_sentinel.php`

I also found that the script below generates the file while installing.
https://github.com/AsgardCms/Platform/blob/9f9c4c470817a5b471fcd4f64fd2085475c25ef9/Modules/Core/Console/Installers/Scripts/UserProviders/SentinelInstaller.php#L38-L42

To reduce confusion, how about removing that migration file from this repo (git) and also remove the lines that publishes Sentinel assets?

I thought we do not need to run publish() on Sentinel because we already have it on git.
ex) `config\cartalyst.sentinel.php`

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Hello,

This is in case Sentinel has a changed migration, so that is published automatically.

**Comment by darron1217** [comment]
@nWidart Then, how about removing `Platform/database/migrations/2014_07_02_230147_migration_cartalyst_sentinel.php` from git?
And also removing publish command on Sentinel?
As I mentioned, we already have the files we need on this repo :)
ex) config\cartalyst.sentinel.php

**Comment by nWidart** [comment]
Hm if I remember correctly the migration file inside the user module is there for tests purposes only.
I think we still need the one in platform/database.

**Comment by darron1217** [comment]
I was wondered about that issue, so I've tested installing AsgardCMS without the file `database/migrations/2014_07_02_230147_migration_cartalyst_sentinel.php` (not user module's)

Then, it worked well :)
So I thought, if installing process uses User Module's migration, there is no need to have duplicate file on the platform

**Comment by nWidart** [comment]
It is there because of the vendor:publish command will put it there. I don't see a need to remove it, as it will be added back.
We can't also remove the vendor:publish command as it is also needed.

**Comment by darron1217** [comment]
@nWidart Okay... I understood :)
Thank you for sharing your opinion
