### ISSUE TITLE
Fetch current selected locale in a config file

### ISSUE THREAD

**Issue by naveenv1985** [AsgardCms/Platform#484]
### Summary of issue
Fetch current selected locale in a file in config directory

### Steps to reproduce
How to fetch current selected locale on a config file which is located inside config folder? Actually im using a custom file called frontend-assets.php for all frontend assets at config->frontend-assets.php which is a config file similar to config->asgard->core->core.php which has all the admin assets. In the frontend-assets.php i want to fetch the current selected locale on the site. 
app()->getLocale() always gives me the site default locale but i need the current selected locale.

### System Details

- Operating System - Linux
- PHP Version - 7.0
- Laravel Version - 5.4
- `Asgardcms/Platform` version - 2.6.1

**Comment by nWidart** [comment]
You can use this method: https://github.com/mcamara/laravel-localization#set-locale

**Comment by naveenv1985** [comment]
Well... the above method cannot be used directly in the asgard config files though they are php files, Facades are not available for access in those files.

I had to do: request()->segment(1) to get the locale.

Is there a better approach?

**Comment by nWidart** [comment]
You shouldn't call anything in config files, yes. So you can't do what you want there.

**Comment by naveenv1985** [comment]
Basically what i want to achieve is load different css files corresponding to each locale. Since the assets are declared in config file have to send the current locale to config file to pick the correct css file. Is there any other option to achieve this?

**Comment by nWidart** [comment]
Hm, I wouldn't do this logic in the config itself. Maybe you could do this in the view, based on the locale load the assets related to that locale.

Maybe the config file could be something like

```php
'en' => [array of assets],
'fr' => [array of assets],
'nl' => [array of assets],
```

**Comment by naveenv1985** [comment]
Slightly changed the logic and was able to achieve above implementation. Thanks a lot @nWidart

**Comment by nWidart** [comment]
Awesome!
I'll close this issue then :)
