### ISSUE TITLE
BaseEloquentRepository allWithBuilder() Error

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#487]
### Summary of issue
`Type error: Return value of Modules\Core\Repositories\Eloquent\EloquentBaseRepository::allWithBuilder() must be an instance of Illuminate\Database\Eloquent\Builder, instance of Modules\{ModuleName}\Entities\{ModelName} returned`

`{ModuleName}` and `{ModelName}` is just sample name.

I got an error while calling `allWithBuilder()` of my own repository. (Which extends BaseRepository without any overriding)

I looked into the error and I found that this method returns `return $this->model;`
Just like the link below
https://github.com/AsgardCms/Platform/blob/9f9c4c470817a5b471fcd4f64fd2085475c25ef9/Modules/Core/Repositories/Eloquent/EloquentBaseRepository.php#L62

Maybe we should change this method into `return $this->model->query();` to avoid error

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
Hm interesting, this worked before. 

Indeed I think the `query()` method does return the correct type.

**Comment by darron1217** [comment]
@nWidart I think if we use Translatable Model, we can avoid this error.
I was using it well too :)
