### ISSUE TITLE
New issue on fresh installation

### ISSUE THREAD

**Issue by bradxxx** [AsgardCms/Platform#49]
FatalErrorException in E:\Jekyll\agardcms\vendor\maatwebsite\laravel-sidebar\src\Maatwebsite\Sidebar\SidebarBadge.php line 3:

Maximum function nesting level of '100' reached, aborting!

**Comment by nWidart** [comment]
That's an xdebug issue.
Please raise your maximum nesting level.

http://xdebug.org/docs/all_settings

**Comment by bradxxx** [comment]
thanks
