### ISSUE TITLE
Error Exception when trying to Access User, Roles or Profile

### ISSUE THREAD

**Issue by PadaliaRushabh** [AsgardCms/Platform#491]
### Summary of issue
After creating a new user with custom role. The user is unable to view User, Roles or Profile Page

### Error Details

exception: "ErrorException"
file:"/var/www/html/quotation/Modules/User/Http/Middleware/AuthorisedApiToken.php"
line:43
message:"Trying to get property of non-object"

### Steps to reproduce
1) Create a new role and give it permission to view Users 
2) Create a new user and assign it to the newly created role
3) Login in and click on Users from side bar menu

**Role Permission Details**
> {"core.sidebar.group":true,"dashboard.index":true,"dashboard.update":true,"dashboard.reset":false,"media.medias.index":true,"media.medias.create":true,"media.medias.edit":true,"media.medias.destroy":true,"media.folders.index":true,"media.folders.create":true,"media.folders.edit":true,"media.folders.destroy":true,"menu.menus.index":false,"menu.menus.create":false,"menu.menus.edit":false,"menu.menus.destroy":false,"menu.menuitems.index":false,"menu.menuitems.create":false,"menu.menuitems.edit":false,"menu.menuitems.destroy":false,"page.pages.index":false,"page.pages.create":false,"page.pages.edit":false,"page.pages.destroy":false,"setting.settings.index":false,"setting.settings.edit":false,"tag.tags.index":false,"tag.tags.create":false,"tag.tags.edit":false,"tag.tags.destroy":false,"translation.translations.index":false,"translation.translations.edit":false,"translation.translations.import":false,"translation.translations.export":false,"user.users.index":true,"user.users.create":true,"user.users.edit":true,"user.users.destroy":true,"user.roles.index":true,"user.roles.create":true,"user.roles.edit":true,"user.roles.destroy":true,"account.api-keys.index":false,"account.api-keys.create":false,"account.api-keys.destroy":false,"workshop.sidebar.group":true,"workshop.modules.index":true,"workshop.modules.show":true,"workshop.modules.update":false,"workshop.modules.disable":false,"workshop.modules.enable":false,"workshop.modules.publish":false,"workshop.themes.index":false,"workshop.themes.show":false,"workshop.themes.publish":false}

### System Details

- Operating System - Ubuntu 17.10
- PHP Version - 7.1.11-0ubuntu0.17.10.1
- Laravel Version - 5.5.*
- `Asgardcms/Platform` version -  3.0.x-dev

**Comment by PadaliaRushabh** [comment]
Turns out there was an exception in the mailtrap.io config. Solving the config and following the entire activation process fixes the issue

**Comment by Fisiu** [comment]
It might be related to #496, however fix is awaiting to be merged #528.
Beside that, @PadaliaRushabh updated that it's no longer issue. What about closing it, @nWidart?
