### ISSUE TITLE
Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint...

### ISSUE THREAD

**Issue by olegshepel** [AsgardCms/Platform#494]
Hi, my problem is trying to make command: "php artisan migrate" in 1 version evething is ok:
public function up()
    {
        Schema::create('companies', function (Blueprint $table) {
            $table->increments('id');
            $table->text('company_id');
            $table->text('company_name');
            $table->boolean('company_verify')->default(0);
            $table->timestamps();
            $table->integer('user_id')->unsigned()->nullable();
            $table->integer('email_id')->unsigned()->nullable();
            $table->integer('phone_id')->unsigned()->nullable();
        });
        //Schema::enableForeignKeyConstraints();
        Schema::table('companies', function (Blueprint $table) {
            $table->foreign('user_id')->references('id')->on('users')
                    ->onUpdate('cascade')->onDelete(NULL);
//            $table->foreign('email_id')->references('id')->on('emails')
//                    ->onUpdate('cascade')->onDelete(NULL);
//            $table->foreign('phone_id')->references('id')->on('phones')
//                    ->onUpdate('cascade')->onDelete(NULL);
        });
    }
But once uncomment: foreign key for email_id and phone_id (even only email_id) the error: Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `companies` add constraint `companies_email_id_foreign` foreign key (`email_id`) references `emails` (`id`) on update cascade). PS: 
public function up()
    {
        Schema::defaultStringLength(191);
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('surname');
            $table->string('password');
            $table->boolean('status')->default(TRUE);
            $table->rememberToken();
            $table->timestamps();
            $table->integer('company_id')->unsigned()->nullable();
            $table->integer('role_id')->unsigned()->nullable();
            $table->integer('email_id')->unsigned()->nullable();
            $table->integer('phone_id')->unsigned()->nullable();
        });
    }
and table of emails:
public function up()
    {
        Schema::defaultStringLength(191);
        Schema::create('emails', function (Blueprint $table) {
            $table->increments('id');
            $table->string('email');
            $table->boolean('email_verify')->default(0);
            $table->integer('email_type')->unsigned()->nullable();
            $table->integer('company_id')->unsigned()->nullable();
            $table->timestamps();
        });
//        Schema::table('emails', function (Blueprint $table) {
//            $table->foreign('email_type')->references('id')->on('email_types')
//                    ->onUpdate('cascade')->onDelete(NULL);
//        });
    }

Pls help someone. What is the problem ?

**Comment by nWidart** [comment]
Hello,

This is not an issue with asgardcms.
Make sure to read the laravel docs on migrations.

The errors says you have an issue with your foreign keys.

**Comment by Fisiu** [comment]
@nWidart What about closing this one?

**Comment by nWidart** [comment]
@Fisiu Good idea :)
