### ISSUE TITLE
CKEditor not saving content

### ISSUE THREAD

**Issue by mariglenjahollari** [AsgardCms/Platform#495]
### Summary of issue
There's a problem with the CKEditor. Whenever I write some text in the source editor, the page won't save the new text. Only the old editor content is POSTed, although I get the notification that the page was saved successfully. However, this problem does not occur when I type in the visual editor, only when writing in the source. My guess is that it has something to do with the editor not triggering document.write() when using only the source editor, which causes the POST request to get the old data. A workaround to this is to write the text in the source editor and in order to save it, write something in the visual editor just to trigger the write() method. This way the POST request will contain the pasted text.
### Steps to reproduce
-	Open a page, write some text in the CKEditor, in Source.
-	Save the page and reopen it
-	The editor will show the old content

This problem occurs even in a fresh Asgard installation.
### System Details
- Operating System: Ubuntu 16.04.1
- PHP Version: 7.1.15
- Laravel Version: 5.5.36
- `Asgardcms/Platform` version: 3

**Comment by nWidart** [comment]
Hello,

Indeed I've had this before too. I've reported this to the editor package, but nothing new last I checked.
I'll close this issue for now as it's mostly related to the upstream package itself.

**Comment by abemuis95** [comment]
Hi,

I'm facing the same problem. How to fix this?

**Comment by jmazurpl** [comment]
Same here. Maybe the solution would be to update ckeditor?
