### ISSUE TITLE
Menu package configuration

### ISSUE THREAD

**Issue by kamekun** [AsgardCms/Platform#499]
### Summary of issue
Hi, im trying to  style my menu on frontend theme, i called the {!! Menu::get('main') !!} and get the values with boostrap, but dont understabd how how to make the "Custom presenter" work.

### Steps to reproduce
Generate a menu with {!! Menu::get('main') !!} , try yo create a custom presenter.

### System Details

- Operating System
- PHP Version 7.0
- Laravel Version 5.5
- `Asgardcms/Platform` version 3.5.2

**Comment by mikemand** [comment]
`Menu::get()` (as well as the blade directive, `@menu()`) accept a second parameter for the class name of the presenter you want to use. For example: `Menu::get('main', \Modules\Mysite\Presenters\MainMenu::class)`

**Comment by kamekun** [comment]
Thanks you for you reply, you're right; with set the presenter this way i get the menu view like i want.

Regards.
