### ISSUE TITLE
Generated module but no fields display on form

### ISSUE THREAD

**Issue by bradxxx** [AsgardCms/Platform#50]
module was created with entity and objects but when adding record there are no fields associated

**Comment by nWidart** [comment]
This is working as intended. The fields need to be added by you after generation.

**Comment by bradxxx** [comment]
can u give directions for that?

**Comment by nWidart** [comment]
This is nothing specific to AsgardCms. Just go ahead like any Laravel model.

**Comment by bradxxx** [comment]
suppose if i modify the migration file and run migration will those added field be available ?

**Comment by nWidart** [comment]
Those will be on the database, the fields won't magically display on the form and index views though. 
Just proceed like any laravel app..
