### ISSUE TITLE
[Menu] Menus not displaying active state when default lang is hidden

### ISSUE THREAD

**Issue by kamekun** [AsgardCms/Platform#502]
Summary of issue
Hi i found a bug with the module menu, when i  set the `hideDefaultLocaleInURL` to true, and the default lang is hide, the active lang dont recognize the active menu option. on the Menu::get('main'), if i leave it as false, it work normal.

Steps to reproduce
Go to config `Laravellocalization.php` and set the option `hideDefaultLocaleInURL` to true, go to your front-end  and get your menu with  `{!! Menu::get('main', \Modules\Menu\Presenters\MenuPresenter::class) !!}`
</nav>
System Details

    Operating System
    PHP Version 7.0
    Laravel Version 5.5
    Asgardcms/Platform version 3.5.2

**Comment by Fisiu** [comment]
I think issue is within `nwidart/laravel-menus` package.
All checks failed inside `public function isActive()` except `getActiveStateFromUrl()`:
```php
protected function getActiveStateFromUrl()
{
    return Request::is($this->url);
}
```
$this->url is always $$/slug where $$ is lang. If we hide $$ in default lang it always returns `false`.

**Comment by devakumetsu** [comment]
Fixed on the pull request #517

**Comment by kamekun** [comment]
Fixed on the pull request #517 tested and working fine now.

Regards.-

**Comment by Fisiu** [comment]
I can't get it working, even with AsgardCMS 3.5.3 which includes this fix. For me, it's still valid bug report.

**Comment by bl3** [comment]
i have the same issue, if hideDefaultLocaleInURL = true and default language isn't english, the active class is not given to the li element. Because the url given by the menu $item does include the locale prefix and therefore does not match with the current URL.
