### ISSUE TITLE
ActiveEditor.js prevents a custom editor from being loaded

### ISSUE THREAD

**Issue by superewald** [AsgardCms/Platform#506]
### Summary of issue
Registering a custom editor via the `EditorIsRendering` hook will give you a vue error on loading saying that `ckeditor.js` dependency wasn't found.

```js
app.js:1607 [Vue warn]: Error in callback for watcher "value": "ReferenceError: CKEDITOR is not defined"
app.js:2755 ReferenceError: CKEDITOR is not defined
```

### Steps to reproduce
I did exactly what is told here: [Hooks::EditorIsRendering](https://asgardcms.com/docs/v3/core-module/hooks#editor-is-rendering).

* create an `EditorIsRendering` handler (look `LoadToastUIEditor`)
* add handler to `wyswig-handler` config (look `core.php`)
* visit a backend page with an editor field  (`localhost/backend/page/pages/1/edit` for eg)
* look at the JS console and see loading the editor failing.

**my custom editor files (for Toast UI Editor):**

<details><summary>App\Events\Handlers\LoadToastUIEditor</summary>
<p>

```php
<?php
namespace App\Events\Handlers;


use Modules\Core\Events\EditorIsRendering;

class LoadToastUIEditor
{
    public function handle(EditorIsRendering $editor)
    {
        $editor
            ->addJs('markdown-it.js')
            ->addJs('codemirror.js')
            ->addJs('toMark.js')
            ->addJs('tui-code-snippet.js')
            ->addJs('codemirror.js')
            ->addJs('highlight.js')
            ->addJs('squire-raw.js')
            ->addJs('tui-editor.js');

        $editor
            ->addCss('tui-editor.css');

        $editor->setEditorClass('tui-editor');
        view()->share('activeEditor', 'tui-editor');

        return false;
    }
}
```

</p>
</details>

<details><summary>config/asgard/core/core.php</summary>
<p>

```php
...
   'wysiwyg-handler' => App\Events\Handlers\LoadToastUIEditor::class
...
```

</p>
</details>

### System Details

- Operating System: Linux/Ubuntu 16.04 (Docker)
- PHP Version: 7.1
- Laravel Version: 5.5.39
- `Asgardcms/Platform` version: 3.0

### Bug Breakdown

This error has it roots in the `Modules/Core/Assets/js/mixins/ActiveEditor.js` file which is imported to determine *vue component name* of the current editor.

```js
export default {
    methods: {
        getCurrentEditor() {
            const configuredEditor = window.AsgardCMS.editor;
            if (configuredEditor === 'simplemde') {
                return 'markdown-editor';
            }
            if (configuredEditor === 'ckeditor') {
                return 'ckeditor';
            }
            return 'ckeditor';
        },
    },
};
```

We can see that `getCurrentEditor` only checks for `ckeditor` or `simplemde` and **will return `ckeditor` on default**.

This effectively prevents our custom editor from being loaded (it will always try to load the `ckeditor`).

### Solution

We can fix this error by just letting `getCurrentEditor` return our editor name as component name on default.

* let `getCurrentEditor()` return `window.AsgardCMS.editor` on default
* add `undefined` check and return `ckeditor` as fallback

```diff
export default {
    methods: {
        getCurrentEditor() {
            const configuredEditor = window.AsgardCMS.editor;
            if (configuredEditor === 'simplemde') {
                return 'markdown-editor';
            }
-            if (configuredEditor === 'ckeditor') {
+           if (configuredEditor === 'ckeditor' || configuredEditor === undefined) {
                return 'ckeditor';
            }
-            return 'ckeditor';
+           return configuredEditor;
        },
    },
};
```

> NOTE: My example script will still not work after this patch because we didn't register the vue component itself. Add this step to the AsgardCms documentation at the Hooks::EditorIsRendering section for completion.

**Comment by nWidart** [comment]
I'll close this now since your PR has been merged.

Thanks for the very detailed report & fix! 😄
