### ISSUE TITLE
artisan migrate exception CreateWidgetsTable not found

### ISSUE THREAD

**Issue by RicardovanTongeren** [AsgardCms/Platform#51]
When running 

```
php artisan migrate:refresh --seed
````

I'll get the following error

```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'CreateWidgetsTable' not found 
```

Can someone hint me in the right direction? I can submit my logfile if this is necessary.

**Comment by mvdstam** [comment]
Did you try `php artisan module:migrate`? Looks like your modules aren't fully migrated.

**Comment by RicardovanTongeren** [comment]
```
vagrant@homestead:~/Code/asgardcms$ php artisan module:migrate
Running for module: core
Nothing to migrate.
Running for module: user
Nothing to migrate.
Running for module: workshop
Nothing to migrate.
Running for module: setting
Nothing to migrate.
Running for module: menu
Nothing to migrate.
Running for module: dashboard
Nothing to migrate.
Running for module: media
Nothing to migrate.
Running for module: page
Nothing to migrate.
```

Still got the error after running this.

```
vagrant@homestead:~/Code/asgardcms$ php artisan migrate:refresh --seed
PHP Fatal error:  Class 'CreateWidgetsTable' not found in /home/vagrant/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 323
```

**Comment by nWidart** [comment]
Why do you want to use the migrate command from laravel ? 

If you really want to use the native migrate command, try to publish all module migrations using `php artisan module:publish-migration`.

**Comment by RicardovanTongeren** [comment]
I'd like to use the native migrate command because I think this is the right way to add tables to my database. I also would like to be able reseeding my database over and over again. Should I make a module for this?

**Comment by nWidart** [comment]
You can publish the migrations with `php artisan module:publish-migrations`.

Also with this module architecture, I'd recommend placing your migrations inside the module, otherwise those aren't really in dependable. Meaning you need the database/migrations folder for you module to work.

**Comment by RicardovanTongeren** [comment]
Ok. Is it also possible to create those migrations with artisan? Or do I have to create the migration files?

**Comment by nWidart** [comment]
Yes, you can use `php artisan module:make-migration you_migration_name ModuleName`.

You'll find every command for modules here: http://sky.pingpong-labs.com/docs/2.0/modules

**Comment by nWidart** [comment]
Did this fix your issue ?

**Comment by RicardovanTongeren** [comment]
Unfortunately not. I first created a test module and when trying to create a migration in that module I get the following error.

```
 [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Class 'Pingpong\Generators\Exceptions\InvalidMigrationNameException' not fo  
  und                                                                          
```

Not sure why this is happening.

**Comment by nWidart** [comment]
Oh, you should check this issue: https://github.com/pingpong-labs/modules/issues/177 , someone else is having the same issue as you.
You should reply to that issue to explain your setup etc. So the creator of the Modules package (@gravitano) can debug this.
