### ISSUE TITLE
module:publish-migration

### ISSUE THREAD

**Issue by mvdstam** [AsgardCms/Platform#52]
In my opinion, the `php artisan module:publish-migration` should be part of the Composer `post-install-cmd` and `post-update-cmd`, to keep everything centralized and not force developers to change the way migrations work or the way they are executed.

See also #51.

**Comment by nWidart** [comment]
Well I didn't do this yet since it'll fill the migrations folder very quickly, for things that shouldn't be changed anyway.

Also on post-update-cmd the migrations are getting run for every module.
