### ISSUE TITLE
Route redirection does not take app.locale config into account

### ISSUE THREAD

**Issue by PhoenixII** [AsgardCms/Platform#524]
### Summary of issue
I am currently develop a theme. I installed ASGARD CMS and setup locale to 'fr' by default.
When I go to my browser and go the my frontend homepage, it always display the 'en' version of the page.
The 'fr' version of the page works if I explicitly write 'fr' in the url.

It is the same behaviour for the default backend.

### Steps to reproduce
Install ASGARD CMS as documented
Edit the config/app.php : set the locale to 'fr', let the fallback to 'en'.
Log into the backend : it is the english version which is used.

### System Details

- Operating System : MAC OS X
- PHP Version : 7.1.14
- Laravel Version : 5.5
- `Asgardcms/Platform` version 3.5.2

**Comment by PhoenixII** [comment]
After some step by step tracing, it appears that the problem may comes from the file Modules/Core/Http/routes.php :

```
$lang = null;
if (App::environment() == 'testing') {
    $lang = 'fr';
}
LaravelLocalization::setLocale($lang);
```
If you pass null to LaravelLocalization::setLocale, it falls back to the locale set in LaravelLocalization that is 'en'.

I temporary correct my problem adding :

```
else {
	$lang = config('app.locale');
}
```
before calling LaravelLocalization::setLocale

**Comment by PhoenixII** [comment]
Thanks for yours answer.
I don't see any "/backend/setting/settings/core" in the config directory. Can you specify to me where to find it ?

**Comment by Fisiu** [comment]
Treat it as part of url, ie: http://localhost:8000/backend/setting/settings/core.

**Comment by Fisiu** [comment]
Did you add your locale to `supportedLocales` array in file `config/laravellocalization.php`?

**Comment by PhoenixII** [comment]
Yes I did : 

    'supportedLocales' => [
	'fr' => ['name' => 'Français', 'script' => 'Latn', 'native' => 'Français'],
	'en' => ['name' => 'English', 'script' => 'Latn', 'native' => 'English'],
    ],

I also defined : 
'localesOrder' => ['fr','en'],

**Comment by nWidart** [comment]
Hello,

Please check the configuration in the GUI. These settings are overwriten via the gui options.

**Comment by PhoenixII** [comment]
Hello nWidart,

Thanks for your reply.

I did and tried several things but it didn't help.

Do you have an option or two in mind ?

**Comment by nWidart** [comment]
Not really, I haven't come across this issue when having multi-language websites. I'd suggest to check the configuration.

**Comment by PhoenixII** [comment]
I think I did all the tests using the configuration options but no results.
I will try to retest again some day.
For the moment, I have my workaround and a lot of work ahead :)

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
