### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by hardikaecor** [AsgardCms/Platform#53]
after installation when i go to /backend it gives me this error.

**Comment by nWidart** [comment]
That's an xdebug issue.
Please raise your maximum nesting level.

http://xdebug.org/docs/all_settings

Related to #49

**Comment by hardikaecor** [comment]
thanks, that worked.

**Comment by nWidart** [comment]
Awesome :+1:
