### ISSUE TITLE
How to edit a blank page

### ISSUE THREAD

**Issue by pddangphuc** [AsgardCms/Platform#530]
This is not the case of the backend part. Some modules simply do not show
 anything except a blank page. The modules in question are:

    - Pages
    - Media
    - Users/Roles
    - Profile
    - Api Keys
![capture](https://user-images.githubusercontent.com/39079771/39742988-b136aac6-52c9-11e8-913a-757b2ab390ef.PNG)
Thank you for your help.

**Comment by pddangphuc** [comment]
Hi nWidart,
http://testasgard.localhost/public/en/backend/page/pages
I'm using the path of the botbel
<https://docs.botble.com/cms/2.6>

**Comment by nWidart** [comment]
Ok so you need to configure your server to not have `public` in the url and it'll work.

**Comment by pddangphuc** [comment]
Why did I follow the instructions?
You can help fix it.
Thanks.

**Comment by nWidart** [comment]
It depends on your webserver.
First google result for apache: https://stackoverflow.com/questions/28364496/laravel-5-remove-public-from-url
First result for nginx: https://stackoverflow.com/questions/35646374/remove-public-from-url-laravel-5-1

**Comment by pddangphuc** [comment]
Hi, 
Why it lost css?
![capture](https://user-images.githubusercontent.com/39079771/39745746-6128d2e4-52d2-11e8-8fcf-4fb768b0651d.PNG)

**Comment by nWidart** [comment]
A possible fix here: https://github.com/AsgardCms/Platform/issues/543#issuecomment-392282208
