### ISSUE TITLE
by default the widgets doesnt show.

### ISSUE THREAD

**Issue by kamekun** [AsgardCms/Platform#532]
### Summary of issue
Try to make a simple count widget, it seen that the asgard,dashboard/admin.dashboard.blade.php is overwriting the dashboard view of the module. and don't have the widgets.

### Steps to reproduce
configure a widget nothing happens on dashboard. need to add the widget code to the overwritten view.

### System Details

- Operating System
- PHP Version 7.0
- Laravel Version 5.5.40
- `Asgardcms/Platform` version 3.5.3

**Comment by nWidart** [comment]
Hello,

This is normal, due to a change on the dashboard, widgets are not enabled by default. The default dashboard is now the "non widget" one.
You can still use the widget one by removed the published dashboard view if I remember correctly.
