### ISSUE TITLE
User ManyToMany relation

### ISSUE THREAD

**Issue by RadoslavAngelov** [AsgardCms/Platform#534]
### Summary of issue
I have added the following relation in the 'config/asgard/user/config.php :
`'relations' => [
       'favorites' => function ($self) {
            return $self->belongsToMany(\Modules\Store\Entities\Product::class, 'store__favorites', 'user_id', 'product_id');
        }
    ],`

but if I try to call the relation with `$user->favorites` - I get `null` and with `$user->favorites()` the following error occurs `Type error: Too few arguments to function Illuminate\Foundation\Bootstrap\LoadConfiguration::{closure}(), 0 passed in` .

I have putted the relation in the User.php file directly and everything is working properly.

### System Details

- Operating System - MacOS
- PHP Version - 7.2
- Laravel Version - 5.5.39
- `Asgardcms/Platform` version - 3.5.2

**Comment by RadoslavAngelov** [comment]
Hello,

thank you for your help. This way I have the relation. However when I try to call the relation this way `$product->favorites` it returns `null` so I have to call it this way `$product->favorites()->get()`. This is maybe because the relation loads when you call it, not with the `Product::class` instantiation.

**Comment by darron1217** [comment]
You can also use `$product->load('favorites')`

**Comment by mikemand** [comment]
@darron1217 is correct. I typically will load the relation first (either eager or lazy, depending on the use-case). This allows you to use `$product->favorites` to get a collection of `favorites`.

**Comment by nWidart** [comment]
I'll close this due to inactivity.
