### ISSUE TITLE
No application encryption key has been specified. Error on key generation

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#536]
### Steps to reproduce
I was attempting to install it by `php artisan asgard:install -f` command.
(I misspelled something while installation, so I was trying to install it again)
But I got error...
```
In EncryptionServiceProvider.php line 42:

  No application encryption key has been specified.
```

So I ran the command below to generate key
```
php artisan key:generate
```
Then got error...
```
In EncryptionServiceProvider.php line 42:

  No application encryption key has been specified.
```
![image](https://user-images.githubusercontent.com/8064923/39965118-4386cd04-56ce-11e8-8103-dae51c8e486c.png)

### System Details

- Operating System
- PHP Version 7.1.12
- Laravel Version 5.5
- `Asgardcms/Platform` version 3.0

**Comment by nWidart** [comment]
Try to run the `key:generate` command.

But indeed it's weird. Maybe some new behaviour in laravel if there's an env file.

**Comment by darron1217** [comment]
I've posted issue on laravel/framework repo, but they said it might be a problem of our package

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
