### ISSUE TITLE
Copy media from one server to another

### ISSUE THREAD

**Issue by naveenv1985** [AsgardCms/Platform#537]
### Summary of issue
Copy media folder from one server to another

### Steps to reproduce
I have created a website using asgard cms 2.6.1 and the whole site is ready in beta stage. Now when im moving it from beta to prod i want to copy over all the media within assets/media to the prod server as is so that the prod server works exactly as how beta is. How do i achieve this?

I have copied the media folder and on beta there are 1430 files whereas after copying to prod the files are only 1861. Also, on prod when i login to CMS and go to media module, i dont see the thumbnails as how i see it on beta where images were originally uploaded.

On prod, after copying the media dir from beta, even though the permissions are 777 for assets/media, while trying to upload a new image, i get a Forbidden error but unfortunately there is nothing in the logs. All other php.ini parameters for file uploads is all fine and checked. Please help with any pointers for debugging this issue.

Note: I have replicated the DB from beta to prod and it is working fine w.r.t other data on the site except for the images.
Could you please help me with steps or inputs as to how i can move over the whole of the media folder on beta to prod and get the prod CMS working similar to beta?

### System Details

- Operating System ubuntu
- PHP Version 7.1
- Laravel Version 5.4
- `Asgardcms/Platform` version 2.0

**Comment by nWidart** [comment]
Hello,

that's up to you to decide how you want to implement this.
Personally, I wouldn't copy anything on prod.

**Comment by naveenv1985** [comment]
Hi,
Well... basically the beta servers are pointed to prod where are the prod data were uploaded until this version of the site was pushed live. Basically in beta mode all the prod data including images were being uploaded while the old site was live.

After some more debugging, what i figured out is that there are no issues with the code or server folder permissions as i tried replicating it on a different server instance. What happens is when i connect it to the beta db i get this issue while if i connect the application to a fresh db or even a test db then upload works fine. Any idea what could be the issue?

**Comment by nWidart** [comment]
Sorry I can't help you more with this. 
You have multiple options available. You can copy all the media, this will require a copy of the database too.
