### ISSUE TITLE
Repository's paginate method has problems when caching is enabled.

### ISSUE THREAD

**Issue by xirwajim** [AsgardCms/Platform#538]
### Summary of issue

Repository's paginate method has problems when caching is enabled.

### Steps to reproduce
1.edit .env
APP_CACHE=true
CACHE_DRIVER=redis

### System Details

- Operating System CentOS Linux release 7.4.1708 (Core) 
- PHP Version 7.2.5
- Laravel Version v5.5.40
- `Asgardcms/Platform` version 3.5.3

**Comment by nWidart** [comment]
No further information given, I'll close this for now.

Feel free to re-comment if you give more information, or even better, submit a fix via a pull request.
