### ISSUE TITLE
Backend error after installation

### ISSUE THREAD

**Issue by gotroch** [AsgardCms/Platform#54]
I've just install AsgardCms and after I login backend I get:
FatalErrorException in compiled.php line 1039

from log:
PHP message: PHP  61. Illuminate\View\Engines\PhpEngine->evaluatePath() /home/pavel/Code/asgardcms/bootstrap/cache/compiled.php:14240
PHP message: PHP  62. include() /home/pavel/Code/asgardcms/bootstrap/cache/compiled.php:14206
PHP message: PHP  63. Illuminate\View\View->render() /home/pavel/Code/asgardcms/storage/framework/views/02a792ed0def4b4c8b7225a181f45171:160
PHP message: PHP  64. Illuminate\View\View->renderContents() /home/pavel/Code/asgardcms/bootstrap/cache/compiled.php:14055
PHP message: PHP  65. Illuminate\View\View->getContents() /home/pavel/Code/asgardcms/bootstrap/cache/compiled.php:14064
PHP message: PHP  66. Illuminate\View\Engines\CompilerEngine->get() /home/pavel/Code/asgardcms/bootstrap/cache/compiled.php:14077
PHP message: PHP  67. Illuminate\View\Engines\PhpEngine->evaluatePath() /home/pavel/Code/asgardcms/bootstrap/cache/compiled.php:14240
PHP message: PHP  68. include() /home/pavel/Code/asgardcms/bootstrap/cache/compiled.php:14206
PHP message: PHP  69. Illuminate\View\Factory->make() /home/pavel/Code/asgardcms/storage/framework/views/1e9c3965dee229487b53b2437e835b89:37
PHP message: PHP  70. Illuminate\View\Factory->callCreator() /home/pavel/Code/asgardcms/bootstrap/cache/co

Could you please help me? Thanks.
Pavel.

**Comment by nWidart** [comment]
Hello,

Could you try to remove the `compiled.php` path ? Using `php artisan clear-compiled` command.

**Comment by gotroch** [comment]
I run 
I run php artisan clear-compiled and error changed:
FatalErrorException in Container.php line 687

log:
PHP message: PHP  52. call_user_func:{/home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}() /home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
PHP message: PHP  53. Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}() /home/pavel/Code/asgardcms/vendo
2015/06/14 17:13:20 [error] 1724#0: *6 FastCGI sent in stderr: "tion.php:642
PHP message: PHP  93. Illuminate\Container\Container->build() /home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Container/Container.php:626
PHP message: PHP  94. Illuminate\Container\Container->getDependencies() /home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Container/Container.php:771
PHP message: PHP  95. Illuminate\Container\Container->resolveClass() /home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Container/Container.php:800
PHP message: PHP  96. Illuminate\Foundation\Application->make() /home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Container/Container.php:837
PHP message: PHP  97. Illuminate\Container\Container->make() /home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:642
PHP message: PHP  98. Illuminate\Container\Container->getConcrete() /home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Container/Container.php:620
PHP message: PHP  99. Illuminate\Container\Container->getContextualConcrete() /home/pavel/Code/asgardcms/vendor/laravel/framework/src/Illuminate/Container/Container.php:660" while reading response header from upstream, client: 10.0.2.2, server: asgardcms.app, request: "GET /en/backend HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "asgardcms.app:8000"

**Comment by nWidart** [comment]
This looks like something related to your development environment and or laravel.
This should likely be posted on the Laravel repository.

Is everything setup correctly (php, mysql, nginx/apache etc.) ? What version of php do you use ?

**Comment by gotroch** [comment]
It's Vagrant machine Laravel Homestead so it should be alright. 

I've got several Laravel dev applications running on it without any trouble.

**Comment by nWidart** [comment]
I see, I've had feedback from people using Homestead where it works great, so indeed it should be alright.

Could you get the actual error message ? We posted only until stacktrace # 52. The actual error will be at 0.

**Comment by gotroch** [comment]
It was an xdebug problem. http://stackoverflow.com/questions/13213378/what-is-causing-a-maximum-function-nesting-level-error-in-symfony-2-1-and-twig

Thank you for your support.
Pavel.

**Comment by nWidart** [comment]
Ah, if I knew that was the error I could have told you before :)

Related to #53 #49
