### ISSUE TITLE
Allowing CACHE_DRIVER=file, due to queue:restart issue

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#540]
### Summary of issue
I'm currently utilizing queue worker on test
But on CACHE_DRIVER=array , the command `php artisan queue:restart` not working.
(Because the command utilizes cache to make worker stop)

So.. is there a way to use file driver disregarding performance?

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
This is currently not possible because of the cache tags usages.

**Comment by darron1217** [comment]
Installing Redis is quite easy, so I'll just use redis :)
