### ISSUE TITLE
Custom Menu Presenter not found

### ISSUE THREAD

**Issue by bl3** [AsgardCms/Platform#541]
Hi 

i try to customize the menu layout. But i get an annoying "Class App\Http\Presenters\CustomMenuPresenter not found" error within the MenuBuilder.php

What id did so far:
- created CustomMenuPresenter Class (copy of \Nwidart\Menus\Presenters\Bootstrap\NavbarPresenter) and stored this in App\Http\Presenters.
- published the menu module to get the app/config/menu.php file and modified that by adding a new line to the styles array:
'custom-nav-bar'    => \App\Http\Presenters\CustomMenuPresenter::class,
- set the new default presenter in app/config/asgard/menu/config.php
'default_menu_presenter' => 'custom-nav-bar',
- and sure i did composer dump-autoload

does any one has a similar issue or has any idea to solve this?

**Comment by nWidart** [comment]
Hello,

I haven't had any issues with this before. Maybe worth checking out the laravel-menus github issues.

**Comment by bl3** [comment]
hi, if i create the CustomMenuPresenter in a custom Module instead of App\Http directory, it works all fine.
