### ISSUE TITLE
Half the back-end shows blank pages after fresh install

### ISSUE THREAD

**Issue by sampniels** [AsgardCms/Platform#543]
### Summary of issue
Hi, I've tried installing the CMS twice and both times everything appears to be working, homepage seems fine.

However, when I go to the back-end, several pages are completely blank(aside from the navbar top/side)

I found another issue here who described the same problem as I'm having, there's no working solution provided on that post though..

Any idea how I can fix this?

I'm using XAMPP as local webserver but it should work perfectly fine since I've already created numerous normal laravel applications with it.

Thanks!

- Niels

### Steps to reproduce
Run fresh installation then go to /backend

### System Details
Intel Core i5-6500
MSI GTX 970
16GB RAM
1TB HDD

- Operating System
Windows 10
- PHP Version
7.2.4
- Laravel Version
2.0.1
- `Asgardcms/Platform` version
Latest

**Comment by nWidart** [comment]
Hello,

This issue has been reported before. Please setup your webserver so that there is no path after the domain name. Ie no `/public` for instance.

**Comment by sampniels** [comment]
Hi,

Yeah, I've tried doing this before, nearly every post on google/stackoverflow/etc tells me to change server.php to index.php and copy-paste .htaccess from the public folder to root folder.

This has never worked for me though, whenever I try to go to my website after doing this, all the CSS is gone and everything appears broken..

**Comment by nWidart** [comment]
yea it's because the assets are trying to load for the root, ie no public path in the url.

I'm not familiar with xamp, but you should be able to set your directory to the public directory of laravel, instead of the top level one.

**Comment by sampniels** [comment]
Oh I see, right the solution appeared to be alot easier than I thought..

I'll explain below for other people having the same issue as me:

- Don't rename server.php to index.php, leave it as is.
- Don't copy-paste the .htaccess from public to root folder.

Instead(copied from https://stackoverflow.com/questions/8847392/how-to-change-xampp-localhost-to-another-folder-outside-xampp-folder)

Edit the httpd.conf file and replace the line DocumentRoot "/home/user/www" to your liked one.

The default DocumentRoot path will be different for windows [the above is for linux].

in my case, the URL( that didnt work) was: localhost/asgardcms/public/backend

After changing the DocumentRoot from D:/Program Files/xampp/htdocs to D:/Program Files/xampp/htdocs/asgardcms/public it now works perfectly fine :)

Thanks for pushing me in the right direction @nWidart :)

**Comment by nWidart** [comment]
Awesome! Glad you found out how. I'll have to keep this issue in mind for future people having the same 😄
