### ISSUE TITLE
Not finding a user with an API access token resulting in an internal server error.

### ISSUE THREAD

**Issue by joekaram** [AsgardCms/Platform#545]
### Summary
I'm having an issue with API routes when I register a new user that doesn't have an API access token.

### Steps to Reproduce
Starting with an empty database, I registered a user. The newly created user doesn't have a token. Accessing API routes that need authorization will lead to an `ErrorException: Trying to get property of non-object` in `/Modules/User/Http/Middleware/AuthorisedApiToken.php` line 44.

Since the parameter `$token` of the `isValidToken` method is null, then `$found` is `null` leading to the error on line 44. 

I suggest checking if `$found` is `null` before logging the user .

**Comment by nWidart** [comment]
Hello,

Thank you for the detailed report.
A pull request is welcome 😄

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
