### ISSUE TITLE
error instalation

### ISSUE THREAD

**Issue by pablocasas74** [AsgardCms/Platform#547]
### Summary of issue
I have a problem with the instalation

### Steps to reproduce
In the composer console i wrote the folow
"composer create-project asgardcms/platform ZY"

And an a error appears

Failed to download asgardcms/platform from dist: The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(C:\Program Files\EasyPHP\eds-www\ProgramacionGeneral\ZyWebProjects\ZyWeb\site/vendor/composer/405a2f79/AsgardCms-Platform-17ddc9e\Modules\Translation\Assets\vendor\x-editable\dist\inputs-ext\wysihtml5\bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.min.js): failed to open stream: Invalid argument

Now trying to download from source
  - Installing asgardcms/platform (2.6.1): Cloning 17ddc9ea17 from cache

  [RuntimeException]
  Failed to clone https://github.com/AsgardCms/Platform.git via https, ssh protocols, aborting.

  - https://github.com/AsgardCms/Platform.git
    fatal: destination path 'C:\Program Files\EasyPHP\eds-www\ProgramacionGeneral\ZyWebProjects\ZyWeb\site\ZY' alread
  y exists and is not an empty directory.

  - git@github.com:AsgardCms/Platform.git
    fatal: destination path 'C:\Program Files\EasyPHP\eds-www\ProgramacionGeneral\ZyWebProjects\ZyWeb\site\ZY' alread
  y exists and is not an empty directory.

**Comment by nWidart** [comment]
Hello,

The error seem to be telling you that folder already exists.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
