### ISSUE TITLE
Table settings_setting doesn't exist in database when operate migration

### ISSUE THREAD

**Issue by thevis009** [AsgardCms/Platform#549]
### Summary of issue
"Database (database/module.sqlite) does not exist. (SQL: select * from "setting__settings" where "name" = core::locales limit 1)"

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
You have to run the install command.

**Comment by thevis009** [comment]
I know that but i use command "composer update".
When i have to run install it says asgard already installed.
I tryied to reinstall and fix it with "php artisan asgard:install -f".
Then i run "php artisan serve"

>>> I configure database.php to 'default' DB_CONNECTION and add database_path.

I always not find this setting table...and Said database Do not exist.

**Comment by nWidart** [comment]
If you're running asgard in a vm/container, you need to run the install command inside that vm/container.

**Comment by karneaud** [comment]
$ `php artisan asgard:install -f`

> n Connection.php line 664:
> 
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dohlapse.setting__settings' doesn't exist (SQL: select * from `setting__settings` where `name` = core::template limit 1)

On the other hand

 php artisan module:migrate Setting

In Connection.php line 664:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'setting__settings' already exists (SQL: create table `setting__settings` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `pl
  ainValue` varchar(191) null, `isTranslatable` tinyint(1) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)


> In PDOStatement.php line 107:
> 
>   SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'setting__settings' already exists
> 
> 
> In PDOStatement.php line 105:
> 
>   SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'setting__settings' already exists


`$ php artisan module:migrate Setting`

> In Connection.php line 664:
> 
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dohlapse.setting__settings' doesn't exist (SQL: select * from `setting__settings` where `name` = core::template limit 1)
> 
>

**Comment by felipemarques** [comment]
the same error occurrs for me... i have clone the demo repository ...
