### ISSUE TITLE
After Upload Media

### ISSUE THREAD

**Issue by pharit** [AsgardCms/Platform#553]
### Summary of issue
after upload file media file is not show
https://drive.google.com/file/d/1Fhi_5c-AnS2KyTbCIFsAG1IT5BGJAk4w/view?usp=sharing

### Steps to reproduce
1. click add file
2. upload success images not show

### System Details

- Operating System ubutu 16.0
- PHP Version 7.1.18
- Laravel Version 5.5
- `Asgardcms/Platform` version 3.5.3

**Comment by tariqdev** [comment]
set APP_URL in .env file

**Comment by darron1217** [comment]
It could be related to thumbnail creation process

Thumbnail creation uses Queue. If queue is not working, though this thumbnail creation would not work
