### ISSUE TITLE
Media grid (upload popup) needs serverside pagination - Performance issue)

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#557]
### Summary of issue
Media grid (upload popup) needs serverside pagination

I have uploaded about 10,000 medias on my app.
This made the upload page slow that I had to wait about 30 seconds

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by darron1217** [comment]
Then, do you have a plan to implement it on v4?

**Comment by nWidart** [comment]
no since it's there in v3 already.

**Comment by darron1217** [comment]
What do you mean 'already'?
https://github.com/AsgardCms/Platform/blob/6d1bdc2379f859e409268d1c44b5468aab5af074/Modules/Media/Http/Controllers/Admin/MediaGridController.php#L32-L38

I uploaded all my medias on root folder (there's no subtree)
So it's still slow on v3

**Comment by nWidart** [comment]
You're not looking at the right controller.

Look at the one I linked.

However, it looks like we can remove that call from the `index` method in the admin controller though.

**Comment by darron1217** [comment]
Oh, now I understand why it's not working..
I couldn't utilize that view because, I'm not working on vuejs page. I'm currently working on pure HTML
Using `@mediaSingle` blade lead me to `MediaGridController`

**Comment by darron1217** [comment]
Then, I guess it is implemented on v3 vuejs version.
But not supported on blade template system. Right?

**Comment by nWidart** [comment]
That's correct, I still need to remove the `allForGrid` call in the controller though.

**Comment by darron1217** [comment]
But if then, `@mediaSingle` blade will not work anymore... :(
Will you remove it from the platform?

**Comment by nWidart** [comment]
hm I see, didn't think mediaSignle used that controller 🤔 

They're being replaced by their vue alternatives yeah. Though for now they still work.

**Comment by darron1217** [comment]
![image](https://user-images.githubusercontent.com/8064923/42686325-7b233a9a-86d0-11e8-9ee8-f52da3b49673.png)
Clicking button opens popup window with location `media/media-grid/index` on v3

**Comment by nWidart** [comment]
Ah yes, I remember now indeed.

**Comment by darron1217** [comment]
I created PR. Check it plz

**Comment by jaga888** [comment]
Hi again!
one more question :)
Could you add "vue-style" Media module to CKEditor?

**Comment by daothanh** [comment]
You can check here
https://github.com/AsgardCms/Platform/pull/523/commits/e6e689ff684e377be2f02c9304cfd673e92838be
