### ISSUE TITLE
Invalid argument supplied for foreach() when switching to a locale other than english

### ISSUE THREAD

**Issue by iceberg53** [AsgardCms/Platform#559]
### Summary of issue
The AsgardCMS application doesn't work properly after changing the fallback locale

### Steps to reproduce
Installing asgardCMS using  `composer create-project` and php artisan asgard:install
Adding french locale during the initial configuration process and other site related informations(website title, ...)
Adding fr locale to supported locales in config/laravellocalization.php
modifying `locale` value in config/app.php from `en` to `fr` and `php artisan config:clear` (works correctly at this point)
modifying  `fallback_locale` value in config/app.php from `en` to `fr`  and `php artisan config:clear` : outputs the following error message when hitting `CTRL+R` in the browser  

`Invalid argument supplied for foreach() (View: C:\path_to_wamp\www\site-git\Modules\Page\Resources\views\admin\index.blade.php)` 

I got the similar error message from the backend home page 

`Invalid argument supplied for foreach() (View: C:\path_to_wamp\www\site-git\resources\views\asgard\dashboard\admin\dashboard.blade.php)`

This error only happens when switching to french locale using the language switcher in the dashboard.

Apart from this, your cms is really awesome.

Thank you very much.

### System Details

- Operating System : Windows 8.1
- PHP Version : 7.1.12
- Laravel Version : 5.5.40
- `Asgardcms/Platform` version : latest (installed through composer create-project)

**Comment by lemmeV** [comment]
Ran into this issue aswell - check your lang folders. You will need to replicate all lang files to fr to use French as default

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
