### ISSUE TITLE
Composer update some sort of endless loop

### ISSUE THREAD

**Issue by armababy** [AsgardCms/Platform#56]
Hey,

Just did fresh install ``composer create-project asgardcms/platform folder``
Everything installed smoothly.

Right after that i did not modify single bit of code and ran ``composer update`` and it failed on me.

This is the output:

```bash
c update
Loading composer repositories with package information                                                                                                              
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
AdminLTE assets published.
Flatly assets published.
Assets published.
Published: Core
Published: Dashboard
Published: Media
Published: Menu
Published: Page
Published: Setting
Published: User
Published: Workshop
Running for module: core
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? [y/N] (yes/no) [no]:
 > 

 [ERROR] Aborted  
```

The last bit is on endless loop have to kill output to stop:
```bash
 Do you really wish to run this command? [y/N] (yes/no) [no]:
 > 

 [ERROR] Aborted  
```

Anything to do with my system? What kind of info you need?

**Comment by nWidart** [comment]
Hello,

This is strange, related to [modules package](https://github.com/pingpong-labs/modules). Try setting your app in `local` environment before running composer update.

**Comment by armababy** [comment]
Did that and looks like i need active db configuration.
```bash
local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)'
```

**Comment by armababy** [comment]
Looks like some laravelish issue, i went ahead and added database just to see and after that i got 
```
[ErrorException]                                                                                                                     
  call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags' 
```

**Comment by nWidart** [comment]
You need to set your cache driver to `array`, or another driver who supports cache tags.

**Comment by armababy** [comment]
Setting ``CACHE_DRIVER=array`` worked and update finished successfully.

Yet it looks like i have to populate .env file with details, to be able add sentinel for example.
Interesting if that's something on my end or it's not order of actions i should take.

**Comment by nWidart** [comment]
If you want sentinel you needed to set that up before running the `asgard:install` command. 
By default the cache driver is set to array, so I'm guessing you created the `.env` file manually ?

**Comment by armababy** [comment]
@nWidart i did not create anything, then i created .evn and aded 1 line with ``APP_ENV`` param so it's local.

Also i did not run asgard:install.

Heres steps i tried to execute:
1) ``composer create-project asgardcms/platform your-project-name``
2) ``cd your-project-name; nano composer.json``
3) add ``"cartalyst/sentinel": "~2.0",`` in require block (i see that repository already there)
4) add Aliases and Providers to ``config/app.php``
5) run ``composer update``
6) Get endless loop since laravel detects production i guess
7) Add .evn file with 1 param ``APP_ENV=local``

Something like that :D
