### ISSUE TITLE
Add Transaction on Repositories

### ISSUE THREAD

**Issue by ChristianGiupponi** [AsgardCms/Platform#560]
### Summary of issue
I have just digg into the code and I have noticed that in the EloquentBaseRepository there is no use of DB transaction. Did you use it in another place? Or just is a missing?

### Steps to reproduce
Open the EloquentBaseRepository

### System Details

- Operating System: MacOS
- PHP Version: 7.1
- Laravel Version: 5.5
- `Asgardcms/Platform` version: latest

**Comment by nWidart** [comment]
They're not used indeed.

You can use them in your own repositories of course.

**Comment by ChristianGiupponi** [comment]
It's a choice or I can send a pull request eventually?

**Comment by nWidart** [comment]
Not intentionally, but I also don't see the need. The base repository doesn't make calls cross table.

**Comment by ChristianGiupponi** [comment]
Ok, thanks for the answer
