### ISSUE TITLE
Vuejs documentation

### ISSUE THREAD

**Issue by ChristianGiupponi** [AsgardCms/Platform#562]
### Summary of issue
I have seen that some module are using vuejs and I think that the whole project will use it am I right?
There is any documentation to follow to develop new modules with vue? With the scaffold method it do not use vuejs but standard blade files

### Steps to reproduce
Create new module with scaffold

### System Details

- Operating System: MacOS
- PHP Version: 7.2
- Laravel Version: 5.5
- `Asgardcms/Platform` version: 3

**Comment by nWidart** [comment]
Indeed vuejs is used, and there's is no documentation on that.

Feel free to contribute to the documentation if you have idea.

**Comment by ChristianGiupponi** [comment]
I'm asking because I'm not able to reproduce the same thing, I'm having errors with routes, it says that the route is not defined and if I run `route:list` I do not see the apiRoutes.php

**Comment by mikemand** [comment]
Make sure that you've included the `apiRoutes.php` file in your module's `RouteServiceProvider`. By default, only backend routes are included.
