### ISSUE TITLE
Flushing abandoned medias

### ISSUE THREAD

**Issue by darron1217** [AsgardCms/Platform#563]
### Summary of issue
Media uses relation to connect media & entity.

I wanted to know whether there's built-in method to flush all media which is not linked to entity.

### System Details

- Operating System
- PHP Version
- Laravel Version
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
I don't think so. I remember someone suggested a way to do this though

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
