### ISSUE TITLE
Issue in composer memory-limit 

### ISSUE THREAD

**Issue by pc-mon** [AsgardCms/Platform#564]
I tried to install it but always composer issue:
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 36864 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php on line 205

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 36864 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php on line 205

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

I Don't know to fix it,I've Tried my ways even in php.ini but not working
can you help me please
thank you in advance

**Comment by kamekun** [comment]
That is a problem with the memory of your on server buddy neeed to update the memory something hositng blocks those upgrade on the php.ini

Regards,-

**Comment by pc-mon** [comment]
I updated but still have the issue

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
