### ISSUE TITLE
What does "status" mean in Page?

### ISSUE THREAD

**Issue by ChristianGiupponi** [AsgardCms/Platform#566]
### Summary of issue
In the Page module in the backend there is a status checkbox, what is its purpose?

![schermata 2018-07-31 alle 11 38 50](https://user-images.githubusercontent.com/1614796/43451974-8961db9a-94b6-11e8-84d5-e21658312646.png)

### Steps to reproduce
Open Page module and create a new page

### System Details

- Operating System: MacOS
- PHP Version: 7.1
- Laravel Version: 5.5
- `Asgardcms/Platform` version: 3.x

**Comment by nWidart** [comment]
Maybe yes, or just a change in the label text.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
