### ISSUE TITLE
Support PostgreSQL and SQLite

### ISSUE THREAD

**Issue by valle6** [AsgardCms/Platform#57]
Do you intend support PostgreSQL and SQLite. I think liberty to choose your databse is essential. Regards.

**Comment by nWidart** [comment]
I never was against those database, I also did not try those out though. :smiley: 

You could always try to set the database drive in the `database.php` configuration file, before running `asgard:install` and see what happens . :)

**Comment by tk-s** [comment]
Postgres install fails:

    Running for module: setting
      [Illuminate\Database\QueryException]                                                                                                                                         
      SQLSTATE[42703]: Undefined column: 7 ERROR:  column "plainvalue" of relation "setting__settings" does not exist (SQL: ALTER TABLE setting__settings ALTER plainValue TYPE T  
      EXT)                                                                                                                                                                         
      [PDOException]                                                                                                   
      SQLSTATE[42703]: Undefined column: 7 ERROR:  column "plainvalue" of relation "setting__settings" does not exist  

This is cause to postgres taking all Columnnames as lowercase if you dont put them in ".
It seems to me like the necessary quotation is working most of the time, since the column is properly created - but the alteration fails... 
(and it is probably not an asgard bug, but a eloquent or doctrine\dbal one?!)

**Comment by nisbeti** [comment]
I created an sqlite db called database.sqlite in the storage directory, then in config/database.php I changes the dafault driver to sqlite. When running ```php artisan asgard:install``` I just ignored the database questions, then it all installed OK.
