### ISSUE TITLE
Class Nwidart\Modules\Repository does not exist

### ISSUE THREAD

**Issue by chiragpipariya** [AsgardCms/Platform#570]
### Summary of issue
ReflectionException (-1)
Class Nwidart\Modules\Repository does not exist

### Steps to reproduce
We installation fresh version 4, try on login it's not working.
i change setting below from localisation file "/config/laravellocalization.php"
`  'hideDefaultLocaleInURL' => true,`
than i will try to login it's working 
but 
while i'm click to admin "Configure your website"

![download](https://user-images.githubusercontent.com/22808675/44085873-722f90ca-9fd8-11e8-9ad8-bcc7e1d30c7a.png)

I got error below error screenshot 

![screenshot](https://user-images.githubusercontent.com/22808675/44085838-509c6460-9fd8-11e8-8892-87dad3fad546.png)

### System Details

- Operating System : Ubuntu 
- PHP Version : 7.1
- Laravel Version : as per Asgard installed during installation.  
- `Asgardcms/Platform` version : 4

**Comment by nWidart** [comment]
Thanks for reporting. I'll see if I can fix it at some point. It's an easy fix so don't hesitate to contribute. 👍

**Comment by chiragpipariya** [comment]
sure

**Comment by chiragpipariya** [comment]
Any thing status on this because this error come in latest update 3.6 as your last push. @nWidart

**Comment by chiragpipariya** [comment]
@nWidart  please this error screenshot 

![whoops there was an error](https://user-images.githubusercontent.com/22808675/45013090-81aba600-b037-11e8-9a0e-4071d9089269.jpg)

**Comment by mikemand** [comment]
@nWidart See https://github.com/nWidart/laravel-modules/pull/621

**Comment by nWidart** [comment]
That's strange asgardcms v3 should still be in v2 of laravel-modules.

**Comment by mikemand** [comment]
Aye. The problem comes from here: https://github.com/AsgardCms/Platform/blob/3.0/Modules/Workshop/Providers/WorkshopServiceProvider.php#L58

The class `Nwidart\Modules\Repository` is not actually bound to Laravel's container, only the short name `modules`.

**Comment by nWidart** [comment]
Hm interesting, because it used to be:

```php
$router->bind('module', function ($module) {
    return app(\Nwidart\Modules\Contracts\RepositoryInterface::class)->find($module);
});
```
