### ISSUE TITLE
Clone Form TextArea (Ckeditor)

### ISSUE THREAD

**Issue by wassimhattab** [AsgardCms/Platform#574]
### Summary of issue
Hi,
When i clone a div where it contains inputs with name and id as array 
`
<textarea name="text[]" id="text[]"></textarea>
` 
the cloned div CK Editor is showing but not functional and all the buttons in it (bold, italic,...) affect the main ckeditor and not the cloned one. It's because the cloned textarea have the same id (text[]). 

So i changed my code and added the counter directly in the array so the cloned textarea has different id so my generated code has become like below:
`
<textarea name="text[0]" id="text[0]"></textarea>
`
`<textarea name="text[1]" id="text[1]"></textarea>`

But my problem remains the same

### Screen Shot
https://ibb.co/hgfUfz

 `Asgardcms/Platform` 3.5.3

**Comment by nWidart** [comment]
You probably have to setup the javascript as well in your clone.

**Comment by ChristianGiupponi** [comment]
Maybe a radio button would be much more clear? With two option: Enabled and Disabled, what do you think?
