### ISSUE TITLE
Base table or view not found: 1146 Table 'setting__settings' doesn't exist

### ISSUE THREAD

**Issue by karneaud** [AsgardCms/Platform#575]
### Summary of issue
TRied to reinstall asgard CMS but could not because the settin__settings database table dos not exist

### Steps to reproduce
use fresh database
run `php artisan asgard:install`

### System Details

- Operating System Vagrant Unix
- PHP Version  7.1
- Laravel Version 5.5
- `Asgardcms/Platform` version 3.0.x-dev

**Comment by nWidart** [comment]
Please try again on the `4.0.x-dev`, this looks like an installation issue.
