### ISSUE TITLE
customization on any section 

### ISSUE THREAD

**Issue by ergauravsethi376** [AsgardCms/Platform#582]
### Summary of issue
Earlier i use customize things in Module section and install new packages plus update packages(Composer update)
Earlier customization never updated with new source code
But now in module section when we composer update all customization flushed out with new data.

### Steps to reproduce
I just upgraded platform from 2.5.2 to 3.0 version i just copied whole composer.json file to my project all updation is done but once 
i triggered composer update whole customization flushed
**Please help me out over it** 

### System Details

- Operating System Windows development
- PHP Version 7.1.0
- Laravel Version 5.5.2
- `Asgardcms/Platform` version

**Comment by nWidart** [comment]
This is normal, you can't edit vendor files. Solution would be to remove your customised modules from composer, or fork the module.
