### ISSUE TITLE
hideDefaultLocaleInURL doesn't work

### ISSUE THREAD

**Issue by Josue-IT** [AsgardCms/Platform#584]
### Summary of issue

hideDefaultLocaleInURL doesn't work

### Steps to reproduce

If I set the variable hideDefaultLocaleInURL in true, inside app/config/laravellocalization.php, and I have at least two languages selected in the backend dashboard, the redirect doesn't work.

For example:
I have English, Spanish and French. If I select Spanish or French, any of the routes associated /{locale}/backend go to homeage. It should go to the backend in the language specified.

### System Details

- Ubuntu 18.04.01 LTS
- PHP 7.2.7
- Laravel 5.5.40
- `Asgardcms 3.5.3

**Comment by nWidart** [comment]
This is something to report in the package https://github.com/mcamara/laravel-localization which is responsible for this option, not asgard.

Though in my experience this option worked in the past.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
