### ISSUE TITLE
Error module setting when enable cache

### ISSUE THREAD

**Issue by linhtinh92** [AsgardCms/Platform#587]
### Summary of issue
Error module setting when enable cache

### Steps to reproduce
I enable cache in .env after click to item menu Setting in backend then it's error.

![image](https://user-images.githubusercontent.com/20183874/45104617-afd6d600-b15c-11e8-9faf-a782183ab634.png)
 

### System Details

- Operating System
- PHP Version :7.1
- Laravel Version:5.5
- `Asgardcms/Platform` version 3.6.1

**Comment by linhtinh92** [comment]
@chiragpipariya help me !

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
