### ISSUE TITLE
module creation failed

### ISSUE THREAD

**Issue by Grummfy** [AsgardCms/Platform#59]
Hello,
I have an error at module creation

$ php artisan asgard:module:scaffold

 Please enter the module name in the following format: vendor/name:
 > Grummfy/ACMS-PrivateMessage

 Do you want to use Eloquent or Doctrine ? [Eloquent]:
  [0] Eloquent
  [1] Doctrine
 > 0

 Enter entity name. Leaving option empty will continue script. [<none>]:
 > Message

 Enter entity name. Leaving option empty will continue script. [<none>]:
 > Thread

 Enter entity name. Leaving option empty will continue script. [<none>]:
 >         

 Enter value object name. Leaving option empty will continue script. [<none>]:
 > 

[Illuminate\Contracts\Filesystem\FileNotFoundException]                      
  File does not exist at path /.../Modules/ACMS-PrivateMessage/module.json

**Comment by Grummfy** [comment]
Issue came from the '-' in the module name that where removed.

**Comment by nWidart** [comment]
This seems to be intended, https://github.com/nWidart/modules/blob/2.1/Generators/ModuleGenerator.php#L107 .

I'll add in the documentation to not use dashes.
