### ISSUE TITLE
can't use '$this->imagy->get() '

### ISSUE THREAD

**Issue by akegvd** [AsgardCms/Platform#590]
### Summary of issue
i need to generate a new thumbnail for my image by use imagy class method.

my code
$this->imagy->get($file->path, 'smallThumb', true);

error is 
Impossible to create the root directory "C:\xampp7.1\htdocs\xxx\publichttp:/xxx.loc/assets/media"

I find why the path is like that and if found it in "Modules\Media\Image\Imagy.php" in line 70

> $mediaPath = (new MediaPath($filename))->getUrl();

> $this->makeNew($path, $mediaPath, $thumbnail);

and makeNew method is use $mediaPath to writeImage.

### System Details

- Operating System windows 10
- PHP Version 7.1
- Laravel Version 5.5
- `Asgardcms/Platform` version 3.x

**Comment by nWidart** [comment]
Sorry I'm not familiar with windows but it looks like the generated path is wrong.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
