### ISSUE TITLE
Error in merge config when module has a capital letter in name

### ISSUE THREAD

**Issue by ChristianGiupponi** [AsgardCms/Platform#594]
### Summary of issue
If the created module has a capital letter in the name after the first one, like `UserProfile`, the ServiceProvider can't merge the config and permission because it try to find `Userprofile` so it lowercase the whole name and capitalize the first one.  
In this way it can't find the files.  
The incriminate lines are these:

```
$this->publishConfig('userprofiles', 'permissions');
$this->publishConfig('userprofiles', 'settings');
```

as you can see the first params, that should reference the module name, is wrong and the `publishConfig` method just capitalize the first char.  
If I change the name in `userProfile` everything works correctly.

NB: this do now happen on homestead but on a live server, maybe homestead manage the filesystem in a different way.

### Steps to reproduce
1. Create a new module like: `UserProfile`
2. Run the site

### Possibile solution
Maybe the best thing is add the name without any manipulation from the module package, just the first char to lowercase at least

### System Details

- Operating System: Ubuntu
- PHP Version: 7.1
- Laravel Version: 5.5
- `Asgardcms/Platform` v3 version

**Comment by ChristianGiupponi** [comment]
Am I the only one with this issue?

**Comment by nWidart** [comment]
I haven't come across this before, might something in the publish config method or laravel. Have you looked into that?

**Comment by ChristianGiupponi** [comment]
I have noticed that in `Modules\Core\Traits\CanPublishConfiguration.php` at line 18 there is:

$this->mergeConfigFrom($this->getModuleConfigFilePath($module, $fileName), strtolower("asgard.$module.$fileName"));

it use strtolower on the module name so I get `userprofile` instead of `userProfile`.

**Comment by nWidart** [comment]
I see. Makes sense then that you can't use `UserProfile`.
