### ISSUE TITLE
Remove > Illuminate\Foundation\ComposerScripts::postAutoloadDump  from pakacge

### ISSUE THREAD

**Issue by karneaud** [AsgardCms/Platform#599]
### Summary of issue
I'm trying to install your project without the dev files and get the following

> Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
>  @php artisan package:discover
> In Application.php line 635:
>   Class '\Barryvdh\Debugbar\ServiceProvider' not found
> Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

perhaps we can remove this from the default 

### Steps to reproduce

1) run `composer create-project asgardcms/platform src --prefer-dist --no-dev`

### System Details

- Operating System = Vagrant Ubuntu
- PHP Version  7.0
- Laravel Version - 5.4.
- `Asgardcms/Platform` version - 3.6.1

**Comment by mikemand** [comment]
The real issue stems from here:

https://github.com/AsgardCms/Platform/blob/e43253627a55601e5e86b5372d6d2e40bc368b57/app/Providers/AppServiceProvider.php#L34

I think we can safely remove this check since Debugbar will automatically be discovered if it is installed.
