### ISSUE TITLE
Error with Vuejs - Refresh page show AssetNotFoundException

### ISSUE THREAD

**Issue by ChristianGiupponi** [AsgardCms/Platform#602]
### Summary of issue
I'm migrating a module to Vuejs using PageModule as source since there is no documentation at the moment.  
I was able to show the listing and the creation form, the problem is that if I refresh the creation page I get:

> Modules \ Core \ Foundation \ Asset \ AssetNotFoundException
> No message

I have noticed that this issue does not happen in the page module, so how can I solve this?

**Comment by bhaveshdaswani93** [comment]
Can You please provide solution for That, i am also facing the same issue after installing the new module using scaffold command.
