### ISSUE TITLE
[Bug] Asgard not finding theme's module view

### ISSUE THREAD

**Issue by karneaud** [AsgardCms/Platform#620]
### Summary of issue
I'm overriding the default module views in my theme for the User module but it cannot find it 

The structure of my theme has the module at /Themes/Truth/views/modules/user/public/index.blade

### Steps to reproduce
1) Add a blade for user module in Flaty/modules/user/public
2) Integrate blade template into existing root blade template
3) View respective paage

### System Details

- Operating System - Liniux
- PHP Version - 7.0.32
- Laravel Version - 5.5.43
- `Asgardcms/Platform` version 3.6.1

**Comment by mikemand** [comment]
Hi @karneaud,

Make sure you've enabled `useViewNamespaces` for `frontend-theme` in `/config/asgard/user/config.php`, at the very bottom.
