### ISSUE TITLE
User (published) migrations not used during Http Test

### ISSUE THREAD

**Issue by xfudox** [AsgardCms/Platform#637]
### Summary of issue
Trying to make an Http test, retrieving an user to access backend page give me an 
    

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB.users' doesn't exist (SQL: select * from `users` where `email` = xxx@yyyy.zzz limit 1)

Using mysql instead of sqlite, logging in and checked there are no tables in db.

Published migrations from a custom module, re-run the test, same error but modules tables have been created in db.

### Steps to reproduce
Test:

       public function it_can_view_module_entity_index()
        {
            $user = User::where('email', ' xxx@yyyy.zzz')->first();

            $response = $this->actingAs($user)
                                ->get(route('admin.module.entity.index'))
                                ->assertStatus(200);
        }

Setup:

        protected function getEnvironmentSetUp($app)
        {
            $app['path.base'] = __DIR__ . '/..';
            $app['config']->set('database.default', 'testing');
            $app['config']->set('database.connections.testing', array(
                'driver' => 'mysql',
                'database' => 'DB',
                'username' => 'laravel',
                'password' => 'laravel',
                'host' => 'database',
                'port' => '3306',
            ));
            $app['config']->set('translatable.locales', ['en', 'it']);
            $app['config']->set('modules.paths.modules', __DIR__ . '/../Modules');
            $app['config']->set('cartalyst.sentinel.users.model', User::class);
            $app['config']->set('asgard.user.config.fillable', [
                'name',
                'slug',
                'is_active',
                'client_id',
                'client_secret',
            ]);
            $app['config']->set('asgard.user.config.login-columns', [
                'email',
            ]);

        }

Reset database:

        private function resetDatabase()
        {

            // Makes sure the migrations table is created
            $this->artisan('migrate', [
                '--database' => 'testing',
            ]);
            // We empty all tables
            $this->artisan('migrate:reset', [
                '--database' => 'testing',
            ]);
            // Migrate
            $this->artisan('migrate', [
                '--database' => 'testing',
            ]);
            $this->artisan('migrate');
        }

### System Details

- Windows 10 Pro - build 17134
- PHP 7.1.22
- Laravel Framework 5.5.40
- Asgard 3.x

**Comment by nWidart** [comment]
I'm not sure why the cause here is. You're saying the tables have been created, but it still says it can't find the user table.

**Comment by xfudox** [comment]
I found the problem: i didn't imported the UserServiceProvider in my test class, now all the User's module tables are correctly created.

My fault.

**Comment by nWidart** [comment]
Ah awesome that's good to know! 

Thanks for telling the solution for future users 👍
