### ISSUE TITLE
Problems in login after installing asgard cms successfully 

### ISSUE THREAD

**Issue by Sajib32** [AsgardCms/Platform#66]
When I want to login, it shows this errors. pls help.
Method [group] does not exist on view. (View: H:\xampp\htdocs\demoapp\Themes\Adminlte\views\layouts\master.blade.php) (View: H:\xampp\htdocs\demoapp\Themes\Adminlte\views\layouts\master.blade.php)

**Comment by nWidart** [comment]
Hello,

Did you upgrade an older installation ?

**Comment by Sajib32** [comment]
what does you mean by older installation? i just simply do as the asgard installation video does. Pls explain in details @nWidard

**Comment by nWidart** [comment]
On older installation means you already had asgard installed... and updated today.

**Comment by Sajib32** [comment]
no i have just installed asgard today.

**Comment by nWidart** [comment]
Okay, I managed to reproduce the error, checking what went wrong with the modules tags.

**Comment by Sajib32** [comment]
i am stuck with this problem. what should i do now?

**Comment by nWidart** [comment]
You can run a composer update now.

I've fixed the issue, and tested by making a clean install, all back to working ok.

**Comment by Sajib32** [comment]
thanks...problem fixed.... @nWidart

**Comment by nWidart** [comment]
Awesome! :smiley: 

If others have similar issue:

Composer is for some reason getting version `1.0.3` of the settings module when running `composer create-project asgardcms/platform`, a `composer update` right after fetches the right version again (`1.0.8`).

**Comment by Sajib32** [comment]
oh thanks for sharing this also..... @nWidart
