### ISSUE TITLE
Swap Sentry for Sentinel as default auth library 

### ISSUE THREAD

**Issue by vuchl** [AsgardCms/Platform#69]
Catalyst annouced today the release of sentinel to open source and the deprecation of Sentry:
http://www.reddit.com/r/PHP/comments/3aytt2/sentinel_authentication_authorization_library/
https://github.com/cartalyst/sentinel

**Comment by nWidart** [comment]
Yup, I've tweeted this on the AsgardCms account, I'll get to it as soon as possible. :)

**Comment by vuchl** [comment]
Great! I'm not using twitter so I had no idea.

**Comment by joshbrw** [comment]
+1

**Comment by nWidart** [comment]
done.
