### ISSUE TITLE
Version 4 - style issue?

### ISSUE THREAD

**Issue by ChristianGiupponi** [AsgardCms/Platform#696]
### Summary of issue
After a new setup the arrow in the admin menu are huge and the hamburger menu is messed up

![Schermata 2019-04-10 alle 10 24 46](https://user-images.githubusercontent.com/1614796/55863530-fbca7d00-5b7a-11e9-83d0-e6922ef0e1e2.png)

And:

![Schermata 2019-04-10 alle 10 25 47](https://user-images.githubusercontent.com/1614796/55863550-07b63f00-5b7b-11e9-90dd-9909e8d39799.png)

No issue in console, can't figured out why. Any idea?

### System Details

- Operating System: Ubuntu 18.04
- PHP Version: 7.2
- Laravel Version: 5.7
- `Asgardcms/Platform` version: master ( 4.x)

**Comment by nWidart** [comment]
Hm strange, might be some css file missing, nothing in network tab that 404s or something?

**Comment by mikemand** [comment]
Check the sidebar templates [here](https://github.com/AsgardCms/Platform/tree/master/resources/views/vendor/sidebar). If I remember correctly, they are fixed here in Asgard (in `/resources/views/vendor/sidebar`), but not in the Sidebar package.
