### ISSUE TITLE
The problem with modules based on vue.js

### ISSUE THREAD

**Issue by LukaszNiziolDWG** [AsgardCms/Platform#697]
### Summary of issue
I have a problem with the operation of all modules based on vue.js. All index pages are empty. I have no errors in the console. I don't know where to look for a solution. It doesn't help me anything.

The modules don't operate locally and on the server. I work locally on the Linux Mint.

I am asking you for help.

### System Details

- Operating System: Linux Mint
- PHP Version: 7.2.1
- Laravel Version: 5.5

**Comment by nbdamian** [comment]
Have you run the following commands in the terminal in the root of the install?
`npm install
npm run dev`

**Comment by LukaszNiziolDWG** [comment]
Yes. Installation (npm install) and npm run dev work correctly. When you edit views (npm run watch), the compilation also executes. Unfortunately, the pages still remain empty.
