### ISSUE TITLE
Can't upload OTF files using Media Dropzone

### ISSUE THREAD

**Issue by LiamMcArthur** [AsgardCms/Platform#711]
### Summary of issue
Asgard does not allow the upload of OTF files, even when they are added to the `allowed-types` in the asgard media config file.

### Steps to reproduce

1. Add `otf` to the allowed types in `config/asgard/media/config.php`
2. Try to upload an otf font file using the media uploader

### System Details

- Operating System
- PHP Version 7.2.11
- Laravel Version 5.5.44
- `Asgardcms/Platform` version 3

**Comment by assghard** [comment]
Do you have an API key generated?
/backend/account/api-keys

**Comment by LiamMcArthur** [comment]
Yes I have an API key set up and the media folder definitely exists. The website can upload other files no problem. The allowed-types in my config file are:

`'allowed-types' => '.jpg,.png,.pdf,.jpeg,.ttf,.otf',`

I can upload jpg, png, pdf, jpeg and ttf - but otf fails with the following error:

Here is a [screenshot of my error](https://imgur.com/RsQ6Zv4).
