### ISSUE TITLE
Code discussion, aren't we need to use parent::create() here?

### ISSUE THREAD

**Issue by arturmamedov** [AsgardCms/Platform#712]
https://github.com/AsgardCms/Platform/blob/e22a39da42b4b6bc89eebc64450bd01892e466e5/Modules/Menu/Repositories/Eloquent/EloquentMenuItemRepository.php#L20

**Comment by arturmamedov** [comment]
I think that if we use repository design pattern we need to create trough `parent::` if there isn't some particular things, that i not see.

This is because for me in example, i have additional code for all repositories directly in `EloquntBaseRepository` and i want that it was called wvery time for every repository, and if i change my logic i remove it in only one place and i'm done.

Also in `EloquntMenuRepository` and  `EloquentTagRepository` i not see the use of parent for create and update

**Comment by nWidart** [comment]
Hey,

This is not a requirement from the pattern. 
Here it wasn't done because there's no need to perform the parent code.

What you want could be achieved with events for instance.
But you're right the same could be done by using:

```php
    public function create($data)
    {
        event($event = new MenuItemIsCreating($data));
        $menuItem = parent::create($event->getAttributes());

        event(new MenuItemWasCreated($menuItem));
        return $menuItem;
    }
```

**Comment by arturmamedov** [comment]
Okay, thank u! I change my code for call parent:: any way, if you want i can do a pull request after.

This because i need to unset empty locales before saving for not save not translated thing, also before update
