### ISSUE TITLE
artisan module:publish    and  error:  1215 Cannot add foreign key constraint

### ISSUE THREAD

**Issue by scil** [AsgardCms/Platform#72]
mysql defualt engine does not default foregin key ,

so  edit Modules\Menu\Database\Migrations\2015_04_02_184200_create_widgets_table.php , 
add
```             $table->engine = 'InnoDB'; 
```

**Comment by nWidart** [comment]
Thank you for reporting this, I'll add the InnoDb engine asap. :+1:

**Comment by nWidart** [comment]
All modules have been updated with this.
