### ISSUE TITLE
Issue in User backend permission tab

### ISSUE THREAD

**Issue by chauhanabhi88** [AsgardCms/Platform#728]
### Summary of issue
Issue in permission tab once click on permission tab in user module at backend

### Steps to reproduce
Login to backend
Click on edit user once you on edit page click on permission tab It shows blank & In console.log It give below error.
[Vue warn]: Error in render: "TypeError: _vm.permissions[subPermissionTitle] is undefined"

found in

---> <AsgardPermissions> at Modules/User/Assets/js/components/AsgardPermissions.vue
       <ElTabPane> at packages/tabs/src/tab-pane.vue
         <ElTabs> at packages/tabs/src/tabs.vue
           <ElForm> at packages/form/src/form.vue
             <UserForm> at Modules/User/Assets/js/components/UserForm.vue
               <Root> vendor.js:124188:7
TypeError: "_vm.permissions[subPermissionTitle] is undefined"

### System Details

- Operating System
- PHP Version 7.1
- Laravel Version 5.7
- `Asgardcms/Platform` version 4.0.0
![asgardcms_issue](https://user-images.githubusercontent.com/8176647/65323749-d92b9e00-dbc7-11e9-86df-360e33c90434.png)

**Comment by mikemand** [comment]
This should have been fixed with #726. Did you recompile after updating composer?

`composer update && npm run dev`

**Comment by chauhanabhi88** [comment]
Thank you for the help
