### ISSUE TITLE
Force SSL On Login Page

### ISSUE THREAD

**Issue by joshbrw** [AsgardCms/Platform#74]
Title is self explanatory :)

**Comment by nWidart** [comment]
Hm this shouldn't be default behaviour, in my opinion. 
And if you do need ssl, redirect using nginx/apache. That's how it's handled on asgardcms.com

I could possible add a middleware for this, that users optionally can add in the global middleware stack.

**Comment by joshbrw** [comment]
A default "Redirect to SSL" middleware in the global stack would be nice.

**Comment by nWidart** [comment]
This is basically the middleware: https://github.com/AsgardCms/Website/blob/develop/app/Http/Middleware/Secure.php

**Comment by nWidart** [comment]
I'm not going to include this middleware by default, as some will very likely want to customise it.
