### ISSUE TITLE
dashboard not show widgets

### ISSUE THREAD

**Issue by Lamvumr** [AsgardCms/Platform#748]
### Summary of issue
Follow all the steps in the guide, but the widget not appear on the dashboard.
Link guide: https://asgardcms.com/docs/v3/dashboard-module/widgets

### Steps to reproduce
1. Create widget class
2. Create widget blade
3. Registering the widget: add widgets array in module.json

### System Details

- Operating System
- PHP Version - 7.1 or higher
- Laravel Version - 5.5.*
- `Asgardcms/Platform` version - 3.6.1

**Comment by Plasto13** [comment]
Replace view in _your app\resources\views\asgard\dashboard\admin\dashboard.blade.php_ for _your app\Modules\Dashboard\Resources\views\admin\dashboard.blade.php_

**Comment by Lamvumr** [comment]
Thank you very much, it worked for me.
