### ISSUE TITLE
Clear settings cache after update

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#76]
Clear the settings cache after updating settings

**Comment by nWidart** [comment]
Fixed in [Settings/1.2.0](https://github.com/AsgardCms/Setting/releases/tag/1.2.0)

**Comment by miadz** [comment]
i have problem with cache ,
 when i use file setting for cache in .env file ,
getting this error "tagging not support"
then change setting to default and clear cache , route , view ,
but i get this error
Route [media.grid.ckeditor] not defined.
some time get error "default" view not found.

porblem is backend route 
http://asgard.dev/public/en/backend

but this route work
http://asgard.ir/public/en
