### ISSUE TITLE
Unable to install/update via composer

### ISSUE THREAD

**Issue by Innercode** [AsgardCms/Platform#769]
### Summary of issue
Can't install a fresh copy of AsgardCms via composer create-project asgardcms/platform your-project-name

Also a composer update on an existing installation will cause the same error.

Will give the error after installation: 
In LaravelLocalization.php line 1040:
                                            
  Class 'Illuminate\Support\Env' not found  

### Steps to reproduce
composer create-project asgardcms/platform your-project-name

### System Details

- Operating System: Ubuntu Server 20.04
- PHP: Version 7.4.10
- Laravel Version: 5.5 according to composer.json
- `Asgardcms/Platform` version: latest

**Comment by mikemand** [comment]
This is an issue with the localization package: https://github.com/mcamara/laravel-localization/issues/747

If you want to get started now, clone (or download a zip) of Asgard then modifying your `composer.json` to add a section (I put mine above `required`):

```json
	"conflict": {
        "mcamara/laravel-localization": "1.6.0"
    },
```

After that, do `composer update` and then you can install Asgard as normal with `php artisan asgard:install`.

**Comment by Innercode** [comment]
That solves the problem. Thanks!
