### ISSUE TITLE
error while creating new module

### ISSUE THREAD

**Issue by jaimingohel** [AsgardCms/Platform#79]
i have tried to create new module with command:-  php artisan asgard:module:scaffold

but its givving me error like this 

![rsz_1screenshot_from_2015-07-15_153825](https://cloud.githubusercontent.com/assets/9151223/8696276/8a67fde6-2b08-11e5-9761-30f53593208c.png)

**Comment by vuchl** [comment]
Just hit enter, then the defauilt value ("Eloquent") will be used. Nonetheless this needs fixture.

**Comment by jaimingohel** [comment]
tried that also still same error...

**Comment by nWidart** [comment]
Thanks for reporting, I'll get to it asap. :smile:

**Comment by nWidart** [comment]
Just tested on my local version, not updated yet to latest laravel version, and works great. So I'm guessing laravel broke something related to this again.

**Comment by jaimingohel** [comment]
which version you are having? i have laravel 5.0

**Comment by nWidart** [comment]
Just updated to 5.1.7, and it's broken on that version indeed. I was on 5.1.4 before.

AsgardCms doesn't run on 5.0 anymore.

Checking now what they broke.

**Comment by jaimingohel** [comment]
i'm having laravel version 5.0.33

**Comment by nWidart** [comment]
You shouldn't be on 5.0. 

Anyway, no idea what was broken, the `choice()` method doesn't seem to work anymore, whatever I try.

**Comment by nWidart** [comment]
Problem seems to come from the Symfony ChoiceQuestion class.

I've hardcoded the entity type to Eloquent for now.

On [1.4.1](https://github.com/AsgardCms/Workshop/releases/tag/1.4.1)
