### ISSUE TITLE
Authentication & Authorization.

### ISSUE THREAD

**Issue by mvdstam** [AsgardCms/Platform#86]
In continuation of #83.

I found that one of the biggest issues in Asgard concerning portability and integration into existing applications, is the way the User module works at the moment; it's way too much globally-oriented.

AsgardCMS uses Sentinel to handle all authentication and authorization-related logic in the CMS. Awesome, although Sentinel is used as if the CMS is the "complete" application and not simply the backend of an existing application. In other words, your CMS users, roles, permissions and other Sentinel-related information is stored *in the same tables* as your front-end users, possibly overriding already existing roles or changing existing information where it isn't necessary.

Instead, the User module should ship with it's own migrations file containing the tables that Sentinel needs, but *prefixed* so those tables live in their own namespace. The User module can then, using it's own Service Provider, override some of the bindings that Sentinel does regarding the underlying classes for Roles, Users, and other Sentinel-related models, where the correct cms-prefixed tables are used instead.

Secondly, the `/auth` path should also live *behind* the backend prefix (default: `/backend`), since we're not authenticating a "normal" user, but rather a CMS user. The CMS user should also be stored in a different session key. In my opinion, it should be completely possible to use AsgardCMS (with the user-module included by default) along side with an existing Sentinel-based user authentication/authorization system.

*As a side note: I highly recommend prefixing __all__ tables that AsgardCMS generates with the same prefix (`asgard_`), so it's immediately apparent which tables belong to Asgard and which do not.*

**Comment by nWidart** [comment]
This is intended. Your 'front-end' users are the same, just in a different table.

I'd strongly advice **not** to use separate tables for your 'front-end' users. An agency I worked for before did this, it was hell.

Again, Sentinel is used as default, you can choose to use whichever driver you wan.t

**Comment by nWidart** [comment]
No more update on this, I'll close this issue for the time being.

I'm always available on slack/here to discuss this further.
