### ISSUE TITLE
Asgard-based middleware

### ISSUE THREAD

**Issue by mvdstam** [AsgardCms/Platform#87]
In continuation of #83.

AsgardCMS ships with a fixed set of middleware:

```
'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
'Illuminate\Cookie\Middleware\EncryptCookies',
'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
'Illuminate\Session\Middleware\StartSession',
'Illuminate\View\Middleware\ShareErrorsFromSession',
'Maatwebsite\Sidebar\Middleware\ResolveSidebars',
'App\Http\Middleware\VerifyCsrfToken',
```

Unfortunately, Laravel 5 does not (at least not at the time of writing) allow for a way to define global middleware dynamically from within a ServiceProvider.

It is, however, possible to achieve this from within the `Kernel.php` file itself using the `handle` method:

```php
/**
     * Handle an incoming HTTP request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function handle($request)
    {
        if ($request_is_for_backend) {
            $this->middleware = [
                'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
                'Illuminate\Cookie\Middleware\EncryptCookies',
                'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
                'Illuminate\Session\Middleware\StartSession',
                'Illuminate\View\Middleware\ShareErrorsFromSession',
                'Maatwebsite\Sidebar\Middleware\ResolveSidebars',
                'App\Http\Middleware\VerifyCsrfToken',
            ];
        }

        return parent::handle($request);
    }
```

This is in my opinion, a fairly clean and not intrusive way to include the necessary middleware that Asgard needs without touching the existing middleware stack of the existing application. Determining whether or not the request is meant for Asgard should be fairly straightforward, especially if __all__ traffic meant for the CMS (including authenticating users, see #86) is prefixed.

**Comment by nWidart** [comment]
I recently learned it is possible to set the global middleware via an API. [See this issue](https://github.com/laravel/framework/issues/6211).

I do not understand why you want this. As you can see these are all middleware from Laravel and not AsgardCms as you suggested in #83, for the exception of the Maatwebsite one. Maatwebsite could probably register its middleware using that API, but that needs to be discussed on their package.

All the others are standard from laravel. And not only required for the backend. This is why it's in the Kernel.php file, to which you have access, to customise as you need. But I'd strongly advice to keep those.
