### ISSUE TITLE
Conditional loading of the CMS

### ISSUE THREAD

**Issue by mvdstam** [AsgardCms/Platform#88]
Continuation of #83.

The entry point of the whole Asgard stack, including the pingpong modules ServiceProvider, is the `AsgardServiceProvider`. This Service Provider should really check if the request was actually meant for the CMS or not (again: this should be straightforward if all traffic going to the CMS backend has a consistent prefix). If the latter is the case, no further bootstrapping or initialization should take place, since the request isn't meant for the CMS at all but apparently for the front-end application.

**Comment by nWidart** [comment]
This seems logical.

Any request is suppose to be for the CMS, since we're in the CMS. Note: the front-end is also the CMS.

**Comment by nWidart** [comment]
No more update on this, I'll close this issue for the time being.

I'm always available on slack/here to discuss this further.
