### ISSUE TITLE
Missing AdminLTE.css in 1.2.0 using composer create-project

### ISSUE THREAD

**Issue by gverschuur** [AsgardCms/Platform#89]
Following the [installation instructions](https://asgardcms.com/en/docs/getting-started/installation) I installed a new version of Asgard which resolved to 1.2.0. I also did the `php artisan asgard:install` command. 

However, it tries to load the following file 

	public/themes/adminlte/css/AdminLTE.css

which was removed in this commit 04b0d2f077f22a5a1647ceaf1b150f8f78147a99 so the admin/login is unstyled.

**Comment by nWidart** [comment]
Thank you for reporting the issue.
Forgot the login screen still used that file, will fix it asap.

**Comment by nWidart** [comment]
Fixed in [1.2.2](https://github.com/AsgardCms/Platform/releases/tag/1.2.2)
