### ISSUE TITLE
Using media library when creating record

### ISSUE THREAD

**Issue by Thorazine** [AsgardCms/Platform#91]
When creating a new record and wanting to use the media library/api, the entity is null. Therefore the api doesn't seem to be functional when creating.

When editing a record the module works like charm:

@include('media::admin.fields.file-link-multiple', [
		    'entityClass' => 'Modules\\\\Event\\\\Entities\\\\Event',
		    'entityId' => $event->id,
		    'zone' => 'image'
		])

But when creating a record the entityId is null because there is no id yet which results in an error.

As a sidenote, the trait extension "Modules\Media\Support\Traits\MediaRelation" does not work. Adding the actual files() trait manually in the model does.

**Comment by nWidart** [comment]
Like it's stated in the docs, the current state doesn't let you add media on create, only on edit.

The trait does work, I'm using it on multiple projects. Can't help you without more information.
