### ISSUE TITLE
Error creating module migration using module:make-migration

### ISSUE THREAD

**Issue by gverschuur** [AsgardCms/Platform#92]
When running the following command (in Asgard 1.2.2)

`php artisan module:make-migration mymigration Mymodule`

I get the following error:

`PHP Fatal error:  Class 'Pingpong\Generators\Exceptions\InvalidMigrationNameException' not found in /vendor/pingpong/modules/Commands/MigrationCommand.php on line 105`

If I go looking for any file/class with such a name or located in that namespace I get 0 results.

**Comment by nWidart** [comment]
Hello,

This issue should be added on the Modules package.
I'll fix this asap.

**Comment by nWidart** [comment]
Fixed in [443d20](https://github.com/nWidart/modules/commit/236cbfbbd4aef12277b340efba83999687443d20)
