### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by ashissh200025** [AsgardCms/Platform#96]
My cmd stuck on getting token after running 
composer create-project asgardcms/platform your-project-name
AT point Token<hidden>

**Comment by nWidart** [comment]
Hello,

What do you mean by " point token " ?
Do you mean composer is asking for a token ? If so, this is not related to AsgardCms but just standard composer stuff where you need to set a new github token to download more packages.

**Comment by ashissh200025** [comment]
ok thanx

**Comment by ztvMark** [comment]
https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by mikemand** [comment]
I don't know when this will go into effect, but pretty soon you won't have to get a new token anymore. :D

https://github.com/composer/composer/issues/4884#issuecomment-195229989
