### ISSUE TITLE
Missing login layout/blade file when using a new theme

### ISSUE THREAD

**Issue by gverschuur** [AsgardCms/Platform#97]
When I create a new frontend theme using `asgard:theme:scaffold` and enable the theme using the backend, the login page throw an error that the `layouts.account` file is missing. The file isn't in my theme's `/views/layouts` folder because it isn't generated during scaffolding. If I switch back to Flatly it works correctly.

I think there are 2 ways to go here:

Copy the login.blade.php layout file to the AdminLTE theme and include it from there instead of the custom theme. It seems like this is the intended functionality because only the login template is loaded from the custom theme, all the other assets (stylesheets etc) are loaded from the AdminLTE theme.

**or**

Copy `login.blade.php` in the new theme during scaffolding.

**Comment by nWidart** [comment]
It's not created by default because it's up to you to create it.
It's not included in AdminLTE on purpose so it's easily customisable.

**Comment by gverschuur** [comment]
A weird design decision imho, but if that's the intended functionality I'll go ahead and close this one.
