### ISSUE TITLE
Adding a backend route

### ISSUE THREAD

**Issue by Thorazine** [AsgardCms/Platform#99]
We have been trying to add a backend route for more functionality. In this case ordering the table. But with every attempt we take to add a route (in the backendRoutes.php file) we get a 302 in response and get a redirect to the index page.
We have looked our little hearts out online for any documentation, but have found none.
In other words, is there a possibility to add backend routes. If so, is there another action we have to take to register that function.
As for a route, this is what we add before the resource (we made our own pages module): $router->post('/nppage/nppages/order/post', ['as' => 'nppage.nppage.order', 'NppageController@order']);

**Comment by nWidart** [comment]
Hello,

After adding a route in the `backendRoutes.php` file, you need go create a permission for that route and give yourself (or a group) the permission to access that route.

**Comment by Thorazine** [comment]
That is actually a very shiny and logical solution. I like it!

So I added 'nppage.nppage.order', to the permissions and gave myself rights in the permissions tab. But I'm still doing something wrong. Any tips?

**Comment by Thorazine** [comment]
It is alive:

For the person looking for a manual.

Within your backendRoutes.php file of the module (inside the group->prefix) you add a route:

```
$router->post('/nppages/order', ['as' => 'admin.nppage.nppage.order', 'uses' => '\Modules\Nppage\Http\Controllers\Admin\NppageController@order']);
```

Everything behind the @ is the permission for your permission.php config file. Don't forget to give yourself rights in the rights menu.

To make everything more clear: look for the PermissionsMiddleware in the core module.

**Comment by nWidart** [comment]
Thanks for the explanation @Thorazine , I'll try to add that in the docs. A video will be coming out one of these days with this info in it, it was recorded a while ago, just never had the time to edit it.

**Comment by iliyaskhan** [comment]
I am still getting the same 302 response. I can confirm that the permission is given and backendRoute is
$router->get('ajaxserver', ['as' => 'admin.plutos.plutos.ajaxserver', 'uses' => '\Modules\Plutos\Http\Controllers\Admin\PlutosController@ajaxserver']);

Can you help me getting this work?

**Comment by iliyaskhan** [comment]
Got it working now with few changes.
```
$router->get('plutos/ajaxserver', ['as' => 'admin.plutos.ajaxserver', 'uses' => 'PlutosController@ajaxserver']);
```

And for permissions
```
return [
'plutos.plutos' => [
        'index',
        'create',
        'store',
        'edit',
        'update',
        'destroy' 
		],
'plutos.ajaxserver' => ['ajaxserver']
];
```

**Comment by nWidart** [comment]
Like I said on Slack, you should not use the adminRoutes file for api routes.
If you open the RouteServiceProvider of your module, you'll see there is a method to load API routes, use that.
